### ISSUE TITLE
Missionary with 0 Spreads does not die and can still spread (and then die)

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#10049]
~~When I use `unit:SetSpreadsLeft` unit window stop showing both ReligionStrength and SpreadsLeft paramteres, so there are only moves showing up.~~

What's more, Missionary with Spreads=0 after changing the number of spreads via lua is still alive and can do Spread Mission.

**Comment by adaneslavo** [comment]
This can be related to GetSpreadsLeft function, because I used:
```
unit:SetSpreadsLeft(unit:GetSpreadsLeft() - 1)
```

**Comment by adaneslavo** [comment]
It got 0 spreads because double GameEvent triggering. It's ok with window, but still 0 Spreads can spread.

**Comment by azum4roll** [comment]
Well, the game really isn't supposed to have a 0-charge missionary.

The following scenarios will still be considered a bug:

1. Check charge before spread: missionary spread button does nothing and it dies
2. Check charge on turn start/end: missionary disappears

We should fix the root cause (event fires twice?) instead.
