### ISSUE TITLE
GameEvents.PlayerCanBuild function seems broken.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1020]
In the CP (12-18), this function doesn't seem to work at all resulting in function errors. I've tested it with other players. But in older CP versions, the function seems to work.

**Comment by ilteroi** [comment]
i haven't messed with this at all.

just checked the code, it seems to be negative test, so you can prevent a unit from building something on lua side. that correct?

anyway, it's called like this, don't see anything obviously wrong there:

  #if defined(MOD_EVENTS_PLOT)
	if (MOD_EVENTS_PLOT) {
		if (GAMEEVENTINVOKE_TESTALL(GAMEEVENT_PlayerCanBuild, getOwner(), GetID(), getX(), getY(), eBuild) == GAMEEVENTRETURN_FALSE) {
			return false;
		}
	}
  #endif

**Comment by LoneGazebo** [comment]
I was thinking it might be related to the changes to plots/builds with recent versions.

G

**Comment by ilteroi** [comment]
well, what exactly does "not working" mean?

- is the LUA event triggered?
- if it is, is the return value being ignored?
- if it is not, what else could be the problem?

**Comment by TechpriestEnginseer** [comment]
The LUA event isn't triggered at all.

**Comment by ilteroi** [comment]
looks like i need a firetuner tutorial.

anyway, asking the stupid question: you are sure EVENTS_PLOT is active, right?

otherwise, i see only one possibility.there might have been a bug in CvPlayerTraits::HasUnitClassCanBuild(), which is called before the LUA events trigger. it's a bit strange because it should lead to not being able to chop, while apparently your problem is the opposite. anyway, it has since been fixed. can you retry with the latest version?

**Comment by TechpriestEnginseer** [comment]
When it's EVENTS_PLOT not EVENT_PLOT.
...

**Comment by LoneGazebo** [comment]
Praise the Omnissiah!
