### ISSUE TITLE
AI not expanding

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#10387]
There are several reports of the AI not expanding beyond a few cities (3-5). You recently changed this, could you look into it @ilteroi?

Furthermore, if anyone has a savegame+mod list that would be very helpful.

**Comment by ilteroi** [comment]
i'm not aware of any recent changes, and everything is fine for me. still on 3.10 ...

**Comment by adaneslavo** [comment]
3.10 is fine.

**Comment by ilteroi** [comment]
so i checked and it turns out AI doesn't build settlers if at war ... that seems ... exploitable.

i removed that check, it seemed redundant, they check whether they are *losing* a war anyhow.

**Comment by bsesar** [comment]
Perhaps the inability to make peace treaties (due to a bug in Deal AI?, recently fixed) and the consequent never-ending wars combined with the above check were the cause of lack of expansion? I guess 3-5 cities was the max a civ could expand before having it's first war and after that no settlers would be built.
