### ISSUE TITLE
4.2.7 - AI continues not to expand

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#10422]
See https://github.com/LoneGazebo/Community-Patch-DLL/issues/10421

for all of the game details.

Issue: The AI continues to not expand aggressively. It just took tarsus (its eastern most city) a few turns ago. otherwise its left a wide stretch of gorgeous land unclaimed (and its an authority civ with 4 cities, it should want to expand more).

**Comment by ilteroi** [comment]
i'm getting sick of this. next week it's going to be uhh, the map is full of crap cities.

anyway, there is a thing called GetSettlePlotQualityMeasure(). together with Expansion flavor of the leader it determines how "good" a potential settle plot must be. absent any overriding concern (happiness, siege, strategies, ...) the combination of plot quality and personality determines if they will build a settler. i've now lowered the threshold. fingers crossed.

**Comment by ilteroi** [comment]
ok found a new issue: m_pUnitProductionAI->GetWeight() is zero for pioneers. so AI never builds pioneers. somebody else needs to fix.

**Comment by azum4roll** [comment]
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/14953746/0bc5942d-55bc-429c-af46-e6a2b88efe0d)
I believe m_pUnitProductionAI->GetWeight() is a combination of UnitFlavor and CityStrategyAI.
Settlers do have flavors so it has to be the latter, but I don't understand the code at all.

**Comment by ilteroi** [comment]
so i checked this flavor thing ... and maybe flavors for citystrategyai are simply broken?

every time a strategy is adopted or ended all flavors are reset to zero instead of doing a delta update on the previous state.

this happens is in FlavorUpdate(). but that piece of code was added by @LoneGazebo himself in 2018 ... is it possible that this went unnoticed for so long?

**Comment by LoneGazebo** [comment]
I saw my name mentioned but now it’s gone? Anyways I remember working on this and I’m going to pass the homer as the code merged at that time wasn’t mine, but rather Putmalk’s

**Comment by ilteroi** [comment]
so it turns out the flavors aren't zero but actually negative:

```
033, The Iroquois, Osininka, Flavor, FLAVOR_EXPANSION, 55
033, The Iroquois, Osininka, Flavor, FLAVOR_EXPANSION, -45
033, The Iroquois, Osininka, Flavor, FLAVOR_EXPANSION, -245

039, The Maya, Tikal, Flavor, FLAVOR_EXPANSION, 56
039, The Maya, Tikal, Flavor, FLAVOR_EXPANSION, -44
039, The Maya, Tikal, Flavor, FLAVOR_EXPANSION, -244
```

but during lookup negative values are reported as zero.

improved the log, now it tells interesting stories

```
#turn, player, city, flavor, current, change, reason
255, Sweden, Stockholm, FLAVOR_EXPANSION, -167, 30, CITYSPECIALIZATION_SETTLER_PUMP, start
257, Sweden, Stockholm, FLAVOR_EXPANSION, -117, 30, CITYSPECIALIZATION_SETTLER_PUMP, end
257, Sweden, Stockholm, FLAVOR_EXPANSION, -147, -4, CITYSPECIALIZATION_GENERAL_ECONOMIC, start
265, Sweden, Stockholm, FLAVOR_EXPANSION, -571, 200, AICITYSTRATEGY_ENOUGH_SETTLERS, end
```

but the numbers just don't add up. the plot thickens ...

**Comment by ilteroi** [comment]
> I saw my name mentioned but now it’s gone? Anyways I remember working on this and I’m going to pass the blame as the code merged at that time wasn’t mine, but rather Putmalk’s

yeah, i realized i had misread the code ... turns out there is a difference between -= and =- 

so that's why i deleted the comment.

**Comment by LoneGazebo** [comment]
haha yeah i can still be summoned! I wish I could do more right now...

**Comment by ilteroi** [comment]
so this should be fixed now for good. 

* the flavor inconsistencies were cause by military AI interfering
* there was a bad city strategy check for detecting isolated cities
* AI settlers sometimes got stuck in a loop between two city sites

**Comment by bsesar** [comment]
I would like to add some of my observations on the AI expansion obtained from my VP 4.4.2, Communitu Continents map, Standard run (no ruins, tech trading or other mods). Here is a [save](https://github.com/LoneGazebo/Community-Patch-DLL/files/13823332/Ottomans.zip) around turn 150 (medieval) and zipped [logs](https://github.com/LoneGazebo/Community-Patch-DLL/files/13823336/Logs.zip).

By turn 150, I (Ottomans) have ten cities, while Japan, Greece, and Babylon each have only 3 (actually, Babylon built the 4th city only in the last dozen or so turns, I think). The interesting thing is that the spacing between cities of Progress civs (Greece and Babylon) is 5 tiles, while for Japanese cities is 4 tiles (perhaps because they went Tradition)?

Babylon and Japan have been warring with Greece that is sandwiched between them and I suspect that these wars are the main reason why they are not settling cities. The wars themselves are not going anywhere and neither side is taking any cities at this point. They just peace out eventually.

@ilteroi, does the separation between cities depend on the policy tree (e.g., 4 for Tradition, 5 for Progress)? Perhaps it would make sense to reduce this spacing to 4 regardless of the civ or policy tree (well, maybe not for Polynesia). Also, perhaps the building of Settlers could be pushed up in priority even in the time of war.

**Comment by ilteroi** [comment]
there is no direct relation between policy and city sites; but indirectly they are linked by leader personality.

also, only *losing* a war should stop expansion. nevertheless i just tweaked the logic yet again ... let's see.
