### ISSUE TITLE
city governor using laborers over specialists

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10434]
for some reason the governor prefers laborers over specialists in city states.

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/29f7d49c-061e-4c0b-be4a-6165736a37b5)

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/3bec986c-5c08-45a1-9e0b-a9c5ea99f971)

default focus, food to spare.

**Comment by tomekpa** [comment]
5 Happiness against 25 unhappiness, im impressed you have any surplus food any way since unappiness gives quite large food intake nerf. Usually when i had similar issues there were some logical explanation. 
In this case it probably does not want to grow, since its already very unhappy. 
To set example to extreme,  what is the point to prioritize food, when you have -100% growth due to happiness?
And on the other hand specialists generate Urbanization, which can exceed city size. therefore, what is left are labourers.
I mean im guessing, what happend, but the more i investigated this issues, the more i learned to trust governors :)

**Comment by ilteroi** [comment]
1. this is a city state, don't know how happiness works for them
3. unclear if this behavior could affect majors as well
2. food being useless it typically an argument for using specialists, not against
4. as it happens i've written a lot of code for the governors and so i don't trust them

**Comment by ChordaCiv** [comment]
![59556](https://github.com/LoneGazebo/Community-Patch-DLL/assets/146994485/d5ce5122-672a-4415-bb04-8fa25c0220f0)
Major civs do not like to have specialists either. Despite of having 5 "free" slots, as you can see, still zero.

**Comment by reikken** [comment]
this is a particularly big problem for venice, since you can't override the buggy governor in your other cities

**Comment by ilteroi** [comment]
@axatin is the maintainer now, please fix

**Comment by axatin** [comment]
Fixed in 1685c78
