### ISSUE TITLE
Air Interceptor promotion line available for infantry/melee but cannot be chosen

### ISSUE THREAD

**Issue by tomekpa** [LoneGazebo/Community-Patch-DLL#10453]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7_

PS. Can paste zipped mods but its 200Mb

_2. DirectX Version_

_3. List of Other Mods_

'(1) Community Patch'
'(2) Vox Populi'
'(3a) VP - EUI Compatibility Files'
'(4a) UI - Promotion Tree for VP'

'(9d) Reforestation for VP v.5'
'(over) More Unique Components for VP (v 87)'
'(overhaul) Even More Resources for Vox Populi (v 11)'
'(overhaul) More Wonders for VP (v21)'
'(overhaul) Unique City States for VP (v15.10)'
'(ui) Trade Opportunities for VP (v21)'
'Better Lakes for Vox Populi (v 2.5)'
'Convert Caravans and Cargo Ships (v 4)'
'Global - Civilians Move After Purchase (v 2)'
'Global - Pro-rata Buildings Purchase (v 2)'
'Improved City View (v 20)'
'Maps - Rotate Start Position (v 13)'
'Monopoly Buildings for Vox Populi (v 3.5)'
'Provincial Palace (v 3)'
'TreeSuccession (v 37.12)'
'UI - Enhanced Demographics (v 6)'
'UI - No Auto-Embark Workers (v 7)'
'UI - Overlay Barbarians (v 8)'
'UI - Overlay City Limits (v 8)'
'UI - Overlay Luxuries (v 3)'
'UI - Overlay Resources (v 11)'
'UI - Overlay Road And Rail (v 9)'
'UI - Overlay Unimproved Tiles (v 1)'
'Units - Cheap Workboats (v 2)'
'Units - No Mechs (v 6)'
'Worker Mountaineering (v 2)'

_4. Describe the Issue_

Air Interceptor promotion line available for infantry but cannot be chosen.
I was thinking, maybe eventually, some research will allow to take it, but im in modern era, and i still cant.
I checked Archery, Skirmisher and Armour lines and they seems fine. Just Melee. 
Not sure also if that was the case for the whole game, but i think not.
But it showed relative early comparing to the time you have first AA units. Maybe Industrial era, dont really
remember since at that point i wasnt sure its correct behaviour, thou i suspected not.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

![obraz](https://github.com/LoneGazebo/Community-Patch-DLL/assets/21251138/07594bb1-1e1b-438e-8122-ee3950853617)

**Comment by tomekpa** [comment]
Don't get it, thought it is integrated, also, one need your knowledge to know its junky xD

**Comment by ryanmusante** [comment]
Is there not enough room to display the full tree, in the mod?

**Comment by n-core** [comment]
> Is there not enough room to display the full tree, in the mod? What is the problem with the mod?

The problem with the mod is that it's limited by the room to display all possible promotion branches because the mod is written in such a janky way. I did try to figure out what's wrong with the mod because it won't show all of my custom promotion branches, and I gave up trying to do that and just disabled the mod. <sub>~(Also advocate to remove the mod from the VP installation.)~</sub>

**Comment by azum4roll** [comment]
Any promotion with interception chance requires the unit to have an intercept range (= able to intercept).

`	if (GetAirInterceptRange() <= 0)
	{
		if (pkPromotionInfo->GetInterceptChanceChange() != 0)
			return false;

		if (pkPromotionInfo->GetInterceptionCombatModifier() != 0)
			return false;

		if (pkPromotionInfo->GetNumInterceptionChange() != 0)
			return false;
	}`

Promotion Tree does have a check for CanAcquirePromotion, but the function doesn't return why the unit can't have the promotion (it can be due to lack of prereq, for example). There seems to be no way to know for sure in lua unless explicit checks for intercept range is added.

**Comment by axatin** [comment]
Promotion Tree has been removed from VP
