### ISSUE TITLE
CTD after pressing end turn about 200 turns in

### ISSUE THREAD

**Issue by maptap** [LoneGazebo/Community-Patch-DLL#10586]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

_3. List of Other Mods_

(5) Enlightenment Era edited by CAYM (for VP 4.4)(v10) (2)
(over) More Unique Components for VP (v 87)
(overhaul) More Wonders for VP (v22.1)
Civic And Reform (v 22)
Enginseer's Wholesome Tweaks (v 12)
Historical Religions Complete (BNW or GK) (v 45)
InGame Editor+ (v 46)
Jarcast's Bigger Huge Map for Communitu_79a (v 3)
National Wonder Collection (v 3)
The Timurids for VP
Vox Populi's Bare Necessities (v 12)
Wonder Race (v 7)
World Congress Reformation (v 12)

_4. Describe the Issue_
202 turns in the game crashes to desktop when beginning to process Korea's turn. I reproduced this many times.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13897232/QuickSave.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13897250/Database.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13897264/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_
Just press end turn.

Thanks!

**Comment by Nu-Illasera** [comment]
Since nobody else is answering you, i would recommend just ... find the mod conflict yourself

Start with vanilla + CP + VP only.
then add mods as you go.

Its not ideal but if you can't get someone to look at the code and debug it, you may to pinpoint exactly what causes the conflict (If it is, a conflict in mods).

**Comment by azum4roll** [comment]
Since the CTD is at turn 200+, it's going to take a long time.

Investigating the minidump is the way to go but I don't know how.

**Comment by maptap** [comment]
Yeah 200 turns is a very long time for that :(
Thanks for the advice though, I really appreciate you guys trying to help.

**Comment by axatin** [comment]
The issue is caused by a building BUILDING_QALHAT_DUMMY and is somehow related to great work theming bonuses, but I'm not exactly sure what went wrong. The error happened in a turn before the turn of the save game, that's why I can't really tell what happened. Do you still have some earlier save games?

**Comment by maptap** [comment]
Sorry for taking so long to respond. Here is an earlier saved game from 2
turns prior.
Thanks so much!
