### ISSUE TITLE
Incorrect damage preview when killing units

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#10758]
There was a recent change that units that are killed deal reduced damage to the attacker (@azum4roll, your change I think?) This is not reflected in the combat preview.

Issue is consistently reproducible.

**Comment by azum4roll** [comment]
It's part of CvUnitCombat::GenerateMeleeCombatInfo(). No way that can be exposed to Lua.

**Comment by ilteroi** [comment]
assume a defender with 1 hp left.

old state: damage dealt incorrect in the sense that it's higher than remaining hp. damage taken technically correct but implausible since defender is almost dead.

new state: both damage dealt and damage taken are incorrect but consistent. the same fraction of damage dealt and damage taken will be applied to the respective units.

progress!
