### ISSUE TITLE
AI Building/Unit priority algorithms

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1101]
Working on a new model for unit/building production and selection that depends less on flavors.

**Comment by TechpriestEnginseer** [comment]
Is there a solution for production overflow of units?

In Quick game speed, most, if not all, take 1 turn to produce at some point in the game. Of course this solution is when you have some production left over from a previous project then the production should carry onto the next project. But the problem is how can a production carry onto the next project that already cost 1 turn to produce? (Ex. Massing 1-turn cost units when the city has basically no more buildings nor wonders to overflow into).

**Comment by LoneGazebo** [comment]
No, overflow stops after 1 turn to prevent exploitation.
G

**Comment by LoneGazebo** [comment]
I've got this pretty much rewritten now. Flavors still exist, but they are a base value that is modified by 'real' value, so it's much more rational now.

G
