### ISSUE TITLE
city governor working too many laborers

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#11046]
v4.9

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/40d54382-ffe7-439a-8303-0128898e165c)

something is wrong with specialist assignment.

in the screenshot (antium) we have 5 laborers for a total of -10f5p5g. by working the jungles + herbalist bonus they could generate 12f5p5s. food might not be the highest prio because of unhappiness but there are also unused specialist slots.

assignment often is not stable. by changing the focus of the governor from default to something else and back you get a different assignment then what the default governor did over multiple turns. often the laborers are completely gone (eg in ravenna).

assignment also seems to run twice (check citytilescorer log).

[AutoSave_0230 AD-1600.zip](https://github.com/user-attachments/files/16021172/AutoSave_0230.AD-1600.zip)

whoever messed with this please fix, i'm not touching it any more

**Comment by axatin** [comment]
The save is not from 4.9, and I can't load it with 4.8 either

**Comment by ilteroi** [comment]
this is weird:

[103848] CvGame.cpp[10998]: CvGame::Read - Savefile was generated from gamecore version Release-4.9.1 bde9b87dc Dirty

but i just checked, i have infoaddict and removebanluxury mods on top. maybe that could be the problem

**Comment by axatin** [comment]
The save requires Community Patch version 130 to load, which is not 4.9

**Comment by ilteroi** [comment]
i don't understand ... what is wrong. anyway i have a feeling the issue is quite easily reproducable

**Comment by axatin** [comment]
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/95587882/3c7a3588-6255-4895-947a-a22acb708fc7)
4.9 is not Community Patch Version 130, but Community Patch Version 131.

I was able to load it now by manually editing the modinfo, but something is messed up in your mod files

**Comment by axatin** [comment]
There are no errors in the assignment process as far as I can see, only the valuations could maybe be tweaked.

You have a growth mod of -95%, so 3 food are actually 0.15 food. Your city has -7 unhappiness and your empire is also unhappy, so the AI actively wants to avoid growth. Taking these together, the AI values food at 0.

> we have 5 laborers for a total of -10f5p5g.  by working the jungles + herbalist bonus they could generate 12f5p5s

No, laborers do not consume more food than worked plots. The correct comparison would be 0.6f5p5s vs. 5p5g

The only thing left is that the AI values 1 gold higher than 1 science, and that's because you have 7 Poverty in the city but only 2 Illiteracy. I'll try to tweak that a bit, but I'm very hesitant to make any large changes as those might break a lot of other things again.

**Comment by ilteroi** [comment]
thanks for the analysis and yes, you're right about the food. so it's more a question of science vs gold. i thought science has a higher value but yeah, it's debateable.

but there are other issues as well:

* why did the governor work laborers when there are "real" specialist slots available
* why is the resulting assignment different after changing/resetting the governor

**Comment by azum4roll** [comment]
I think yield values shouldn't depend on unhappiness that much, unless the city/empire is already unhappy AND changing the assignment reduces the unhappiness.
