### ISSUE TITLE
CTD during 1st AI turn 

### ISSUE THREAD

**Issue by victoranohin** [LoneGazebo/Community-Patch-DLL#11282]
_1. Mod Version 
VP + ¾ UC (v87), Even More Resources for Vox Populi, and supersettler modpack with EUI: 4.16.0_VP-SSEM-EUI.zip
Downloaded from official tread https://forums.civfanatics.com/threads/voxpopuli-modpacks-update-4-16-0.685164/

_2. DirectX Version
DX 10 & 11

_3. List of Other Mods_
No mods, clear install, clear cache

_4. Describe the Issue_
Game Civ: doesnt matter
Map name: doesnt matter
If i choose to start from the latest era, the game always CTD during first AI turn, no matter what i try.
Both on EUI and nonEUI versions.

_7. CvMiniDump.dmp File 
[CvMiniDump.dmp](https://github.com/user-attachments/files/17017750/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_
Just start any game and set up the starting era to latest

**Comment by skodkim** [comment]
Maybe this is connected to an issue that I (and other users) seems to be having where the game starts crashing upon entering the medieval era. 

My setup is highly modded so it doesn't really make any sense to make a proper error report, but apart from minor changes this mod is the only one that has been updated since it started.

**Comment by Cyclopia31** [comment]
I have the problem of OP when I start on the last era, no issue if I start in ancient era.
