### ISSUE TITLE
Unit pathfinding still bugged

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1149]
See screenshot. Pathfinding chooses do embark a unit and then disembark, which is completely unnecessary.
Latest version of the mod.
![2016-01-25_00001](https://cloud.githubusercontent.com/assets/16341598/12562165/57db3e14-c3ac-11e5-8e02-ee7dfc51e354.jpg)

**Comment by ilteroi** [comment]
savegame would be extremely helpful

**Comment by ilteroi** [comment]
ok. not a real bug but fixed as far as possible.

the effect stems from the fact that land units have a different amount of moves when embarked. so in this case it's "cheaper" to embark, move one extra tile and then disembark (because fewer movement points are spent entering the hill - 2 vs 4).

i think it has always been like that. anyway we now always assume the worst case when switching domains (ie check both movement rates, use the higher one). this also means domain changes in general are discouraged now.

needs some testing to see if there are unexpected side effects.

**Comment by ilteroi** [comment]
ok, seems to be fine

**Comment by LoneGazebo** [comment]
Coolio.
