### ISSUE TITLE
Religion EUI Tooltip Error?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1223]
![image](https://cloud.githubusercontent.com/assets/13937047/12839663/6d71f2ea-cb90-11e5-99dd-fec4ae879bb2.png)

**Comment by LoneGazebo** [comment]
Bad install?

**Comment by TechpriestEnginseer** [comment]
Probably. Issue fixed in 2/5.

**Comment by LoneGazebo** [comment]
I'll look, but I know the religious tooltip was working for me when I pushed the 2-1 EUI update. Hasn't been touched since.

G

**Comment by TechpriestEnginseer** [comment]
This is just by hovering over the faith in the CityView.lua, so I have to assume it's referencing the function GetFaithTooltip which seems to be working fine until it hits

```
tips:insert( GetReligionTooltip( city ) )
```

**Comment by LoneGazebo** [comment]
Right, I get that. It was working fine the other day, so I'm quite confused. I'll take a look.

**Comment by LoneGazebo** [comment]
Report this to bc1, as the code is all his (I've checked, can reproduce, but don't know why).

**Comment by Iamblichos** [comment]
This is why I dislike his MO stance on his EUI mod. Imagine if whoward took that kind of stance on his VMD DLL? Imagine how many mods would be neutered or non-existant.

**Comment by ricanuck** [comment]
Yep, I saw this one in 2.2 version, not gamebreaking but a little pain in the behind given the overall neo-perfection of G's efforts... as of bc1, I stopped interacting with him a long time ago due to his pseudo-assorifice attitude. That's why I proposed to G in the open forum to decide on a final EUI version for CBP and stick with it forever... not that bc1 is adding anything meaningful to EUI for the last year or more.

**Comment by LoneGazebo** [comment]
Techpriest, can you replicate this with just the CP and EUI (i.e. not using my compatibility files)?

**Comment by TechpriestEnginseer** [comment]
This is replicated without the CP. It's a problem on bc_1's end.

**Comment by LoneGazebo** [comment]
Okay, cool, just making sure it wasn't actually me. :)

**Comment by LoneGazebo** [comment]
Let me know if/when he fixes.

**Comment by Iamblichos** [comment]
...at least this is a minor issue outside the CPP codestream. Imagine if it wasn't?

**Comment by LoneGazebo** [comment]
Well, no offense to bc1, but he seems to take an "I am infallible" approach to EUI, which can be harmful. Takes a lot to get him to admit it was a bug in his code. I, on the other hand, am a paragon of humility. :)

**Comment by Iamblichos** [comment]
Well, the difference being, you're just a normal good guy to deal with, and you don't pretend a given mod is more important than it actually really is. The EUI is nifty and cool, no doubt, but it isn't a game changer. It's handy, but handiness shouldn't be given special status (which he thinks it deserves).

**Comment by Iamblichos** [comment]
This is a simple and easy fix. He's got the two functions out of order. Since they are local functions he simply he needs to have local function GetReligionTooltip(city) defined BEFORE local function GetFaithTooltip( city ).

![2016-02-08_00001](https://cloud.githubusercontent.com/assets/14372214/12893915/8bd0e6bc-ce59-11e5-819d-f725ca87d2c8.jpg)

**Comment by Iamblichos** [comment]
Has to be fixed this way in both files (the EUI) and in the CP.

**Comment by LoneGazebo** [comment]
Makes sense (I haven't looked at it yet). Once I do, I'll fix it. Thanks for research!
G

**Comment by Iamblichos** [comment]
Of course, anytime.

**Comment by LoneGazebo** [comment]
Seems to have worked. I'll update the next version.
