### ISSUE TITLE
Can`t make peace

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1233]
I have beaten the Osmans, and he is willing to make peace.
However, even though he accepts, we remain at war.
Also, is it intentional that a peace deal does not include all allied CS anymore? I have a lot, and adding them manually is tedious.
[I don`t even.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/120732/I.don.t.even.zip)

**Comment by ilteroi** [comment]
CS are indeed no longer added to the deal because they made it invalid (so you couldn't accept it). chicken and egg problem where you can't make peace with a CS when at war with their ally.

however, that was a quick fix, maybe it's better to work around the "blocked peace" in another way.

can't say anything about the deal not going into effect.

**Comment by LoneGazebo** [comment]
I'm working on the CS issue.
