### ISSUE TITLE
LUA Clarification and Possible Suggestion

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1251]
What is iResolution, iChoice, bEnact referring to?
Is iResolution referring to the Civ5Resolution tag where RESOLUTION_PLAYER_EMBARGO is one example?
What is iChoice referring to?
What is bEnact referring to?
Is bPassed believing that if passed will return true and if not passed will return false?

I know that the World Congress API is hardcoded, but if it is possible, then could a iPlayerAffected be created? (Ex. I have a decision that is toward a certain civ and if enabled, then I could use GameEvents.PlayerPlunderedTradeRoute.Add(function(iPlayer, iUnit, iPlunderedGold, iFromPlayer, iFromCity, iToPlayer, iToCity, iRouteType, iRouteDomain) end) or some other game events to incur a penalty/bonus to them)

And could resolutions also be flavored? I would like the AI to use them to their advantage since there is basically no XML tag to indicate how negative or positive it could be for any AI civilization.

**Comment by LoneGazebo** [comment]
iChoice is Yes/No/Player etc. (i.e. the resolution decision). bEnact is whether it is being enacted or repealed. bPassed is if it succeeds or fails.

**Comment by LoneGazebo** [comment]
There's no logic for resolution flavoring, and it doesn't have a flavoring weight system (thus the AI doesn't 'get it' if the stuff isn't hardcoded). I appreciate that on one hand (as it's not chaotic evil flavors), but it's also DLL limited.

Do what JFD is planning to do and make a separate table that you store off dummy policies or whatnot on. Otherwise, the data isn't easily accessible (few functions in the WC logic run every turn).

**Comment by TechpriestEnginseer** [comment]
So, does iResolution be called normally like this then?
````
function blahblah(iResolution, iChoice, bEnact, bPassed)
if iResolution == RESOLUTION_PLAYER_EMBARGO then
end
end
````

**Comment by LoneGazebo** [comment]
Yep!
