### ISSUE TITLE
Water areas dividing across international date line of map

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1319]
@ilteroi, 

It seems like water areas on a contiguous ocean are not always the same. This seems to happen right around the 'date line' of the map. This becomes a problem in the operational functions that look for naval units in the same area as a muster/target.

So, should we fix the area IDs, add a 'are these areas touching?' function in the map, or should we have the operational AI simply generate a path instead of checking area IDs?

**Comment by ilteroi** [comment]
i'd much prefer fixing the pathfinder, but i see nothing in the "area finder" code which could cause this. quite strange.

on a related note, i've been thinking about having an "area connectivity matrix" because especially for naval units there's a lot of unnecessary pathfinding. unfortunately it's not so easy because of ever changing passability (ice, borders, forts, cities). so it's like not worth the effort.

**Comment by LoneGazebo** [comment]
I think area divisions happen in the map scripts, not in the DLL specifically.

There's the 'landmass' functionality of the map- possible to mirror that for water tiles?

**Comment by ilteroi** [comment]
well, there's code for area assignment and for landmass assignment in the pathfinder too.

which map script did you use? i cannot reproduce it

**Comment by LoneGazebo** [comment]
Just a standard continents map. Maybe it was a weird quirk, who knows.

G
