### ISSUE TITLE
A few smaller issues

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1352]
See this thread:

http://forums.civfanatics.com/showpost.php?p=14180617&postcount=4576

**Comment by ilteroi** [comment]
_1. If you use player:Found() to give a civ a city, the game crashes on that civ's next turn. Workaround: create a settler and use unit:PushMission() to force the settler to found the city. Is there something that the mission does that :Found() doesn't?_

checked the code, can't really see a difference. probably needs the debugger to find the place where it's going wrong

_2. Barbarian (player id 63) cities appear to undergo absolutely insane growth. They easily get above size 50 while other civs are sitting in the teens. This doesn't happen with major or minor civilizations. For some reason some of their plots seem to be giving civ 63 (and only civ 63) massive amounts of food. When the city is captured by any other civ, it quickly city starves itself down to a proper size. It's not some promotion or building or trait i'm giving them, because the Barbarian Civilization (whose id is not 63) doesn't experience this, yet has the same trait._

we never run out of surprises ... can't think of a reason for that

_3. Barbarian (player id 63) appear to be able to build every unique unit in the game unless you specifically override them to nil. Did you change the way unit class overrides work? As far as i'm aware this was not the case in vanilla._

not my domain ;)

_4. The "CanMoveAllTerrain" flag on Promotions causes units to be able to enter water tiles (?!) and they don't switch to embark graphics. Calling UpdateEmbarkGraphics() doesn't fix this. As far as i'm aware this was not the case in vanilla._

probably my fault. but what is the expectation?

**Comment by LoneGazebo** [comment]
2. I'll take a look 
3. I didn't, but I'll take a look.
4. Not sure. I mean, units with that promotion are supposed to be able to move anywhere (like helicopters).

**Comment by Iamblichos** [comment]
In regards to #4, I believe we made Helicopters not embark. Discussed this a long time ago on here.

**Comment by ilteroi** [comment]
just checked a barbarian city for super food tiles, no issue in this sample of one ...

![image](https://cloud.githubusercontent.com/assets/1358966/13476142/b6675634-e0c6-11e5-932d-6a564a0d3dd0.png)

also never noticed extraordinary growth for barbarian cites before.

**Comment by LoneGazebo** [comment]
Me either, but I'll keep an eye on it.

**Comment by LoneGazebo** [comment]
Something else, @ilteroi : http://forums.civfanatics.com/showpost.php?p=14184934&postcount=4622

**Comment by ilteroi** [comment]
hmm. traderoutes to foreign cities work at least

![image](https://cloud.githubusercontent.com/assets/1358966/13507200/eef199b8-e181-11e5-99dd-168ba2052519.png)

**Comment by ilteroi** [comment]
also can't reproduce the missing gold from city connection.

**Comment by LoneGazebo** [comment]
Sounds good, I'll assume its a mod conflict.
