### ISSUE TITLE
C4DF top panel issue

### ISSUE THREAD

**Issue by shaglio** [LoneGazebo/Community-Patch-DLL#1407]
I play with just the CP and regular EUI. When I downloaded the latest beta (3/1) and the C4DF add-on, the top panel has the Vassal Overview button, but all the other buttons I usually have are missing. Previously, when I would download the latest CP betas, I would have to delete the LUA folder. Should I do that as well for the C4DF?

**Comment by JFDaly** [comment]
This is because C4DF replaces the part of the Interface that EUI uses to turn the Dropdown into various buttons. It's probably too early in C4DF (re-)development to ask for Putmalk to add an EUI compatible version, but that's what will be needed.

**Comment by mwhiter** [comment]
Once I have a reliable way of testing the EUI version I can attempt to solve issues. However, I don't play with them :( so it's hard for me to debug these issues. In fact, I don't even play with CBP so it's even harder to debug or test balance issues for that.

Looking at your issue, it appears you only have Community Patch and EUI, is  that right? If so, that's even further out of my testing range because I have no idea how EUI works or is structured, and I work with CP and non-EUI only. I'm not sure how to enable that functionality, nor do I know how similar it is to the CBP EUI version, so I'm not sure.'

At this moment, there are a lot of unknowns for me.

**Comment by LoneGazebo** [comment]
@mwhiter , if you look at the files in the EUI compatibility files, you'll see where I integrated your C4DF code into the CBP's EUI code. I've marked it, though I'm fairly certain that you could just the lua from that folder for the C4DF + EUI, as all the functionality in the CBP needs functions in the CP (just like C4DF).

**Comment by shaglio** [comment]
@mwhiter "Looking at your issue, it appears you only have Community Patch and EUI, is that right?"  Correct.  I use just CP with the regular (bc1) version of EUI, and am interested in trying the C4DF alongside them.

PS I assume you're Putmalk then?

**Comment by mwhiter** [comment]
Yes sir, that's me.

I never considered EUI and CP only for development which is why you're having issues. Following G's advice, at some point in the near future I need to support this. I'm juggling lots of things at the moment and haven't really developed for a few days but I plan on putting a few hours of work tonight when I get home. 

I need to finish squelching bugs in preparation for the full release of the new version (which honestly I doubt is that too far off), and then I need to support my standalone version (and host my code on my personal github).

Sorry for any delay in support!

**Comment by shaglio** [comment]
I started a game last night with the latest non-beta release and, since it had been so long since I've played with the Vanilla UI, I forgot that the leftmost button on the top right has a drop-down list of all the overviews/modules and things.  So the game is completely playable with CP, C4FD, and EUI together.  It's just odd that the EUI top panel got overwritten by C4DF, when I deleted the Top Panel LUA files from both the CP and C4DF folders.

**Comment by JFDaly** [comment]
It's not the TopPanel that activates those buttons, its the DiploCornor.xml/lua

**Comment by LoneGazebo** [comment]
@JFDaly is correct.

**Comment by shaglio** [comment]
He usually is!  Deleting those 2 files worked perfectly.  I am now celebrating a We Love The Modgesty Day!
