### ISSUE TITLE
Can't enhance a religion acquired via conquering the holy city

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1424]
Just shipping it here, to a safe place where it won't get lost. Just in case.
http://forums.civfanatics.com/showpost.php?p=14193496&postcount=179

**Comment by joosegoose** [comment]
Yep, also have this. :( Logs included (note--modpack version).

On a more positive note, I was really loving this feature otherwise. Just after taking Piety, I missed out on the last religion by a couple of turns. The civ that beat me was my closest neighbor, Suleiman...needless to say I changed plans and took Istanbul. :) Between this bug and the "voluntary capitulation" bug the war didn't turn out how I intended, but these new features are really adding a lot to the game. Thanks for the dedication.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/168314/Logs.zip)
