### ISSUE TITLE
CS Allies not included in peace deals

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1427]
I've noticed this for a few versions now, keep forgetting to open an issue. Pretty self explanatory...it's obviously a nuisance for humans (have to remember to manually make peace with everyone), and leads AIs to sometimes stay at war for centuries. It's not uncommon for a CS to be at "war" with several civs and city states later in the game.

I believe it was intended to make CS's removable from peace deals, but I strongly suggest they should at least be included by default.

**Comment by LoneGazebo** [comment]
@ilteroi removed this, not sure why. I'll get his input first.

**Comment by ilteroi** [comment]
well, that was a hack because back in the day we had a lot of impossible peace offers which you could not accept.

the reason was the city states included in the deal. because peace with them was blocked, since you are, at this point, still at war with their major ally.

so the easy way out was not to add "impossible" items to the deal. finding a way to resolve this chicken and egg problem would be better of course.

**Comment by LoneGazebo** [comment]
I think I can fix this.

**Comment by Edaka** [comment]
Something to keep in mind: IIRC, the amount of CS that were automatically included into a deal was factored into the assessment of the victor/loser. 'Make peace with CS X' was considered a quantum of price for peace in a deal between two majors, so the one who had to make peace with less CS would be considered to have paid a smaller price. That would sometimes cause false triggering of the Aztecs' UA and historic events as a result of otherwise white peace deals.

Uh, that reads horribly. I hope it makes sense.

**Comment by LoneGazebo** [comment]
Yeah, I'm aware of that. I just need to control the value a bit.
