### ISSUE TITLE
Air Sweep Hijinks

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1453]
@ilteroi, Seems that air sweep is being allowed multiple times a turn.

http://forums.civfanatics.com/showpost.php?p=14199218&postcount=97

**Comment by ilteroi** [comment]
there is definitely something wrong. or multiple things.

- CvUnit::canStartMission() is not called for air sweep when the menu is built. but it is called for air patrol (i.e. intercept). lua problem?

- multiple air sweeps per turn is possible because a fighter has 2 moves per turn (which is normally irrelevant because it's an air unit). but an air sweep costs one move, so a fighter can do two per turn *if* it doesn't have to fight (it can only fight once - but that's not even tested, see above).

- it seems that AI currently doesn't set its fighters to intercept. so air sweeps don't find a target. they are all used for other moves (ranged attrition). might be useful to skip some of them.

- if there's a non-air interceptor around, it works in principle, but there's no notifcation about the result except if the attacker dies.

- there is no damage to non-air interceptors, only to the attacker and air-based interceptors?

- anyhow, non-air interception always gives a damage of zero, because GC.getAIR_SWEEP_INTERCEPTION_DAMAGE_MOD() is zero?

- in general it seems AI didn't build any aircraft (in 12/3). had to create them via firetuner. but i know they used to do it. bad luck or a change in build sanity?

what can i say, lategame isn't tested very well ...

**Comment by LoneGazebo** [comment]
Yeah. Late game can get rough. 

They definitely build air units, though.

**Comment by LynnesCFC** [comment]
Just a short note: You can do 3 air sweeps per turn. Or 2 air sweeps and then rebase and so on.

**Comment by ilteroi** [comment]
which unit type did you use for testing?

**Comment by LynnesCFC** [comment]
Triplanes and fighters.
I was playing with Darius so I thought the 3 air sweeps would be because of a golden age, but when it was over I was still able to do 3 air sweeps per turn.

**Comment by ilteroi** [comment]
ok, fixed. some comments though:

it seems AIR_SWEEP_INTERCEPTION_DAMAGE_MOD was 75 in vanilla, but changed to 0 in the expansion packs. kind of makes sense because it's supposed to be a modifier, but they never adjusted the code accordingly. so now its 100+AIR_SWEEP_INTERCEPTION_DAMAGE_MOD as it should be, and the value is -50 (to compensate that ground based interceptors don't take damage - it doesn't affect air interceptions).

the fact that unsuccessful interceptions don't end the turn seems to be by design, it didn't change it for now, but it would be easy.

didn't touch the lua problem either. any takers?

**Comment by LoneGazebo** [comment]
What's the actual lua issue? Could be possible to just change that in the luaunit.cpp so that it is called in the DLL for the function.

**Comment by ilteroi** [comment]
the button for the air sweep mission doesn't seem to be hooked up to CvUnit::canAirSweep(). not such a big issue

anyway. pushed.

**Comment by LoneGazebo** [comment]
Cool. I'll merge this for tonight's beta. Just air sweep stuff?

**Comment by ilteroi** [comment]
yeah. and the heli attack.
