### ISSUE TITLE
Melee units stop when ordered to attack

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1520]
When you order a melee unit to attack an enemy 1 tile away, it will move next to the enemy and stop without attacking.

**Comment by LoneGazebo** [comment]
@ilteroi  might have an idea.

**Comment by Iamblichos** [comment]
Yeah but you can attack if you still have moves left, correct?

**Comment by ilteroi** [comment]
cannot reproduce. tried twice.

**Comment by Iamblichos** [comment]
If I understand him right, (and I noticed this a long time ago vs. vanilla): let's say you have a knight that can move 4 tiles and you order him to move and attack a unit 4 tiles away, he will move all the way up to the unit and stop, you have to issue the attack again. To me I think this solves some problems in regards to the resolve unit combat panel, because it can read wrongly if this involves attacking over a river, etc. In vanilla it will perform the attack 4 tiles away and carry out the order, but combat preview won't be accurate. I consider this a fix (if and only if I'm understanding him right).

**Comment by LoneGazebo** [comment]
i think having the unit stop is fine. Doesn't hurt anything, and guarantees it is what you want.

**Comment by qqqbbb** [comment]
I guess it's to prevent your units from attacking when you move them to unrevealed tile and there happens to be an enemy unit on it. But when you click on enemy that you can see your units should just attack them.

**Comment by LoneGazebo** [comment]
If it is a matter of convenience versus function, I lean towards the latter.

**Comment by qqqbbb** [comment]
I'm not saying it should be removed. I'm saying if you order your units to attack an enemy unit that you can see they should attack it. And if you move them to unrevealed tile and there happens to be an enemy unit on it, they should stop.

**Comment by Iamblichos** [comment]
Sorry, I don't think we're changing this see my notes above.

**Comment by LoneGazebo** [comment]
Yep.

**Comment by qqqbbb** [comment]
Why not make it optional? Most people want their units to do what they are ordered to do. And if I want to see correct combat prediction I can move my unit next to enemy unit.

**Comment by LoneGazebo** [comment]
That's just not how the pathfinder works, sorry.
