### ISSUE TITLE
Pathfinder/Movement quirk for feature promotions/traits

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1582]
@ilteroi, you have any ideas on this? Not sure if kasper noticed this before or after your refactoring of the movement system.

http://forums.civfanatics.com/showpost.php?p=14230195&postcount=213

**Comment by ilteroi** [comment]
well that's a difficult question.

looking at the code i think you never ever got road movement on forest. and the pedia states the trait ignores the terrain cost. nothing more.

but he's right that it's slightly inconsistent that for city connection purposes they would count as road, but not for movement.

so what to do? i can grant the movement bonus as well, but it's a boost to the iroquois. do they need it?

and what about songhai? they have the same issue with rivers. and it's even more complex because there are actually two traits at play (IsRiverMovementBonus and IsRiverTradeRoad), whereas for iroquois there is only one (IsWoodlandMovementBonus).

**Comment by LoneGazebo** [comment]
I think the movement bonus makes sense, truth be told. The Iroquois and Songhai aren't exactly top-tier, and consistency is king.

G

**Comment by ilteroi** [comment]
it shall be done

**Comment by ilteroi** [comment]
pushed. also fixed some other pathfinding quirks

**Comment by LoneGazebo** [comment]
Awesome!
