### ISSUE TITLE
Warmonger penalty - tooltip error?

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#169]
I was told there would be a MINOR penalty before I took a city, but the tooltip said the penalty was MAJOR once I took it. No idea if there's a problem with calculations or if it's a tooltip problem.

![2015-03-24_00002](https://cloud.githubusercontent.com/assets/11132095/6815395/3146498e-d257-11e4-8717-3b1fef7690ba.jpg)
![2015-03-24_00003](https://cloud.githubusercontent.com/assets/11132095/6815396/3147c9d0-d257-11e4-8a21-c81686573d3d.jpg)

**Comment by LoneGazebo** [comment]
This should be fixed in latest version – there were some issues with warmonger.

Also, because of how the game calculates warmonger values, a single point drop can cause the penalty to change from 'major' to 'minor (out of hundreds of warmonger points). I wouldn't stress too much (if there is interest, I can add the actual warmonger # value to the popup).
G

**Comment by joosegoose** [comment]
If it's as simple as displaying a number that the game is already
calculating, I'd be very interested in seeing it.

**Comment by LoneGazebo** [comment]
I'll close this for now, but in a later version I'll do the lua for this.
G
