### ISSUE TITLE
Game crushes on pressing "Next turn"

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1721]
1. Mod Version (4/23b) with DLL hotfix

2. Full CBP

3. Game CTD's on proceeding to next turn

4. Steps to reproduce: savegame attached

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/247374/QuickSave.zip)

**Comment by saamohod** [comment]
seems like a difficult issue.

**Comment by ilteroi** [comment]
thank you for bringing this to my attention.

unfortunately i cannot load the savegame. apparently it's incompatible. you are sure about the version?

because interestingly, the same crash-on-load issue has occurred to me with another savegame, so it looks like the problem might be on my end, but i don't know what it could be.
