### ISSUE TITLE
Ignoring diplomatic notifications on multiplayer

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1745]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

4/23b modpack with hotfix. Multiplayer game

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

You can ignore diplomatic notifications on multiplayer games by not opening them, which can lead to certain exploits. You can basically see what the notification says before opening it, as a short text regarding it appears while you hover the mouse on the notification. A friend of mine saw that some AI wanted to complain about him settling too close. He didn't open the notification and therefore didn't receive a diplomatic penalty for ignoring them nor did he need to avoid settling near them for the next 50 turns.

4. Steps to reproduce:

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by Mikkles** [comment]
This is tangentially related to my bug report #1744 
In my bug, when two diplomatic notifications happen at the same time (either bundled, or unbundled by turning off bundling line 197 NOTIFICATION_PLAYER_DEAL_RECEIVED of NotificationPanel.lua), by completing one, the other disappears and is ignored.

I'm mentioning this here as it seems both bugs are due to putting these AI diplomacy requests in the player's notifications, effectively triggering them on the player's turn instead of during the AI's turn.

**Comment by J-d-H** [comment]
I already thought that ignoring those complains could lead to problems. 
I'm just not sure atm what's the best way to solve this.

**Comment by LynnesCFC** [comment]
Maybe ignoring a deal can always automatically lead to the negative/ refusing answer?

**Comment by LoneGazebo** [comment]
@J-d-H , you could make those notifications block the end of the turn (like with production or research choices).

**Comment by J-d-H** [comment]
@LynnesCFC , it is not clear to me, what that answer would be at this point. I cannot just cancel a deal, because there is no deal in those cases.
For various reasons I haven't looked deeper in those cases because in the long run, I wanted to rewrite the whole diplomacy system anyway.

@LoneGazebo , yes. That would be an easy way, if there is no turn timer.

**Comment by LynnesCFC** [comment]
Sounds good! Do you still want to rewrite it, or have you put this plan on ice?
