### ISSUE TITLE
resource counting

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1751]
i got this notification:

![image](https://cloud.githubusercontent.com/assets/1358966/15093184/043c642a-1480-11e6-92d6-8c95ae457604.png)

which was strange because i knew that the dutch had a 100% monopoly on olives. checking the monopoly overview, poland indeed had a 66% monopoly and it said:

netherlands: olives 3 of 3
poland: olives 2 of 3

checking the map, i found only 2 olive resources. now if the dutch have the east india company it works out, but where do the polish olives come from?

**Comment by LoneGazebo** [comment]
Was there one under a city?

**Comment by ilteroi** [comment]
none that i could find. and it was a small map.

**Comment by Jotaro31400** [comment]
Great Amiral maybe ?

**Comment by ilteroi** [comment]
hmm. might be the case.

but why is it not 5 olives in total then?

also, since the olive monopoly is tile based, it is kind of pointless if you don't have any actual tiles

**Comment by GrantSP** [comment]
That's a good point. Since we can now get resources from other sources than just the tiles:
Great Admiral expeditions, meteors being broken open for Iron etc.
The actual number of resources at play in the game does not always match the number of resource tiles used to create these monopolies and may lead to other inconsistencies.

**Comment by LoneGazebo** [comment]
Since it isn't technically a bug, I'm closing.
