### ISSUE TITLE
production tooltip is confusing

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1770]
![image](https://cloud.githubusercontent.com/assets/1358966/15199152/5f06acee-17dc-11e6-9ad6-31cb5cb5b6ca.png)

i was actually looking for the railroad bonus. it's missing ...

but anyway, the numbers don't seem to add up.

36 base, 48.9 total -> 36% bonus but it says 20%?

and below the tooltip it say 75.15!

anyone can shed light on this?

**Comment by LoneGazebo** [comment]
in the CBP the railroad bonus is tied to the train station, not the railroad itself. Not sure about other inconsistency.

**Comment by pandasnail** [comment]
If you add up the numbers you get 40.75 for base which times 1.2 for the building modifier is the 48.9. The from pop bit just isn't adding in the number the UI shows. Now I have no zero idea where 75 comes from

**Comment by ilteroi** [comment]
good to know about the train station, i must have missed that part. luckily i wasn't in the hair pulling stage yet.

as for the the 75, could it be that it was overflow? would that be shown in the tooltip?

**Comment by Edaka** [comment]
Just tested, the overflow isn't shown in the tooltip like that. It's added directly to the production progress (i.e., where it shows 42.7/401 in Ilteroi's screenshot).

Has anybody been able to reproduce that ever since? I, for one, don't look at the production tooltip in such detail often (read: at all). We need to keep a close eye on that.
