### ISSUE TITLE
Victory Screen bugged

### ISSUE THREAD

**Issue by Kerbolosh** [LoneGazebo/Community-Patch-DLL#1778]
1. Mod Version (i.e Date - (4/23b)):
1.3.9 (latest stable)

2. Mod List (if using standard CPP set, leave blank):
None

3. Type of error (i.e. crash, interface bug, AI quirk): 
The Victory summary at the end does not show any info on how the game progressed.

4. Steps to reproduce:
Win the game

5. Additional information:
Screenshots:

![20160514145946_1](https://cloud.githubusercontent.com/assets/18732599/15268702/f097d860-19e7-11e6-8cb9-173373b4a7a0.jpg)
![20160514145954_1](https://cloud.githubusercontent.com/assets/18732599/15268701/f0963bfe-19e7-11e6-8e6b-000b58d67fd1.jpg)

**Comment by mwhiter** [comment]
post your lua.log :)

**Comment by Kerbolosh** [comment]
I had to activate logging first and replayed the last 2 turns, because I didnt save. Here is the lua.log

[Lua.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/264584/Lua.txt)

**Comment by mwhiter** [comment]
Your have two errors, which I think are related to each other.

1. The line
``` if(message.Player > -1) then ```
failed to execute, because message.Player was nil instead of a number. This means there is a high chance of a bad message being sent to UI.GetReplayInfo() - I cannot determine the cause of this from the .lua file. This may or may not be related to the Events system. I believe I can safely defer this to @LoneGazebo 

2. That above line failing causes all other initialization to fail, so the function 'SetCurrentTurn' fails, resulting in a bunch of failed calls to that method, since every tab in the replayviewer seems to call it.

**Comment by LoneGazebo** [comment]
The event system doesn't send anything to the replay info.

**Comment by mwhiter** [comment]
*shrugs* it was a guess. Yeah I have no idea why that is happening

**Comment by LoneGazebo** [comment]
This might be a mod conflict. Mod list?

**Comment by Kerbolosh** [comment]
No other mods. I installed with the Installer and selected CPP CBP C4D CSD and luxuries. Everything without EUI.
I attach my savegame right before I win.

Thanks for the help attempts.

[Augustus Caesar_0373 AD-1953.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/267450/Augustus.Caesar_0373.AD-1953.zip)

**Comment by Edaka** [comment]
Would any particular logs be useful here? I've also been having this issue for a long time now. If needed, I can provide some logs.

**Comment by Edaka** [comment]
Funny thing - tried to reproduce by killing myself (my in-game civ, that is) on turn 2 or so and the replay was fine.
