### ISSUE TITLE
EventDuration and Expire

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1780]
I'm converting a few E&D Decisions into dummy events so that it's less buggy for the user to do, but I have a few questions.

Does EventBuildingClassGlobal consistently apply the event buildings to newly-settled cities?

If the expire is set to false, but the event duration is still 30. Do the effects still consistently apply such as EventBuildingClassGlobal or EventPromotion or EventChoice_CityYields after the duration has passed up? Could I circumvent this by setting the duration to 1000 or something?

CapitalEffectOnly and EventBuildingClassGlobal on an EventChoice makes sure only the capital receives the building correct?

If I have an event that grants a free stadium in the capital from CapitalEffectOnly and EventBuildingClassGlobal let's say, if that capital got captured but the event's duration had not passed yet would I still have the free stadium in the new capital? Then what happens if the old capital gets recaptured, does the free stadium in the new capital disappear in which the free stadium in the old capital reappears?

**Comment by LoneGazebo** [comment]
EventBuildingClassGlobal only applies to current cities. It is not sustained. If expire is set to false, duration doesn't do anything - the buildings will persist. You could set the duration quite high, but I'd just keep expiration off if you want a permanent effect.

CapitalEffectOnly and EventBuildingClassGlobal would make it only apply to the capital, yes. Otherwise, you can use the cityevent.

Free buildings are destroyed on capture, and would not reappear. Event buildings don't have a sustained presence in the DLL beyond the creation/duration/deletion cycle (this is to save on memory space).

**Comment by Edaka** [comment]
Seems like there are no more open questions here,closing.
