### ISSUE TITLE
Caravans not getting pillaged.

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1800]
Mod Version (i.e Date - (4/23b)):
5/14, full CPP, nothing else.

Type of error (i.e. crash, interface bug, AI quirk):

An enemy caravan didn't get pillaged as it walked over my military unit. It started the turn on a tile next to my unit and walked through the tile where my unit was standing. I could pillage it manually and this happened on ancient/classical era, so the enemy couldn't have a corporation that prevents trade units getting pillaged.

**Comment by LoneGazebo** [comment]
@ilteroi, change to trade unit logic caused this?

**Comment by ilteroi** [comment]
need to check. depends on the unit also - some have the ability, some don't. note it's not the same as pillaging: canPlunderTradeRoute() vs canPillage()

**Comment by F0rst1** [comment]
> depends on the unit also - some have the ability, some don't. note it's not the same as pillaging: canPlunderTradeRoute() vs canPillage()

Well that explains it. 800 hours of CIV, most of it with CPP and I always thought that any unit could plunder trade routes. It was a melee unit, either brute or warrior and they don't have the promotion so the issue never existed. Sorry for the inconvenience.

**Comment by Edaka** [comment]
Wait, so the conclusion is that some military units like brutes and warriors can't plunder trade routes by design? That doesn't sit right with me. If I'm not mistaken, they used to be able to plunder trade routes in the past - every military unit could, even scouts.

But anyway, I haven't seen that  issue myself, although I haven't look. Is this still happening? I guess I'll check up on it myself later on.
