### ISSUE TITLE
"Your Culture" menu empty (can't move great works around)

### ISSUE THREAD

**Issue by hyogodan** [LoneGazebo/Community-Patch-DLL#1804]
When viewing the "Your culture" Tab of the Culture overview (leftmost tab), it is empty (no cities/great works/etc. shown) So great works can't be moved around for theming bonuses.

Could be interference from a different mod? I turned IGE off, but could info addicts be affecting it?

**Comment by GrantSP** [comment]
Definitely a mod conflict happening here, using just "Vox Populi" installed mods has no issue.

**Comment by hyogodan** [comment]
Aside from CP and CBP, I have some Civs added as mods. Other than that it's
only IGE (turned off and error still occured), Yet Not Another Earth Map (I
followed the directions for installing CP/CBP to work with it and it has
been fine so far) and Info Addicts.
Any idea on which would be the source of the trouble? (at work now, so I
can't check, but wanted to know maybe where to start when I get a chance)

**Comment by GrantSP** [comment]
Can't imagine it is any of the mapscripts, possibly one of the new civs adds some UI files that conflict with this but my guess would be IGE. You should try a game with just "Vox Populi" installed to see.
You might also check the logs for any error messages or other indicators to an error.

**Comment by hyogodan** [comment]
Could you tell me where to check to see the logs? KInd of new to this. I'll
try with disabling and let you know if I can find the source.

**Comment by GrantSP** [comment]
Civ V installation folder in the sub-folder called "logs".

**Comment by hyogodan** [comment]
Thank you.

**Comment by LoneGazebo** [comment]
This is a mod conflict, probably with a civ that modifies the culture overview tab.

**Comment by hyogodan** [comment]
OK, I'll start there, cheers!

**Comment by Edaka** [comment]
@hyogodan so, any success?

**Comment by hyogodan** [comment]
Nothing yet, though I don't know well how to read the logs, so I am not so
sure what I am looking for. I am (when I have time to play) trying to turn
off individual added civs. When I can pinpoint the source I'll let you
know. Cheers.

**Comment by Bloodrocution** [comment]
I have encountered this same issue, but I am not using any mods that add Civs to the game, so that can be ruled out as the (single) cause. I am, however, using the Ingame Editor. 

@hyogodan Did you have any success by running a game with the IGE disabled? I will have to try that, but to be honest, I find the IGE to be indispensable when playing Civ. It will be most unfortunate if that happens to be the source of the issue :( .

I checked my log filed as suggested, and I didn't see any errors, but like hyogodan, I don't know exactly what I am looking for. I can post the log files here as attachments if that will help.

**Comment by Bloodrocution** [comment]
**UPDATE** 
Disabling the IGE for my current game made no difference; the bug still persists:
 ![Culture Overview](http://puu.sh/ta8jh/1cc10ccd54.jpg)
![Active Mods](http://puu.sh/ta8ql/73e17079cf.jpg)

Next I will try uninstalling the IGE completely to see if that solves the issue.

**Comment by Bloodrocution** [comment]
**UPDATE**

I completely uninstalled the IGE, deleted the _cache_ and _ModUserData_ folders, loaded up the save and the bug still persists. I am now at a loss for what to do. I don't see how starting a new game would make a difference, since the IGE doesn't affect save game files, so it has to be something else (but what?) @LoneGazebo @GrantSP suggestions?

I did take another look at my log files and I may have possibly found something relevant within the Database.log file: 

_[458010.671] columns StrategicViewType, TileType are not unique
[458010.671] While executing - 'INSERT INTO ArtDefine_StrategicView(StrategicViewType, TileType, Asset) VALUES(?,?,?)'
[458034.531] no such table: ContentPackage.LocalizedText
[458034.531] no such table: ContentPackage.LocalizedText
[458034.531] no such table: ContentPackage.LocalizedText
[458035.968] no such table: ContentPackage.LocalizedText
[458039.171] columns StrategicViewType, TileType are not unique
[458039.171] While executing - 'INSERT INTO ArtDefine_StrategicView(StrategicViewType, TileType, Asset) VALUES(?,?,?)'
[458040.531] no such table: ContentPackage.LocalizedText
[458040.531] no such table: ContentPackage.LocalizedText
[458040.531] no such table: ContentPackage.LocalizedText
[458048.359]
-- SQLite Memory Statistics --_ 

"StrategicView" and "ArtDefine"? Pertinent to the issue? I have no clue, but it sounds like it could be related. I have no clue how to interpret the meaning of any of this though. 😕

**Comment by LoneGazebo** [comment]
No worries!
