### ISSUE TITLE
Submarines firing across land

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1828]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

1. Mod List (if using standard CPP set, leave blank):

+ FlagPromotions v7

2. Type of error (i.e. crash, interface bug, AI quirk): 
Quirk: submarines can fire across a 1 tile peninsula because they have a range of 2.
Suggest the range should be reduced.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Same body of water? If so, that's unavoidable, sorry.

**Comment by ilteroi** [comment]
not unavoidable if the range is reduced to one ...

**Comment by GrantSP** [comment]
Yes, same body of water, though that shouldn't be the issue, regardless of whether the units are in the same sea, submarines should not be able to fire across land.

As @ilteroi and I suggest, simply reduce the range to one.

**Comment by LoneGazebo** [comment]
Range 1 on subs is not viable. Takes away their utility. Lots of units can fire across targets like that.

**Comment by GrantSP** [comment]
Submarines are invisible to units and fire torpedoes. Other units that fire 2 range are always visible and are firing either missiles or artillery shells, which means you can see them coming and prepare. Subs, by their very nature are stealthy hit and run units, long range bombardment!

This is an issue because knowing there are subs about you will often find safe harbour behind a peninsula or other landmass between where you last saw them and where you think it is safe. For the sub to just fire across land is wrong and infuriating gameplay.

Having a range of 1 will not reduce the subs utility if they retain their invisibility and movement.
Cruisers/battleships etc. have range of 2 and submarines are not a direct counter to these. Those units could historically shoot over very long distances whereas a sub's torpedo range was very limited.

**Comment by GrantSP** [comment]
I just checked in the vanilla game and although subs have a range of 2 there, the target selection and acquisition does not allow for units hidden behind land.
Perhaps the tweaking in the AI path-finding etc. has affected the targetting? Either that or the AI is using some other cheating mechanism. Damn AI, can't trust 'em.

**Comment by LoneGazebo** [comment]
@ilteroi should check the pathfinder, but the problem with subs at range 1 is that it takes away their stealth when adjacent to an enemy. They're already quite weak on the defense.

**Comment by ilteroi** [comment]
good point about stealth, so maybe not a good idea

targeting is independent from the pathfinder. the only check is whether the target is in the same area. we only added the ability to attack cities if they border that same water area.

**Comment by Vyyt02** [comment]
Probably better to discuss the sub range at the CivFanatics forums, but I will share my opinion on this subject here. I have always been reducing the sub range to 1. I believe the sub should be hidden only until it fires the torpedoes. If it does not destroy the target and ends its turn next to an enemy ship, its position is given away and the escorts should hunt it down. It is:

1) Realistic: When the Allies started using the convoys in WWII, the German subs became the prey once they gave away their position by firing their torpedoes
2) It is fun: It forces the player to use subs in wolfpacks and in combination with other units to make sure no sub ends its turn next to a surviving enemy ship. I consider subs to be glass canons, don't you? I think they should be hit-and-disappear
3) It is AI friendly: Correct me if I am wrong, but I believe that now if you attack with a 2-range sub, the AI is unable to deduce where the torpedoes came from and will not try to find and destroy your sub. With a 1-range sub, there is always risk that you will not sink your target and AI can retaliate. If I remember correctly, Communitas went even so far that they made subs ALWAYS visible, because they believed the invisible subs were too OP

**Comment by ilteroi** [comment]
if range is reduced, it could get the move after attack promotion to make up for it. AI should know how to handle that. but i don't have strong feelings either way.
