### ISSUE TITLE
Late game unit purchase

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1855]
Bug Report Template

Mod Version (i.e Date - (4/23b)):5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Rocket Artillery, X-Com Squad, Modern Armour, GDR, Jet Fighter, Stealth Bomber, Helicopter all require the military base to be purchased. It should be the military academy.
And as already reported, mech. inf. requires airport.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Intentional.

**Comment by Der-Zorn-Gottes** [comment]
Sorry to be insistant here, but that makes no sense.
For all earlier units, either barracks or armory are required to purchase. The military academy is the third buiding of that line, and therefore the logical candidate.

The military base, which is currently required, is the third building in the walls/castle line. It's predecessors have nothing to do with unit purchasing, and neither should it.

**Comment by Edaka** [comment]
I believe the military base goes largely as a continuation of mounted unit line, which at some point uses stable as a requirement for buying knights, for example. Military base gives bonus towards air and mech unit production, so that's another reason for it to grant ability to buy them. The military academy, on the other hand, is required to buy infantry units anyway, isn't it (aside from X-COM)? So what we have right now is a differentiation between mechanical/non mechanical units, which require their own buildings. If anything, think it actually diversifies the game.

**Comment by Der-Zorn-Gottes** [comment]
Hm, I can see your point, but I still disagree with this design choice.
It is both confusing and irritating to suddenly require a completely different building line for end game units.
I could see an additional requirement for the GDR and maybe X-Coms, but Modern Armour, Rocket Artillery and Jet Fighters should follow the same rules as their direct precedessors.

**Comment by Edaka** [comment]
Yeah, I think I can see your point as well. But as a balance concern, it should be brought up on the forum.
