### ISSUE TITLE
Units with goto-orders can stack

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1939]
Bug Report Template

Mod Version (i.e Date - (4/23b)):5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

If you give a goto-order to a unit, it can end it's movement on a tile already occupied by another unit.
![20160608174122_1](https://cloud.githubusercontent.com/assets/16065630/15907570/02ec8f58-2dbe-11e6-8a56-bd47a16994bf.jpg)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
seems to similar to #1866

**Comment by ilteroi** [comment]
should be fixed

**Comment by ilteroi** [comment]
hmm. just a heads-up, the fix works but it has side effects ... don't get too excited yet.

**Comment by LoneGazebo** [comment]
@ilteroi that's cool, just let me know. In other news, have you been editing the trade route logic at all? At some point in every game that I've observed (thus far) the AI decides to only send internal trade routes.

**Comment by ilteroi** [comment]
yes i did, a while back. the previous trade route target selection logic was broken. if they stop making international traderoutes, it's because their value is not high enough to the AI. i didn't touch the valuation logic - it's quite sensitive, so simply upping the gold value might make domestic routes too unattractive. i guess it needs to be more situation dependent (current yields, flavors etc).

**Comment by LoneGazebo** [comment]
I'll investigate.

**Comment by ilteroi** [comment]
ok, got another fix for this. it's quite tricky, the new pathfinder is smart enough to _not_ spend all movement points in a turn if it's better that way. but then the mission AI code just goes ahead and starts executing the moves for next turn because there are movement points left. 

didn't want to force finishing the turn because that's not nice for human players. it seems to be impossible to pause the mission without cancelling it. so now the unit wakes up and needs new orders.
