### ISSUE TITLE
resilience and/or Celt's UA leads to inquisitors not doing anything

### ISSUE THREAD

**Issue by crdvis16** [LoneGazebo/Community-Patch-DLL#1953]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
**5/21/2016**

1. Mod List (if using standard CPP set, leave blank):
**CBP full with EUI**

2. Type of error (i.e. crash, interface bug, AI quirk): 
**bug**

3. Steps to reproduce:
**try to use an inquisitor from your own religion on a city you have puppeted/annexed with a foreign majority religion which has the 'resilience' belief.  In my case it was a Celtish city with the Celt's religion as majority, so perhaps their UA is also playing a part in this?  The inquisitor did not reduce their number of followers at all (originally had 15 followers and still had 15 followers afterward).  I have not attempted to use either a prophet or missionary yet.**

4. Additional information:

**Comment by crdvis16** [comment]
To spell it out more clearly:

I have my own religion (Tengriism).  The Celts have Catholicism and chose "resilience" as a belief.  I have conquered a few of the Celt's cities.  I then tried to use an inquisitor which was purchased from my capital (my capital does have my religion as majority) on the puppeted Celtic cities.  The number of Celtic Catholic followers did not change from the use of the inquisitor.  There were 15 followers before its use and still 15 followers afterward (I expected the followers to go down to 7 or 8 due to their resilience belief).

**Comment by LoneGazebo** [comment]
@ilteroi, would you mind taking a look at this?

**Comment by LoneGazebo** [comment]
@ilteroi I looked, and did not see anything wrong the code.

**Comment by ilteroi** [comment]
it's complicated ...

inquisitors really only work well when you have meaningful religious pressure in the city.

now if you you don't, the resilience belief makes it so that there aren't any meaningful changes, because the old religion still has the highest pressure. so that's not really a bug. it should be possible to combine inquisitors with missionaries for better effect.

i've got another idea though, we could try and change RecomputeFollowers() so that it does not compute pressurePerFollower from the reduced total pressure but from the previous full pressure value. but it's used in a lot of places, so it needs careful checking.

**Comment by LoneGazebo** [comment]
I wonder if we could buff their 'religious strength' a bit more?

**Comment by LoneGazebo** [comment]
Rather than reinventing the functions, just adjust the power of the inquis,  I mean.

**Comment by ilteroi** [comment]
well the inquisitor doesn't add any religious pressure. it just removes others. if it did, it would be a great prophet. so backing it up with a missionary seems to be a good strategy.
