### ISSUE TITLE
Various unit movement issues

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2043]
1. "Do you want to attack?" window pops up when another non-hostile unit appear (either by revealing the fog or its own movement) on the pre-defined path. The thing is it won't give me control of my "trespassing" unit if I decline, and the game considers this unit as completed its movement (when it's not) and ends the turn regardless.
How it worked in previous versions: in case of any obstructions the unit get "awoken" before doing the movement for the player to path another way, without any additional window shenanigans and no skipped turns either.
2. Can't move on top of non-hostile civilian units even with "move to" command and declining the window from the previous case.
3. Again, non-hostile units and unit stacking when switching positions:
![8930_20160626151509_1](https://cloud.githubusercontent.com/assets/1131228/16361723/481463dc-3bb3-11e6-8825-bee92659ee8d.png)
The archer was standing on the tile with the portugal worker, I ordered him to switch position with the pictish warrior and this is the result.

v. 6/25-1

**Comment by LoneGazebo** [comment]
@ilteroi, the fun never ends. :)

**Comment by ilteroi** [comment]
i fixed the non-focused unit after the popup. 

but i don't have a clue right now why stacking with enemy civilians doesn't work anymore. although honestly i could regard that as a feature.

i could also possibly make it so that the popup doesn't appear when moving into a non-hostile civilian. but the code (GetDeclareWarMove) is rather involved, and i don't want to break something else. i should never have touched the whole thing ;)

**Comment by pandasnail** [comment]
I had a Scout on a long go to mission use three movement points on one turn and then had one movement point left for the next turn. (regular 2 move scout moving thru nontrailblazer territory, i really do mean 3 movement points not merely 3 tiles)

**Comment by LoneGazebo** [comment]
@ilteroi I think it is worth solving. I wrote that code in the declare war move some time ago, but I'm not sure what was changed that broke it.

**Comment by ilteroi** [comment]
just pushed some fixes ... hope that helps.

**Comment by LoneGazebo** [comment]
Cool, thanks. I'll add it in and see how it goes. :) Nest of vipers, eh?

**Comment by LoneGazebo** [comment]
@ilteroi, a report from Funak: If use a mouse drag movement and create a movement destination outside of a units range, my military units are able to stack with anything that's currently on the tile of their last movement. This also seems to be true concerning auto-exploring units (I've had scouts go into my cities and kicking out my garrison on the next turn because they are stacked).

**Comment by LoneGazebo** [comment]
@ilteroi, where are we on this? http://forums.civfanatics.com/showpost.php?p=14335206&postcount=1

**Comment by ilteroi** [comment]
that should be fixed. but there are other small pathfinding bugs. hope to get a look tomorrow night

**Comment by LoneGazebo** [comment]
Sounds good!

**Comment by ilteroi** [comment]
fixed and pushed
