### ISSUE TITLE
no notification after moving onto ruins

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2076]
sometimes i find ruins but there is no notification about the result ... don't know if i didn't get anything or if it's just not shown.

**Comment by LoneGazebo** [comment]
Getting a lua error?

**Comment by Edaka** [comment]
I think there was an checkbox in the in-game options that disabled pop-ups - perhaps you have that on?

**Comment by ilteroi** [comment]
na. normally i get the notification. but not always.

**Comment by ilteroi** [comment]
problem is, it doesn't seem to be reproducable. i tried loading an autosave, afterwards i got the notification.

**Comment by LoneGazebo** [comment]
Odd. Nope, never seen.

**Comment by 8h42** [comment]
I have noticed this issue since the version 5/14.
When I use the "No Reward Popups" option, the **production boost** message doesn't appear.
Shoshone Pathfinders should help you to reproduce this issue.

Active Mods
(1) CP 6/28
(2) CBO 6/28
(3) IGE

![ruin](https://cloud.githubusercontent.com/assets/11933188/16518777/ae0c9b72-3fbf-11e6-88a2-eff0f6d41003.png)

**Comment by LoneGazebo** [comment]
@8h42  that's intentional - none of them show if you have popups disabled (faith, etc.).

**Comment by 8h42** [comment]
@LoneGazebo
Even if you disable popups, you can see boost messages including Gold, Culture, Faith and so on.
Now, only the Production boost message doesn't appear.
![ruin2](https://cloud.githubusercontent.com/assets/11933188/16601938/2bf63618-434b-11e6-8efa-8ccc321557e1.png)
