### ISSUE TITLE
Can't active "CBP - Compatibility files". Says Mod is missing required dependencies

### ISSUE THREAD

**Issue by marcelofbaca** [LoneGazebo/Community-Patch-DLL#2132]
Bug Report Template

Mod Version (Vox Populi 7-7 ):

1. Mod List (if using standard CPP set, leave blank):
Using only the MODs installed with the Vox Populi.exe file. 

2. Type of error (i.e. crash, interface bug, AI quirk): 
I can't select "6a CBP - Compatibility files" at MODS menu. The game says it's missing required dependencies but i've already selected all the others 5 files. I installed the MODS using Vox Populi automatic install (selected Vox Populi (including EUI)). I have the same issue when using any other older version of the MOD, except Community Patch 3-9. I executed the program using "execute as administrator"

3. Steps to reproduce:
Install Vox Populi using 7-7 version and then select all the MODs in numeric order at MOD menu.

4. Additional information:

---------------------------
Supporting information:

Screenshot: http://imgur.com/2zahNLK

**Comment by GrantSP** [comment]
It looks like the installer has not completely removed the previous versions of some of the modules.
You have the versions as this:
(2) CBO - version 3-8 -- it should also be 7-7
(6a)  EUI compatibility files 3-8 -- should be 7-7

Completely remove everything in your 
**\Documents\My Games\Sid Meier's Civilization 5\MODS\** folder and then re-run the installer.

I think it may be because the installer is looking for differently named folders. Since the project changed to Vox Populi those folders once called _Community Balance **Patch**_ are now called _Community Balance **Overhaul**_.

@LoneGazebo you may want to check the setup script.

**Comment by LoneGazebo** [comment]
Setup script does not account for betas (it can't), but it does grab mod files of the same type and deletes them. Nothing I can do about this, but instructions note to check mods folder for invalid mods after install.

**Comment by marcelofbaca** [comment]
It worked!
Thank you guys!! The MOD is great and really refreshed my experience with Civ V.
