### ISSUE TITLE
Paralyzed CS

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2155]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7-7 full CBP

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk):

 A City-State was pillaged by a barbarian invasion centuries ago. Apparently, until now it hasn't built a single worker to repair their tiles nor hasn't built any units at all for 100-200 turns AFAIK. 

[Paralyzed CS.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/359362/Paralyzed.CS.zip)
![20160712160644_1](https://cloud.githubusercontent.com/assets/16341598/16768041/2a62afa2-484b-11e6-8ba7-eea77df554f9.jpg)

**Comment by cdanger341** [comment]
Just chiming in to report that I too have experienced this behavior. There was a CS sacked and taken over due to the Barbarian Horde CS quest. Another Civ liberated the CS, but afterwards the CS built no units (Workers or Military) for the rest of the game. This could have been happening to other CSs that were sacked by barbarians and then liberated, but this was the only CS I was close enough to observe.
