### ISSUE TITLE
unit's path miscalculation

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2184]
Mod Version (i.e Date - (4/23b)): 7-15 full with EUI

 1. Mod List (if using standard CPP set, leave blank):

FlagPromotions(v.7)

 2. Type of error (i.e. crash, interface bug, AI quirk): 

The amount of turns it takes to take a unit to a certain spot is bugged.

 3. Steps to reproduce:

In my savegame a hoplite unit would take one turn to get to cow tile (pic. 1). But when I stretch the path further is says the unit would only reach truffle tile (pic. 2). When I release the order the unit would reach the truffle tile and stop, but it will still have the movement points to get to the cow, also the initial path would change (pic. 3)

Savegame:
[1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/367768/1.zip)

![20160717124818_1](https://cloud.githubusercontent.com/assets/16341598/16899943/67b5b252-4c1d-11e6-980c-2a4e18f26e8b.jpg)
![20160717124819_1](https://cloud.githubusercontent.com/assets/16341598/16899944/68e5d95e-4c1d-11e6-9d77-27f624ef275f.jpg)
![20160717125749_1](https://cloud.githubusercontent.com/assets/16341598/16899981/37fb77b2-4c1e-11e6-9b43-dbb7d479ffe4.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi see also the thread on units getting picked up by the AI.

**Comment by ilteroi** [comment]
which thread is that?

**Comment by saamohod** [comment]
Sorry for not reporting it into github. 
 Here it is http://forums.civfanatics.com/showthread.php?p=14358391#post14358391

**Comment by ilteroi** [comment]
regarding the pathfinder issue - it's not a bug, it's a feature. the pathfinder is actually quite smart and tries to end the turn in the jungle for the defensive bonus. even if you force the unit to spend the last movement points, it still tries to stay in a good defensive position.

i've already deactivated part of the smartness in order not to confuse people. it's a shame actually, but maybe i'll do that here too.

**Comment by ilteroi** [comment]
regarding the other issue with the AI interference with missions, do you have a savegame there too?

**Comment by saamohod** [comment]
@ilteroi  Sadly no savegame right at the moment of weird behaviour.
 Regarding what you've said before. Please have a look at screenshot 1 and screenshot 2 I provided. You should see what problem I'm trying to point out. When I order the unit to go to the "cow" tile it shows it'd reach the tile in **one turn**. But when I stretch the path one tile further into the forest then it shows me that the unit will only reach the "truffle" tile; and in order to get to the "cow" it'd require **two turns** (which is not true). That's where the inconsistency and confusion is.

**Comment by ilteroi** [comment]
as i said. the unit perfers to end its turn on the truffle instead of the the cow. 

now if you are ordering it to move to the cow, it will do so. but what you're really trying to do is to move to the forest southwest of the cow, right? that's two turns, no matter how you slice it.

anyway it's no longer done for human players.

**Comment by saamohod** [comment]
Seems we're both talking about different things. Must be because of my bad English.
 I'm gonna make a third attempt and explain this bug as simple as possible. Sorry for being a nuisance.
 1. There are pic.1 and pic.2.
 2. There are both from the same game, same turn.
 3. They "claim" two different things: 
 4. Pic. 1 claims the unit will reach the "cow".
 5. Pic. 2 claims the unit will reach the "truffle" and **stop because no more movement points left** (the path's figure "one" on the truffle tile tells us that's the farthest the unit can walk, isn't it?)
 6. If we run the test and let the unit walk according to pic.2, we see that the previous claim is not true. The unit **does stop** on the truffle tile, **but** it **still has** movement point to spend.

 Therefore two questions: Why did the unit stop at truffle if he can still move? Why did the path "claim" the truffle is the farthest the unit can go when in fact it can go even further?

 Once again sorry for the trouble, but in my view the bug is too obvious to ignore. And it pisses me off big time because it gives wrong information on how far a unit can walk, and it keeps taking me back to the same unit after it moved all the way it was ordered but then stopped and still had movement points to spend.

**Comment by ilteroi** [comment]
don't worry, not a language problem, just a regular misunderstanding :)

the blue line indicates the movement range of the unit. the number in the circle simply indicates where the unit will end the turn. the blue line includes the cow. everything is good, no contradiction.

now, in a multi-turn mission, a unit is not required to spend all movement points each turn. sometimes that happens because it's impossible (a blocking unit is in the way), sometimes it happens because it's just better to stop on a tile with high defensive bonus (in case it will be attacked) or sometimes it happens because you want to stay out of enemy territory (no attrition for missionary).

since moving into the forest tile consumes all the movement points of the unit, it doesn't really matter if it takes a small detour to get there.

**Comment by saamohod** [comment]
Thanks for clarification, ilteroi. Now I understand.
 From my point of view, let me doubt the utility of such mechanics. In any game where I have more than 5 units (which is any game past Ancient Era) it is a source of constant pain and annoyance. When you give move orders to a dozen of units and at the end of turn some of them still report back to you because their move is interrupted **and for the life of me I can't remember where I sent this particular unit**
 I may be the only person who finds this mechanics clumsy, but most likely I'm not. 
 Just my five cents.

**Comment by ilteroi** [comment]
you're right - but deactivating the "smart pathfinding" won't solve the issue. because in any multi turn mission, it is possible that the path will be blocked, so a detour becomes necessary or the mission becomes impossible. so you will always have the situation where a unit wakes up and you don't know what it was supposed to do. solving this would need a huge UI redesign. on the other hand, if it's not obvious, maybe it wasn't so important ... let's consider it a memory exercise :)

**Comment by saamohod** [comment]
I see your point. You are the boss and the decision-maker ;)
But maybe it is possible to return this pathfinding back to vanilla mechanism? Which is logical and straighforward? When the numbers on path show exactly the amount of turns it would make to reach a certain point?
I understand your argument that quite often a unit's path will be blocked and the unit wakes up. It seems normal and inevitable. But... when a unit's path is **not** blocked and the unit stops in the middle of nowhere for **no obvious reason**, is a different story.
 I honestly don't see any advantages over vanilla pathfinding, that's my point.
 Sorry for the trouble.

**Comment by LoneGazebo** [comment]
@saamohod putting it bluntly, the new pathfinding system is so advanced and optimized compared to the old model that it is like comparing a Model T and a Ferrari. I'd trust @ilteroi on this one. :)
