### ISSUE TITLE
A Couple Things #2

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#2189]
From the July 7th version, all Standard, No-EUI

1.  The Submarine damage VS Cities (at least on the Nuclear Submarine) doesn't seem to reduce the damage by 75% as the indicator would seem to say in the attack panel - rather, my Nuclear Subs are consistently cracking out more than twice as much damage as my Battleships, and this isn't merely on the attack panel - the city really falls as quickly as things are suggesting.  If you take all the multipliers in the attack screen, they simply don't add up.

2.  Targetting on warships seems to give an additional bonus that reduces "domain" damage against other warships - is this intended?  It makes Targetting a rather strongly-biased pick, because defensively, it is insane.

3.  If an AI owns a City-State via conquest (the city belongs to the AI and is no longer a City-State), and you liberate it, the very AI that previously owned it is happy about it.  Clash of logic between conquering an AI city and liberating a City-State.

4.  Attacking a city sometimes displays the hit points of the unit inside the city rather than the city's hit points, and thus the damage dealt ends up being deceiving because both the city and the unit absorb damage, causing the total damage to not be what was displayed.

5.  The "Coastal Raider" promotion on Submarines suggests that Subs pillage gold when attacking cities, but this is not actually true.

6.  The B17 Bomber, as it is superior in every way over a Heavy Bomber and also cheaper, should logically exclude the production of Heavy Bombers and become the upgrade of the Bomber once you have acquired all the prerequisites for it.

**Comment by LoneGazebo** [comment]
1. There's nothing in the code to reflect that. Perhaps just the power of the unit?
2. Nothing in the code for that either. I'll look.
3. Normal. Unfortunately, since the UI is a little rigid, you can't see that while liberation makes the AI happy, you are also still getting warmonger with the person you conquered it from.
4. Don't understand.
5. No, they just get the city damage bonus.
6. Can't do that - code doesn't support it.

**Comment by LoneGazebo** [comment]
Fixed what was valid, thanks!

**Comment by Gidoza** [comment]
Okay, you'll have to let me know what you thought was valid and what wasn't.  :P   Will offer a reply to what you said.

1.  Well, my sub was powerful, but the tooltip clearly says "-75% power against cities," which would suggest a massive damage reduction.  Either the tooltip is wrong, or the damage is wrong, but I don't know which one.

4.  What I mean is that you can choose to put your cursor over a city with a unit in it - the tooltip will display the damage, with the flashing part in red - example, that the city will be reduced to zero hit points.  But then you attack the city, and it is not reduced to zero hit points at all.

5.  Is it possible to fix the tooltip, then?

6.  Ah, okay.

**Comment by LoneGazebo** [comment]
1. This was a lua issue – subs get a +75% to attack, but -75% to city attack. So it was cancelling out, leaving a bonus that made the function make sense. The 75% attack wasn't showing up in UI(vanilla error, actually).

2. Can't be avoided – the UI simply can't account for units like it should, as it is predictive of city combat. 

3. No, because only one function can be called (liberation v. warmonger).

**Comment by Gidoza** [comment]
OK, all good, then.  :)
