### ISSUE TITLE
Danish UA bug (?)

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2208]
Bug Report Template

Mod Version JULY 15

1. Mod List - as always, regular with a few changes I wanted to make in order to make the game more balanced. Sometimes strange religions mod to get more religion icons to choose from,

2. Type of error - lack of scaling.

3. Steps to reproduce:
Pick Epic gamespeed.
Attack a city with melee unit.
You get 100% of the city's health as money. The problem is that city health is equal on all speeds while the worth of gold is higher on shorter, lesser on longer speeds. Therefore you'll get 200 gold while taking down a non-upgraded city with no +HP on  all speeds - but that 200 gold is a lot on Quick, decent on Normal, meh on Epic and bad on Marathon.

(Portuguese UA scales (scaled? I didn't play them for more than a month) with Gamespeed in a similar way, but the problem is opposite - it's terrible on quick, bad on normal, decent or even goodish on Epic and good on Marathon - because the amount of stuff you  get per turn changes from N2 to Q1/E3/M4, the cost of everything is higher but there's also more turns, so your UA is pretty much superior on other speeds)

4. Additional information:
I'm way cooler than anyone else
I like colour purple

**Comment by LoneGazebo** [comment]
lol at purple.

Scaling of city size is just the way that plundering works. I don't see it as a problem.

Just FYI, Portugal's UA scales with Era.

**Comment by pandasnail** [comment]
I think I agree with Swag? I have for awhile wondered why pillaging and plundering don't scale with game speed, when most everything else does, on kill bonuses, barbarian camp clears, and so on. Now, I've never reported it or brought it up at all because I certainly do not need more Gold on Marathon (at least post-Currency). But as Swag says, it makes the Danish UA, the Landsky, and the Coastal Raider promo less desirable and effective. (I take CR anyway a lot for Supply over Pincer tho).  I mean, cities aren't bigger on Marathon, so city size scaling doesn't affect it.

**Comment by LoneGazebo** [comment]
Fixed for both.
