### ISSUE TITLE
Civ not expanding

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2278]
Mod Version (i.e Date - (4/23b)):8-2

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

 Playing a first game of the latest patch I've noticed that most of the civs expand "normally" except one. Morocco in 1775 has the whole continent to themselves and still has just the capital city founded, which seems totally wrong.

3. Steps to reproduce:

 Savegame attached.

![20160804225256_1](https://cloud.githubusercontent.com/assets/16341598/17416443/d5c1487e-5a96-11e6-9a12-aab7f68fe1ea.jpg)
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/402582/QuickSave.zip)

**Comment by NuttSo** [comment]
yep just noticed the same thing ,playing with 14 AI, immortal,Epic , I am on turn 116 and the korean settler has been stuck in the capital since turn 50 and the Babylonian one is just wondering around 
![20160806163304_1](https://cloud.githubusercontent.com/assets/20857721/17457075/0e5a3c86-5bf5-11e6-9282-1e988ac22673.jpg)
