### ISSUE TITLE
Able to adopt social policies before reaching their prerequisite eras

### ISSUE THREAD

**Issue by Gindisi** [LoneGazebo/Community-Patch-DLL#2391]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-12 and 8-9

1. Mod List (if using standard CPP set, leave blank):
Just the one CPP file by itself, no other Vox Populi components

2. Type of error (i.e. crash, interface bug, AI quirk): 
Gameplay Bug

3. Steps to reproduce:
Start game, gain enough culture to adopt a social policy, pick whichever one you want. Even though it's ancient era, you can choose any of the policy trees.

4. Additional information:

---------------------------
Supporting information:
[IssueReportSupportingInfo.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/428142/IssueReportSupportingInfo.zip)

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict.

**Comment by Edaka** [comment]
That's interesting. The lua.log attached indicates that the only active mod is Community Patch, nothing else. I myself have been experiencing the same problem since updating to 8/12 after a recent break, only VP pack + IGE activated. Although I thought it was due to my tinkering with various xml and sql files (policies, civ UAs, etc.).

**Comment by JFDaly** [comment]
Can confirm, with only CP + IGE active:

![Alt Text](http://imgur.com/Xu8vVHn)

**Comment by Iamblichos** [comment]
This happens in CP only because the CBO adds a table element for Number of policy prereqs. For some reason without that set the old method is not working. Haven't seen the DLL at the moment to see if there is a both/and requirement for era prereq and policy amount prereq. If that's returning false , that might explain while all branches are open.

**Comment by Edaka** [comment]
I tend to update to new versions manually - while I did replace the CP folder by the new one entirely, I only made changes according to the patchnotes in the CBO myself. I must have missed the table element you're speaking of, @Iamblichos , but I've looked everywhere I could with my very limited knowledge. May I ask where the responsible element is to be found in CBO?

**Comment by Iamblichos** [comment]
Traveling home today. Will definitely let you know tomorrow.

**Comment by Edaka** [comment]
Thanks! I suppose it's not that big of a deal for me, anyway, since I could just downgrade in the worst case scenario.

**Comment by ricanuck** [comment]
Until G corrects the dll code responsible for this, a workaround is:

-- Policy Branch - number of unlocked policies (finishers excluded) before branch is unlocked.
ALTER TABLE PolicyBranchTypes ADD COLUMN 'NumPolicyRequirement' INTEGER DEFAULT 100;

Change the integer to 100 in 
..\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files\Core Tables

**Comment by LoneGazebo** [comment]
I'll fix.
