### ISSUE TITLE
Cannot declare peace

### ISSUE THREAD

**Issue by maddoks** [LoneGazebo/Community-Patch-DLL#2402]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-18

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
AI and i both want to declare peace (I have won and the tool tip says he offers armistice). He also initiated/sued for peace first (offering gold as well) and his text claims that he wants to end the war as well. But I cannot accept since it is "impossible". Clicking "what would make it possible" he offers me gold, but that won't allow me to accept either. Just asking for peace iwith no gold is also impossible.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
do you have a savegame?

**Comment by maddoks** [comment]
This should be it, thanks for taking a look!
[Game.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/430982/Game.zip)

*I tried uploading the game save, but it wouldn't take it unless i zip-ed it

**Comment by rivera128** [comment]
Was a solution found? I'm having the same problem.

**Comment by maddoks** [comment]
Still waiting. Good thing i have a test next week and can put the game down for a bit

**Comment by ilteroi** [comment]
unfortunately i cannot load the savegame - this happens sometimes - there is some kind of problem with my setup

**Comment by maddoks** [comment]
I play with only the vox populi mods (from the autoinstaller), all the civ expansions and all but a handful of dlc. Thanks for trying anyways

**Comment by ilteroi** [comment]
check out #2411 - apparently there's a serious mismatch between your database and mine

**Comment by cdanger341** [comment]
I ran into this bug last night. I had a Civ on the ropes after a long war and just wanted to end it without taking more time to conquer all their cities. Eventually they approached me for peace (with a very good offer) but the offer they gave me couldn't be accepted because it was "Impossible". I attempted to negotiate peace with them again the next turn, and for several additional turns, but the Deal Value was always locked at "Impossible" even though the Civ AI desperately wanted to end the war.

Additional information: This war took place in the Classical Age, so vassalage was not yet available. Maybe the Civ's AI was attempting to become my vassal but couldn't because that tech had not yet been reached? I certainly had them in a position where vassalage would have been a possibility if I had it researched.

Unrelated, but strange none-the-less. The same game I'm playing has The Zulu, the Mongols, the Huns, and several other "war heavy" Civs in it, but despite this the in-game clock has surpassed 1000 A.D. (about 200 turns in Epic Speed) and NO OTHER Civs have ever declared war on each other save for me declaring on my neighbor for settling a city in the middle of 4 other of my cities. I even see a few instances where Civs have settled cities right between Hun and Mongol cities, and yet these Civs have been completely peaceful since the start of the game. This probably isn't a bug, but after so many games of these Civs typically starting wars as soon as they are able, their peacefulness is VERY unnerving.

**Comment by maddoks** [comment]
If my save isn't working, can someone else upload their saves? rivera128 or cdanger341?

**Comment by rivera128** [comment]
Just so you guys know, I use many, many, many, mods. In this save, I'm playing as Russia. I'm currently at war with Austria and Arabia and cannot complete a peace deal because of the bug. Also, at turn 260 I had to destroy the Zulu Civ using the Save Game Editor because it was crashing my game on the end turn phase. I don't suspect that any of the other mods are causing the error since someone in this thread mentioned that they are using few mods and are also experiencing the bug. I hope you're able to load the game.

The Community Patch Mod files that I have are too big to post so here's the link to where I go it.
https://mega.nz/#!XQsmHIDa!HypcR-Yihlj32syHOjBaZr9oBQw1i8OymRQ2N-vQzGA

When "Selecting Components" in the installer, I chose "Vox Populi (Including EUI)".

**Here are the mods I used in this particular game:**
[Civ V Mods Used.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/438900/Civ.V.Mods.Used.zip)

**And the save file:**
[Civ V Russia Save Game.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/438906/Civ.V.Russia.Save.Game.zip)

**Comment by ilteroi** [comment]
i just saw this live ... it seems the problem occurs because a city state is included in the deal.
@LoneGazebo : the deal item in question is considered a third party peace and doesn't go through.

unfortunately the UI does not allow to remove it from the deal, so that seems to be another issue

**Comment by LoneGazebo** [comment]
That's weird. The DLL allows for third party peace deals for the AI if the CS is allied to the 'to' player during s war. Or at least it should.

**Comment by ilteroi** [comment]
well this is the line which fails:

		//Can't already be offering this.
		if (!bFinalizing && IsThirdPartyPeaceTrade( ePlayer, eThirdTeam))
			return false;

the bFinalizing flag is the problem.

also, these are the contents of the deal:

![image](https://cloud.githubusercontent.com/assets/1358966/18042068/b1d2139a-6dbe-11e6-9a9d-36b00b7c730c.png)

any idea why peace itself would be included 4 times?

**Comment by LoneGazebo** [comment]
Odd on both counts.

**Comment by LoneGazebo** [comment]
Not sure why peace showing up 4x.

**Comment by ilteroi** [comment]
debugging further ...

CvTradedItem.m_bFlag1 is never changed when the third party peace is added in AddThirdPartyPeace(), so it stays false. now what it don't know is what this flag is good for - it seems to be relevant for vote trading only?

peace is indeed added twice: once in DoAddItemsToDealForPeaceTreaty() and once in IsOfferPeace() - but that seems harmless.

**Comment by LoneGazebo** [comment]
Finalizing is weird - it is used to check if an item is valid for processing versus evaluation. I'll add a ispeacetreaty check for thirdparty peace to make sure minors are auto-processed.

**Comment by choraltrickster** [comment]
Bug still exists. Suleiman AI offers this peace deal, but if I click 'propose' it doesn't accept it. Thanks if anyone is still working on this!
![2020-04-09 22_25_35-Sid Meier's Civilization V (DX9)](https://user-images.githubusercontent.com/61171515/78956721-22cece00-7ab1-11ea-898c-909b6755260e.jpg)
