### ISSUE TITLE
CTD on opening Tech Tree in late game

### ISSUE THREAD

**Issue by Hepiza** [LoneGazebo/Community-Patch-DLL#2435]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
08/18 w/hotfix

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:
Enter tech tree. Game stalls after a second, then CTD.

4. Additional information:
Same CTD using previous autosaves as well. Repeated on a fresh reinstall of game and MOD. Seemed to have a similar problem with a previous version (8-2) as well.

---------------------------
Supporting information:

[Files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/444589/Files.zip)

**Comment by Iamblichos** [comment]
@LoneGazebo This is the type of crashes I was talking to you about that can happen late game w/ EUI. I have not reproduced it without. It'll crash on some other element other than the Expansion 2 dll. Either the Localization DLL, the .exe, the D3D game renderer, etc.

His files are clean and I don't see any mod conflicts here. For lack of other reasons, I can only think this is caused by EUI.

**Comment by Hepiza** [comment]
Thanks. I will try play without EUI when I've got some time, and will see if I run into the same issue.

**Comment by LoneGazebo** [comment]
Yeah. Best bet is to close game, restart comp, then try to reload. EUI's got a fairly bloated overhead in that regard.
