### ISSUE TITLE
im missing  UI options

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2510]
_1. Mod Version (i.e Date - 4/23):_

september 12th
_2. Mod List (if using Vox Populi only, leave blank):_

CBO+ rest (No EUI)
![koreansnewversion](https://cloud.githubusercontent.com/assets/21192402/18469758/a73c2fa0-79a9-11e6-9b9c-aa73ea2e70a5.jpg)

faster aircraftanim
flag promo
RED mp
Really advanced setup

+ I tried new game with tectonic mapscript

_3. Error Description:_ 
scroll menu from  left corner with science, GP progress,  unit overview and resources dissapeared.
have no idea where to find it now.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

3. Screenshots (optional):

**Comment by matlajs** [comment]
i started new game without tectonic map script and everything is good. so at least some aditional info that tectonic isnt fully compatible with  new version.

**Comment by LoneGazebo** [comment]
Odd.

**Comment by GrantSP** [comment]
Can you provide a link to the Tectonic script? A mapscript should not have that effect and if it does I'd like to see why.

**Comment by pandasnail** [comment]
I had this happen in one of the August versions, but weirdly it didn't happen until I entered the Modern Era, and then on the next reload the ui options came back. I thought it might somehow be JFD Cultural Diversity's leader screens (my first game with that mod), but not really knowing, I didn't post it anywhere. But I do play Tectonic map, and have been for awhile (since Lighthouses got connections in fact) with no issue otherwise. From the screenshot, it looks like Matlajs and I both use the Flag Promotions UI mod as well, tho it sounds like it went away with that still enabled. But in my 9/12 it isn't happening to me with Tectonic so idk.

Anyway, here's a link: https://steamcommunity.com/sharedfiles/filedetails/?id=121243367

**Comment by pandasnail** [comment]
(meant JFD era screens, not leader screens, but looks like they can't be it so)

**Comment by matlajs** [comment]
dont know what else could do that, but i only deactivated tectonic in next game and its fine.

**Comment by GrantSP** [comment]
@pandasnail do you use EUI, because I do and I cannot see this issue. Having said that there is no code within this mapscript that should do this, however since there is another file that needs to be loaded, the XML with the text, perhaps it is interfering with something? Highly unlikely though.

You could move the actual script into the 'Maps' folder and delete the mod and then just try it from the setup screen, all you will miss is the text for the advanced settings and the description, the map will generate properly.

**Comment by pandasnail** [comment]
EUI version, yeah

**Comment by GrantSP** [comment]
Well that being the case then, the Tectonic mapscript isn't the culprit, it was merely coincidental that removing it fixed the issue. Some other combination of mods is causing it since VP + EUI alone and the mapscript doesn't cause it.

**Comment by Vyyt02** [comment]
JFYI, playing with the 9-12 no-EUI on the Tectonics map and the UI is alright.
