### ISSUE TITLE
Trading Cities during Peace Deals

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2571]
Can we make this possible again? Like maybe the AIs could trade their own cities back and the player can trade their own cities back. It has happened in history, but I'm surprised why this isn't possible anymore.

**Comment by LoneGazebo** [comment]
Cities can be traded. Not sure what you are talking about.

**Comment by TechpriestEnginseer** [comment]
I'm unable to trade cities back to them because I was the "winner" with 100 war score.

**Comment by LoneGazebo** [comment]
Correct, winners cannot trade items. It was a human-only element and I removed it.

**Comment by HalfEmptyMug** [comment]
Is it possible to allow AI winners to trade items also rather than removing the element entirely? Often when going for a diplomatic victory the AI will intelligently declare war and simply attack my city state allies, but some are nearly impossible to liberate without first going through their territory. If I take their cities I won't be able to give them back since they'll never accept a DOF, and if I raze them then I'll take an even larger warmonger hit and in some cases hurt them more than would be reasonable. This is also the case with wars where you want to liberate a conquered civ, aid an ally, or simply reduce the strength of a neighbor while still keeping them relevant in the game. This makes me dread fighting any sort of war where I don't plan on eventually conquering my opponent and is incredibly tedious. If it isn't possible to allow AI to make these peace deals, would it at least be possible to allow cities to be given back to their original owner without a DOF?

**Comment by LoneGazebo** [comment]
>If it isn't possible to allow AI to make these peace deals, would it at least be possible to allow cities to be given back to their original owner without a DOF?
You can't have exceptions outside of the class structure when defining class structure boolean logic, unfortunately.

>Is it possible to allow AI winners to trade items also rather than removing the element entirely?

The problem is that warscore (the logic that has always underpinned peace deals) influences peace deal value, and peace deal values are modifiable by the player if the 'winner' can add things to their side of the deal. This is why, for example, players could remove items from the 'winner' side in vanilla civ and the AI would accept it. Given how the structure was designed, there's no way around it.

**Comment by HalfEmptyMug** [comment]
Would it be possible then to reduce the requirement for trading cities to embassy, increase the valuation of city trades in general (with values being greatly affected by DoF?), and have the AI be more willing to make trades for their own cities? Sorry if you've already discussed this at length and for my lack of knowledge of the code, this is just one of the only issues I have with the entire project.

**Comment by LoneGazebo** [comment]
I'll give it a look.
