### ISSUE TITLE
strange build recommendation for great person

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2615]
same happened with a great scientist ... those empty grassland plots are much better places than the already improved iron.

![image](https://cloud.githubusercontent.com/assets/1358966/19219894/091b5f54-8e20-11e6-8c4d-9cb35a43b0b9.png)

there's a place in AddImprovingResourcesDirectives where it says "// this is to deal with when the plot is already improved with another improvement that doesn't enable the resource" but it doesn't seem to check if the old improvement in fact does connect the resource.

also the math in this function is really wildstyle, adding numbers in wildly in different ranges, overflows, whatnot. somebody should really take a look :)

**Comment by Enrico-Swagolo** [comment]
Also Merchant Town placement is very bad for the AI (or was in the previous version - not sure if changed). They have lots of opportunities and spots to place them on city connections, but they never do it. They almost always put it on a coastal tile on which a road will never exist, or on a tile from which planting a connecting road to any city will be hard to impossible, because they own no cities in that direction.

**Comment by ilteroi** [comment]
should be fixed
