### ISSUE TITLE
experimental DLL compatible with 10/9 version

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2618]
for anybody who is interested, an alternative DLL with rewritten tactical AI.

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/518427/CvGameCore_Expansion2.zip)

not finished yet but i'd like some feedback on the general challange level and obvious AI missteps (with savegame, if possible)

**Comment by ashendashin** [comment]
So far it seems pretty weak early on. 150 turns into epic(classical era) and many civs and city states are still relying on warriors and generally have a bad defense. They spread out their forces and try to attack my cities while I'm taking theirs without trouble.
Overall, seems to spread out far too much and build too many early units that they can't afford to upgrade. Still early and I'm playing as the Huns, so I'll see how it goes when I run into more advanced civs.

Couple screw ups I've run into:
[Suicidal Archer.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/518609/Suicidal.Archer.zip) Not a new problem, but an archer stepped out while horsemen were attacking
[Surprise Attack.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/518612/Surprise.Attack.zip) An example of an attempted attack with one of their few spearmen and yet more warriors while I was taking their capital.

**Comment by ilteroi** [comment]
@LoneGazebo : did you do anything about upgrade logic? cause i didn't ...

**Comment by LoneGazebo** [comment]
No I didn't touch it.

**Comment by ashendashin** [comment]
I'm sad to say that the AI is simply not performing well in this version with the experimental DLL. Since this only affects the tactical AI, I'll focus on the issues I've noticed regarding that first.

The most glaring flaw is the constant aggressive movement. They rarely fortify to extend the fight, only retreats when nearly dead, and doesn't seem to acknowledge that my entire army consists of mounted units. The fact that they send small numbers on suicide missions does not help.
I like how individual units behave sometimes, performing actions I'd expect from a human player, but the above flaws conflicts with the new tactics.

Unfortunately, there's not much else I can say. There seems to have been a huge downgrade in production logic for this version(sorry Gazebo) and I've built wonders that I have no right to be building with how ahead the AI was in tech early on(Great Library wasn't built despite some civs being 4 techs ahead!). Warriors and archers have seem standard by AD, with no one nearby having the gold to upgrade, and only one of 4 cities was building units to defend against me and it was the one being attacked. I may do a post on the forums after a new game in case I got a bad install.

**Comment by LoneGazebo** [comment]
@ashendashin, hate to say it, but your experience is extremely aberrant. I'm going to assume that you've either got a bad install, or another mod (or mods) has caused a conflict.

**Comment by ashendashin** [comment]
Not a mod conflict as I prefer to keep it minimal with VP. But yeah I've noticed far to many issues in this playthrough, so I'll manually remove the components and give it another go later.

**Comment by Iamblichos** [comment]
@ashendashin so you do have some mods loaded outside of VP, right?

**Comment by ashendashin** [comment]
For the session I just did:
Faster aircraft animations
Flag promotions
Quick turns
R.E.D. Modpack

**Comment by Iamblichos** [comment]
Strange regarding production logic. Been pretty aggressive in my play through's so far, both in terms of units and buildings.

**Comment by ashendashin** [comment]
Started a new game with a fresh install and so far things don't seem much different. I was wrong on the warriors being standard though. Loaded up IGE to have a look around and plenty of civs have advanced units. Just the ones in the immediate vicinity were exceptionally poor.
What hasn't changed is the wonder production(I still don't know why the civ I was attacking with the Huns wasn't building more units). They do grab up wonders, but I still don't know why no one took the Great Library in my last game. Notable difference from previous versions is that I haven't managed to get Stonehenge. Most of everything else seemed fine. Looks like I got lucky in that game as many civs were focusing on growth and border tensions.
I should be taking this to the forum rather than go on about it here, but I just felt like I needed to bring some closure to this, as I haven't played enough to be sure about all this.

**Comment by LoneGazebo** [comment]
@ashendashin,

To be clear, your primary remaining concern is that they didn't get the Great Library before you? Humans aren't going to get shut out on every wonder they want.

**Comment by ashendashin** [comment]
My concern is that the Great library is good enough to make it a strategy to beeline for it. I wasn't even trying to build any wonders and through IGE I saw that no one else was trying to build it. That's what I find weird.

**Comment by LoneGazebo** [comment]
@ashendashin I'm sure the AI did want it, but keep in mind that rushing from wonder to wonder is often considered a 'noob trap,' in that the production required for the wonder may be better used elsewhere. The AI knows this, and isn't going to go for wonders that aren't worth it relative to other, more pressing needs.

**Comment by ashendashin** [comment]
This is why I'm hesitating to bring it up in the forums. I feel like I got extremely lucky with the Huns as the nearby lands were easy to take and everyone else had high tensions along their borders. Still feels off, as I've never had an easier start before and, well, this was the first time I ever got the Great Library and it just feels so wrong... I suppose I may have gotten too used to a specific pattern.

**Comment by Iamblichos** [comment]
My experience so far is that I have not been able to get wonders that I usually have been going for, so I'm thinking this is a one time example.

**Comment by LoneGazebo** [comment]
Could be a bit of both. I'm not saying the new AI is perfect (it is objectively more intelligent than the prior one, though), and I welcome feedback, however getting blocked on wonders is not the only method by which you should judge it. Wonder-spamming isn't a goal of the AI (not all AIs, anyways), many care more about getting a proper economy going.

**Comment by ashendashin** [comment]
It's not like that was the only thing that got me here. The nearby civs were not producing modern units when others were and they did have the tech for it. Apparently having only one aggressive civ nearby was not enough for them to take full advantage of their war elephants and spearmen. This behavior is not constant though, so I paid more attention to the wonders.

**Comment by LoneGazebo** [comment]
@ashendashin are you on the experimental? It may have been more of an issue of the AI 'not sending their best' than the lack of modern units generally. Not entirely sure, though. Will do some investigating.

**Comment by ashendashin** [comment]
I've done a bad job at explaining my problems so I'll elaborate further on my experience with the experimental DLL.

There were 3 civs near me. Venice west, Inca east, Babylon north, and a couple city states I targeted. I stuck with one city and focused entirely on building a small army of mounted units to start off. Took a city state near Venice and advanced on them. Venice had a total of two spearmen and maybe 10 warriors. Problems with the tactical AI arose and I made short work of them. They did not make more spearmen and instead made one suicidal archer. I then moved onto taking another city state that produced only one spearman and some warriors.

After a short period I moved onto the Inca who had 6 cities, some of their slingers, a single war elephant, a spearman and some warriors. Took two barely defended cities near me right off the bat and they then chose to...try to fix their gold problems(according to IGE and the lack of new units during the siege. I don't know how to check for more details on the AI) while producing speamen in their capital, leaving their one war elephant to heal after they attempted a suicide attack on one of my cities. This was not a short invasion. It lasted around 20-40 turns until I took their capital.

Babylon didn't learn from this it seems because when I started looking north there were only warriors and archers in their lands.

Sorry for the long winded replies. It's just that I often go for aggressive starts and that particular game worries me.

**Comment by LoneGazebo** [comment]
Interesting – that situation does not match the behavior I've been seeing with the AI in the latest version. I'm not using the experimental tactical AI, however. If you don't mind, I'd appreciate a test (perhaps even loading up the same initial autosave) using the non-experimental 10-9-1 DLL.

**Comment by LoneGazebo** [comment]
Good news! My investigation bore some fruit. I think I see why the AI can sometimes ignore a wonder. :) Good catch @ashendashin .

**Comment by ashendashin** [comment]
That's good to hear. On the test, I used the initial autosave and I think I can safely say that I was mostly iffy about how easily I got some wonders and the lack of a proper defense from anyone nearby. I just realized how bad the nearby land is. If the Inca didn't build the pyramids the first time around, I wouldn't have attacked them so early. But it's still weird that not even Babylon goes for spearmen while everyone else does. Hell, Portugal, who has their own section of land above Babylon and doesn't have to worry about the Huns pillaging everything in sight, has plenty of spearmen.

Now that AI tactics are back to the regular state, it's taking as long as I'd usually expect to take cities. I can see how much fun it could be when the new tactical AI is better at handling mounted units though. Surprises, however suicidal, are still fun.

I think I'll continue this game. I've yet to attack anyone besides Venice and some city states, so I'll get back to this if anyone repeats what the Inca did with only besieged cities popping units.
(Quick sidenote: This is the third game I've seen Venice send a great merchant to a besieged city state. Not sure if intended)

**Comment by LoneGazebo** [comment]
> This is the third game I've seen Venice send a great merchant to a besieged city state. Not sure if intended

Besieged = barbarian horde CS?

**Comment by ashendashin** [comment]
Sorry, I meant by me. Though they did still try for it after I attacked the merchant.

**Comment by LoneGazebo** [comment]
Ah, since the AI can't 'read' what a human is doing, sometimes that can happen.

**Comment by Iamblichos** [comment]
Re: Merchant seems like a plausible move still assuming you didn't already capture it. What if he would've gotten it? Or what level of playing skill does the human have? I bet in most cases, the AI might just capture it with the merchant.

**Comment by ilteroi** [comment]
outdated
