### ISSUE TITLE
Issue(?) with a religion's founder changing when capturing a Holy City.

### ISSUE THREAD

**Issue by Chrisy15** [LoneGazebo/Community-Patch-DLL#2962]
_1. Mod version (i.e Date - 4/23):_
12-14 -- Dammit Americans, why do you do your dates backwards :p

_2. Mod list (if using Vox Populi only, leave blank):_
Only Core CP, in terms of mods that would affect this.

_3. Error description:_ 
Unsure if this is a bug or a part of the "Primary Religion" mechanic, but it's certainly different to the Vanilla game.

![20170112180706_1](https://cloud.githubusercontent.com/assets/24508935/21904263/f2f4a8c2-d8fa-11e6-8248-b2930ef1e2bd.jpg)

As seen here, capturing the Holy Cities has made _me_ the founder of the religion. If this is intentional, then I guess it might be in order to give the player access to the Founder beliefs of a conquered religion; however, doing this borks functions such as GetReligionCreatedByPlayer() so that the actual original founder is not recorded as having founded a religion (returns -1). If this is intentional behaviour, then could some consideration be given for those who may expect functions to work the same in the CP as they do in Vanilla? Perhaps caching the actual original founder so that functions such as GetRelgionCreatedByPlayer can still return a valid value?

**Comment by LoneGazebo** [comment]
It is intentional, yes, as a religion can only have one 'founder.' In vanilla, that value would allow founders to continue to gain founder bonuses even if they didn't control the holy city any longer. I rewrote the code so that founder/ownership status of a religion depends on the owner of the holy city. Feels more natural and makes religions agnostic as to their founder/origin point.

G
