### ISSUE TITLE
Wonky map generation

### ISSUE THREAD

**Issue by superunicornfan** [LoneGazebo/Community-Patch-DLL#3004]
_1. Mod version :_1/26

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Upon map generation, no resources spawn. Additionally, tiles of different continent types (i.e. "Americas" "Asia" "Europe" "Africa") are all jumbled together. I also noticed a marsh tile with the appearance of a tundra tile (tooltip indicated 3 food and marsh). 

_4. Steps to reproduce (optional):_I've actually had this issue before, months ago, but it only happened while playing a certain map script mod with CBP. Today, I disabled all mods after the first occurrence to see if the issue remained and it does. I haven't fiddled with anything; went straight from installing the patch with the installer to starting a game with no other mods and the issue is still there.

If I'm the only person experiencing this problem then I'd say ignore me and let me either figure it out myself or go back to the 1/12 version. No biggie. 

Thanks.

[AutoSave_Initial_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/736556/AutoSave_Initial_0000.BC-4000.zip)

**Comment by Rottw** [comment]
See earlier post I made about the same issues. G has a solution.  I just used 1.26.1 43 CIV VP and had no problems with the map generation.

**Comment by superunicornfan** [comment]
I typically leave More Luxuries disabled. I'll try fiddling with a few things and see if I can sort it out. Thanks for the help

**Comment by superunicornfan** [comment]
Cleared cache, reinstalled VP, no change. 

I enabled more luxuries and resources now show up, but I'd rather not play with more luxuries.

**Comment by YellowFish085** [comment]
Hello, I have a similar problem with VP v.1-26-1, and I'm using EUI as well.
*Note that I only tried this on the default "Continents" map type.*

With the automated installer, here is what worked and not.

### **Installation option "Vox Populi (including EUI)"**

- With all mods activated
  - Marsh tiles with tundra appearance
  - Very few ressources spawn (2/3 max), and only near each capital of each civilization
  - No city states

I disabled the mods one by one and finally I found that the **compatibility patch** generated the bugs, I disabled it and the bugs disappeared but then some others bugs appeared in the UI (like missing strings). Since I play with EUI, I tried another installation option.

### **Installation option "43-Civ Vox Populi (EUI)"**
- with all mods activated
  - Same problems

Again I disabled the mods one by one and finally I found the one who generated the bugs, it's the "43 Civs CP" mod. Without this mod, everything work great and there is for as far as I saw no bugs.

I don't really know the differences between the two options, but I hope this can help.

**Comment by LoneGazebo** [comment]
Sounds like your version of Civ is not up to date. Please post your Lua and database logs from each attempt.

**Comment by YellowFish085** [comment]
Okay my bad, I'm not on the .279 version, forget what I said.

**Comment by superunicornfan** [comment]
Found a fix, at least for my case. 

I had this issue with 1/26 modpack and the 2/4 modpack, but not with the 1/12 modpack. A difference between the 1/12 version and the two recent versions I noticed was that AssignStartingPlots.lua was in the CBO compatibility files pack in the two most recent versions, but in the 1/12 version, it's in the More Luxuries pack. Since I don't use More Luxuries, I simply deleted AssignStartingPlots.lua and now everything works great.
