### ISSUE TITLE
Crash while processing AI's turn

### ISSUE THREAD

**Issue by Splurov** [LoneGazebo/Community-Patch-DLL#3095]
_1. Mod version (i.e Date - 4/23):_

2/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Game crashed while processing AI's turn.

_4. Steps to reproduce (optional):_

- Load the game, activate 1, 2, 3, 4, 5, 6a mods.
- Load Pachacuti_0208 AD-1480 save.
- Press Next Turn.
- Got game crash on Spain's turn.

Here is an archive with save file, mods, EUI, dump and logs - https://mega.nz/#!PJtBxSYD!D6zUj2Pa3C67tDMlCS4qaGWxZu5efASwqaVAWCmWmhA

**Comment by Splurov** [comment]
I have another game with crash on AI's turn. Is there any method to determine what is causing the problem? It's not like there is some useful info in the logs.
It's my third game in a row with CTD, not look like an accident.

**Comment by LoneGazebo** [comment]
What's your mod list?

**Comment by Splurov** [comment]
Six CBP mods, EUI and Ingame Editor, that's all.

**Comment by Infixo** [comment]
Well, maybe my CTDs are related. Also using VP 2/15.

First - I encountered this 3 times already; this is when running auto-play via Tuner. Important thing is that I don't have these crashes if I perform the turn manually, as human player. But when I tigger auto-play again, CTD happens in 1 or 2 turns. It worked exactly like three times. I don't even have to do any action as human player i.e. I put all units on sleep or alert and it's ok. 

Last situation. CTD on turn 300. Turn 299 ok, Turn 300 Poland ok, then Netherlands crashed. I attach the logs, but there is not much.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/800656/Logs.zip)
It seems that: 
- GrandStrategy went ok
- TechAI went ok
- most of DiplomacyAI went ok, some was done for Poland but not for Netherlands
- CustomMods and PlayerHomelandAI show that Netherlands' turn was not completed
- all other logs either show nothing from turn 300, or only show Poland, no Netherlands entries

Out of the 2 I've concluded only this:
- Netherlands was at war with Mongolia and took Kabul at turn 299
- In CustomMods there's part about choosing construction projects in cities (ok) and there's no part about choosing next attack target
- PlayerHomelandAI shows that Netherlands chose new combat classes for Kabul (naval) and there's no part with unit movements

OR maybe I'm reading those two logs wrong. If they are OK then the problem lies with DiplomaticAI modules - they are partially processed.

Well, that's all. Any idea what is going on?

**Comment by Infixo** [comment]
I reloaded a save from turn 290. This time it crashed on turn 292, Netherlands again, exactly in the same place (by looking at logs). There is much less of them this time: 
[Logs CTD on T292.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/800718/Logs.CTD.on.T292.zip)
It's really annoying...

**Comment by Splurov** [comment]
@LoneGazebo do you close because there is no way to understand the reason or is it too time consuming? Maybe you know any guide how to debug such errors?

**Comment by LoneGazebo** [comment]
I closed because any time There's a new version and I've fixed bugs I close CTD reports. If it happens again let me know.

**Comment by Splurov** [comment]
Ok, thank you.
