### ISSUE TITLE
Epic speed Tech scaling is out of proportion

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3098]
_1. Mod version (i.e Date - 4/23):_2/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Tech scaling for Epic speed is not proportional for other yields by 50%.
This causes all Civs to hit Eras much, much, much later than when on Standard speed (like Renaissance in XIX cent.)
_4. Steps to reproduce (optional):_
In TechCostChanges.sql there is:
UPDATE GameSpeeds SET ResearchPercent = 325 WHERE Type = 'GAMESPEED_MARATHON';
UPDATE GameSpeeds SET ResearchPercent = 225 WHERE Type = 'GAMESPEED_EPIC';
Epic should be 150, well maybe a little more (175?) But not 225...
---------------------------

**Comment by TechpriestEnginseer** [comment]
It's to fix the issue with instant yields due to Authority's Unit Kill Bonus, Progress's Citizen Yield Bonus, and Tradition's fast GP expendation in Epic and Marathon.

**Comment by Infixo** [comment]
Unfortunately, I don't know the details of the issues you mention. But as I understand, to fix these issues you unbalanced the entire game? Because for now playing on Epic (which is my favorite speed) doesn't make sense. I'm not saying there are bugs or anything like this, only that it is breaking immersion totally.

**Comment by MoiMagnus** [comment]
I think what he mean is that tech scaling is 225 instead of 150 because multiplying time by 1.5 approximatively multiply science production by 2.25 = 1.5*1.5 : 

- Authority : The number of unit is multiplied by 1.5, and the number of unit is multiplied by 1.5, so the resulting science is multiplied by 2.25.
- Progress : The number of citizens is multiplied by 1.5 (not sure on that point), and science per new citizen is multiplied by 1.5, so the resulting science is multiplied by 2.25.
- Tradition : It is a little more complex, because the influence of GP is complex, but it should be the same.
- Others way of producing science : some of them are multiplied by 1.5*1.5, and others only by 1.5.

So multiplying science cost by 2.25 is an over-approximation, but not as stupid as it seems. I guess someone could do some tests to find which value would be the most correct, but 225 is far more reasonnable than 150.

**Comment by LoneGazebo** [comment]
Nah I totally did it to totally unbalance the game on purpose. 

In all seriousness hundreds of users play epic etc and have no issue.

**Comment by Infixo** [comment]
@MoiMagnus I have no idea why do you multiply 1.5 two times. But assuming that even if it was correct, pls. explain why there's no 900 for Marathon but 325? 3.0x3.0 = 9.0...
Standard game is design to last 500 turns, epic 750 (500x1.5) and marathon 1500 (500x3.0). All algorithms scale the values according to these.
Progress: why number of citizens is multiplied by 1.5? Food needed to grow city is multiplied by 1.5 or 3.0, so you basically don't grow bigger cities than when playing on standard, do you?
Authority: even worse - costs are multiplied, you or your enemy can't get more units than in the corresponding time on standard. 
I asked for more details about the issues mentioned.
And, btw - not many people play Epic (like 3x less than Standard). ElliotS made a quick forum poll recently (https://forums.civfanatics.com/threads/forum-metric-polls.610452/) and that was one of the questions. And as I said - it doesn't cause errors. And if you don't care about what year the game shows, you will never notice this issue.

**Comment by ashendashin** [comment]
@Infixo Just play epic for a while. I have no issue with the years to era. Medieval is reached around 1000AD and renaissance 1400 to 1600. Industrial is always in the 1800s and things speed up from there. It's no where near as unbalanced as you make it out to be.

**Comment by bryan317** [comment]
I agree.  If anything,  the first time i played Vox Populi and i noticed my techs were behind the actual date shown,  i just realized i much to improve on to get better at the game.  I just quit and Epic game as Aztecs on Emperor because i became extremely over powered early.  No challenge.
