### ISSUE TITLE
Archaeologists cannot dig?

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#3127]
_1. Mod version (i.e Date - 4/23):_ 15.2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
My archs cannot dig in my vassals land. Bug or WAD? Not sure. Menu option is not present. They can dig in CS lands though.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Radost** [comment]
You have to open your borders to them in order to dig.

**Comment by ricanuck** [comment]
Really? Since when? I want to dig in their lands, why would I need to give them OBs? Anti-exploit?

**Comment by ricanuck** [comment]
Just tried my ongoing game from the last save, and now suddenly I have the option. Again, I am in Denmark's lands, he is my vassal so I have auto OBs with him (but I did not give him OB). Before the last save, I could not dig in his lands. After reloading, now menu option is there. I then tried reloading the same save file again, and this time I cannot dig again.

Something is clearly off here. Cannot be WAD, must be a bug.

**Comment by TechpriestEnginseer** [comment]
You need to have both OB in order to dig.

**Comment by MinnetonkaWinter** [comment]
Had this happen to me twice.  Finally figured it out.  Vassal was using its own worker to remove a road on the antiquity site.  During that time I could not dig.  When vassal's worker was finished, I could then use my archaeologist to dig the site.  What is misleading is the game's notification which states that you cannot dig on a site outside your territory.  Since that is not true, it looks like some kind of bug.  The notification appears when you hover over the archaeologist's darkened dig command when the archaeologist is on the antiquities site along with the vassal's actively working worker.  
![Screenshot 2023-01-03 153437](https://user-images.githubusercontent.com/121903148/210445146-6976461a-c0da-45be-834d-bf3900e8f1d5.png)
Perhaps the notification should be changed to reflect the real reason the archaeologist cannot dig.
