### ISSUE TITLE
observations

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3129]
got an invalid peace offer again:

![image](https://cloud.githubusercontent.com/assets/1358966/23586546/a634554e-0197-11e7-9fd2-326d85669e06.png)

AI still loves building chanceries - both pataliputra and damascus were recently conquered:

![image](https://cloud.githubusercontent.com/assets/1358966/23586549/c31557da-0197-11e7-931d-4ea976285ae2.png)

also note that the indians are on the verge of being defeated, yet they don't build any units. castle in delhi isn't bad but the turn before they were building a customs house ...

also a million errors like this in firetuner:
 UnitFlagManager: IconHookup error - icon index:	5	icon size:	16	atlas:	KRIS_SWORDSMAN_PROMOTION_ATLAS	image control:	Promotion2

**Comment by ashendashin** [comment]
Ah FlagPromotions. I bet most of the late game crashes users experience are due to that error.
And I'm no longer the only one to mention the lack of militarization during war! Yay! Err... No!

Sorry, I just wanted to drop by on the FP error, since I think some people might be mistaking late game instability on VP.

**Comment by ilteroi** [comment]
i suspected it's flag promotions ... but then i can't remember seeing those errors before

**Comment by ashendashin** [comment]
It's a weird one. I tried spamming some Kris swordsmen to no result on a fresh game. But I found out that FP was the cause of ceaseless crashing on one of my games. I may have missed an update, so I blamed it on that. In case it was a memory issue on my part, I ran a 43 civ game on giant Earth without it. There were no CTDs

I tried it again but got another hookup error with E&D so I gave up. Some on civfanatics mention late game instability and considering its popularity, I'm confident that the cause is FlagPromotions.

**Comment by saamohod** [comment]
The KRIS_SWORDSMAN_PROMOTION_ATLAS Firetuner bug is still present in 3-7 version.

**Comment by Vyyt02** [comment]
Would be great if someone could take a look at the FP errors. I have not had any CTDs in my huge epic games - the current one is in early industrial and Indonesia is in it and doing very well, having lots of units. But maybe I am just lucky or maybe my machine is powerful enough to handle the problem - maybe I will encounter problems in the later stage of the game.

**Comment by LoneGazebo** [comment]
It's not our mod. I'd ask around. JFD might oblige.

**Comment by ilteroi** [comment]
i haven't experienced a crash because of flag promotions yet, so maybe the error is harmless.

what about the other problems? fake peace offer and production choices? sorry for cramming all this into one issue

**Comment by LoneGazebo** [comment]
@ilteroi,

Fake peace can happen if you step into the AI on a peace turn - did you?

Production choices were looked at for 3-7 version.

**Comment by ilteroi** [comment]
re: peace - just regular play, no observer mode - hasn't happened in a while, guess it's hard to debug now, but just to let you know it's still there
