### ISSUE TITLE
AI bribed me into a war with someone I don't have borders with

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3203]
![image](https://cloud.githubusercontent.com/assets/1358966/25500554/bb01e596-2b8f-11e7-8879-e311f4aebe10.png)

I'm persia in the southwest and quite weak regarding army size. greece (east) just gave me 15 gpt and two luxuries to declare war on poland (northeast). i don't share a border with poland and there's no way i'll influence the course of the war.

maybe the AI should consider this? otherwise it's just a windfall for me.

**Comment by bigcat88** [comment]
I see in my games very often such behaviour. Better will be if AI will calculate path distance between player and target and then decide - ask for help or not. Cause if distance between player and target AI for war is big(on large and huge maps) - even if u have path(for example sea map), u can just agree and dow, and then just make peace after 15-25 turns.

**Comment by ashendashin** [comment]
It should definitely influence the bribes worth, but it's really frustrating to have my trade routes and deals between civs broken due to these bribes. It seems a valid strategy with all the extra stuff the AI can deal with losing. Those random ships exploring the world replaced barbarians in my games because of all these bribes, which is actually kinda fun.
