### ISSUE TITLE
Suicidal embarkation

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3221]
_1. Mod version (i.e Date - 4/23):_latest hotfix

_2. Mod list (if using Vox Populi only, leave blank):_FlagPromotions v.7

_3. Error description:_ 
An enemy land unit jumps into water right in front of my navy which AI obviously can see.
A bug as old as vanilla game. Attemps been made to fix it but apparently not so successful.

_4. Steps to reproduce (optional):_

Savegame 
[AutoSave_0250 AD-1700.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/980888/AutoSave_0250.AD-1700.zip)
![20170506144651_1](https://cloud.githubusercontent.com/assets/16341598/25772092/8b440a5e-326b-11e7-9cc9-df4074571e27.jpg)

**Comment by ilteroi** [comment]
one of those saves i can't load unfortunately ... so let's do it the other way, here's a test build. no specific changes for this situation because i don't really have enough information, but maybe it's gone anyway.

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/981208/CvGameCore_Expansion2.zip)

also, there's a lua script, which will change the mouseover tooltip to show you what the unit is up to. also it's ID, which allows you to find out more about it in the logs. put it in the EUI compatibility / LUA folder.

[PlotHelpManager.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/981209/PlotHelpManager.zip)

**Comment by ilteroi** [comment]
ok, found this in one of my own games. fix is on the way

**Comment by saamohod** [comment]
Literally dancing with joy right now.
Great job ilteroi!

**Comment by ricanuck** [comment]
can confirm, saw it a lot in a game using the previous version (5-2). Is the fix included in the new recent 2-10 version?

**Comment by LoneGazebo** [comment]
Unless @ilteroi is a time-traveler, no @ricanuck it is not in the 5-10.

**Comment by ricanuck** [comment]
hey... baby making you moody? :smile:

**Comment by ilteroi** [comment]
that kind of provocation is completely uncalled for.

anyway, fix for embarking is pushed, together with another fix which prevented AI range attacks in many situations. didn't test much but AI performance should be noticeably better.

**Comment by LoneGazebo** [comment]
@ilteroi ha, just pushed a hotfix. Oh well, here we go again :)
