### ISSUE TITLE
Random Graphics for new Scout Promotions

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#3281]
current version, 9/6

![scoutbug](https://user-images.githubusercontent.com/24731508/27004221-168e4e16-4e06-11e7-8ceb-db21b49667ce.png)
![scoutbug2](https://user-images.githubusercontent.com/24731508/27004222-169a6d86-4e06-11e7-8108-f661d7eb0539.png)

Icon for Spotters

**Comment by HalfEmptyMug** [comment]
Non-EUI version with hotfix, seems to happen only after adding trailblazer 
![](https://i.imgur.com/JlJr4YL.png)

**Comment by TechpriestEnginseer** [comment]
I'll need your lua logs. This seems pretty easy to fix since I encountered this before provided that this is the same error.

**Comment by HalfEmptyMug** [comment]
[Scout Promotion Lua Log.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1066707/Scout.Promotion.Lua.Log.zip)

Lua log from loading my current game and promoting the offending explorer through IGE. In my case the issue is pretty tricky to directly reproduce, but has also occurred for me in version 5-26.
