### ISSUE TITLE
Crazy mission values

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3462]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

every cs quest gives around 90+ influence, 100+ X, starting from ancient. Intentional?

**Comment by Enrico-Swagolo** [comment]
The next wave of quests is less generous. Maybe it's just barbie camps they're desperate to get rid of?

**Comment by LoneGazebo** [comment]
That's just the randomizer being random.

**Comment by cdanger341** [comment]
Yeah, I was wondering about this too. I managed to be Allied with 4 out of 5 nearby CSs in the Ancient Era just due to taking out Barb camps and Luxery quests that all awarded 75-100 influence each. Now, in the Renaissance I have 7-8 CSs with 500+ influence just from randomly completing quests due to many quests offering 90-100 influence for each completed quest. I guess this is just how it's intended to work now?
