### ISSUE TITLE
Naval units and forts

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#353]
How do they interact?
I've built enough forts to make a canal on the other side, even movement preview agreed with me:
![8930_2015-06-23_00011](https://cloud.githubusercontent.com/assets/1131228/8305277/e3cf2d9e-19c6-11e5-80c5-1d9be33d6c75.png)
But nope:
 ![8930_2015-06-23_00012](https://cloud.githubusercontent.com/assets/1131228/8305284/ef486370-19c6-11e5-89c3-0377d5b59927.png)

**Comment by ilteroi** [comment]
i assume the issue is you couldn't move into the lake to the northwest of the citadel?

anyway, it's probably because there are two different pathfinders at work. unfortunately there are about ten, and the differences are not always clear.

good catch, but a rare case ... could even be viewed as an exploit, AI will definitely never be smart enough to do such a thing. if we want to do anything about this, i would prefer to prevent ships from entering citadels/forts at all.

**Comment by Radost** [comment]
But AI is quite smart, I've only built citadels, forts were already there.

**Comment by LoneGazebo** [comment]
You can't move beyond one tile into the coast - you can't make 'land bridges' that long.
G

**Comment by DanteValerian** [comment]
Forts acting as 1-tile canals is an awesome feature, I definitely wouldn't want to see it removed.

But yes, if you could chain citadels and forts together, that would be insane/absurd. Most epic canal ever.
