### ISSUE TITLE
Happiness calculations are skewed

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#356]
https://www.youtube.com/watch?v=cE4WvSzgiTo
Merchant gives 1 science, but for some reason incurs 2 illiteracy even though the resulting science output is higher.
https://www.youtube.com/watch?v=Hz0n0ztSi20
Merchant incurs isolation penalty (lolwhat) and engineer causes illiteracy.
https://www.youtube.com/watch?v=MyqXJDHA8ns
Again merchant causes illiteracy even though the resulting science is higher.

**Comment by LoneGazebo** [comment]
Are you sure this isn't a consequence of civilians being satisfied in one way, but then becoming unsatisfied in another way?
G

**Comment by Radost** [comment]
So, not only the happiness system is being quite convoluted, it doesn't even show all numbers?
Basically there is no point in settling (or capture) cities past renaissance era (and use advanced settler units), because all happiness values are based on fully built supercities filled with specialists. And the only way to counteract these penalties is to assign specialists, which add another unhappiness on top of city population.

**Comment by LoneGazebo** [comment]
What are you talking about? Each citizen can only be unhappy for one thing at a time. If, say, 5 out of 6 citizens are unhappy because of poverty, and you eliminate poverty enough to satisfy one of them (so only 4 out of 6 are now unhappy for that), the newly 'freed' citizen then looks for something else to be unhappy about. There's a scale (famine, poverty, disconnection, etc.) that the citizen looks at, stopping at the most severe element on the scale and then going on from there.

Unhappiness uses a median, not a raw average, so no, the 'global average' is not drastically inflated by the massive cities of the world.
G

**Comment by Radost** [comment]
The thing is even Order colonist-settled cities start with capped unhappiness.
It's like BNW penalty for number of cities, except you can't see the number.

**Comment by LoneGazebo** [comment]
Except that you can - happiness information is plastered all over the place.
G

**Comment by Radost** [comment]
As shown in the videos - it doesn't show all the information. Apparently numbers are even higher, which you won't know unless you try to get rid of them.

**Comment by LoneGazebo** [comment]
The videos show what I modeled above - citizens no longer being 'unhappy because of x' become 'unhappy because of y.' The happiness calculation doesn't even happen if citizens can't be unhappy for it (by that I mean, in the DLL, I return a value of 0 if there are no more citizens to be unhappy about stuff  because they're already unhappy about other things). Those numbers (for example, illiteracy appearing after you reduced poverty) aren't calculated, or even there, until the other issues are satisfied.

G
