### ISSUE TITLE
Upgraded dromons to galleasses can cross oceans

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3620]
_1. Mod version (i.e Date - 4/23):_
10-17-1

_3. Error description:_ 
In my last game I was able to cross oceans with galleasses. After I finish that game, I found in a test game that if I upgrade my dromon to galleass it loses promotion that denies it to end turn on oceans.  

_4. Steps to reproduce (optional):_
Create duel map, give techs till sailing , buy a dromon, give techs till guild technology, upgrade dromon.
Galleass will cross ocean tiles ) But that galleasses that are build or purchased cant cross oceans.

**Comment by RandomNub** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/3525

Despite G claiming it's WAD, it randomly happened after a patch and makes no sense (due to realism, those ships were never meant for open sea, and gameplay because it nerfs caravels niche). Not sure if the bug involving Sea Beggars has been addressed either.

**Comment by bigcat88** [comment]
1. Astronomy don't need to lost promotion.
2. I repeat it 2 test games in a row after a game I found it. I can test 2 times more, if needed...
