### ISSUE TITLE
"Corporations & Monopolies" window cannot close. Ever.

### ISSUE THREAD

**Issue by Regularitee** [LoneGazebo/Community-Patch-DLL#3664]
I've tried:
- Restarting the game client
- Loading older saves, in which the window was never open
- Trying to open other in-game windows
- Changing between the DX11 and DX9 version of the Civ5 client.
- Changing the game resolution
- Changing between fullscreen and windowed mode
- Reinstall of the mod
- Smacking random keys on the keyboard 
- Banging my head against the wall

**Comment by Regularitee** [comment]
It appears the issue was part of the save itself -- simply starting a new game took care of it. Though the cause remains unclear, as I did not touch any of the files.

**Comment by MoiMagnus** [comment]
Step 1) Go to the DLC folder. Delete the ui_bc1 folder. Also delete any DLC mod you might have installed and forget (for example, a modpack)

Step 2) Delete the MODS folder, the cache folder, the ModUserData folder.

Step 3) Restart steam in offline mode (alternatively, unsubscribe to every mods you have subscribed to)

Step 4) Try an un-modded game. If there is anything that is not "normal", the problem is not Vox Populi.

Step 5) Install the no-EUI version of VP, and try a game. Do not use any other mod of any kind, even graphics mods.

Step 6) If it does not work, try any modpack of VP instead, you never know.

**Comment by Regularitee** [comment]
I think I found the cause. Steam auto-updated mods when it detected a conflict, which caused it to overwrite the manuallu installed recent version of CBP with the buggy/broken steam version of the CBP patches. Since removing all steam-updated mods, haven't had the issue.
