### ISSUE TITLE
Treasure fleet project problem calculating production

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#3681]
_1. Mod version (i.e Date - 4/23):_

6/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Haven't progress further in this game, I suppose that this problem will happen with all projects, when tested I'll update here.
In the turn where the project is finished, production is applied both to the project AND to the next item in the queue.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
Yeah, I noticed that too, but I think it is so small bug that can called "intended" )

**Comment by LoneGazebo** [comment]
The issue is that projects can complete mid-turn sequence, so players who assign the project but it is completed would lose a turn of production. The alternative was this, in which you gain a turn of production if it finishes in a round. This happens because the production here is assigned at the beginning of a game turn, not during a player's turn. I think it is okay, honestly - a bonus round of production is at least not penalizing.

**Comment by Mitchsp** [comment]
Well, if there isn't the possibility of avoid it, yes, is in any case the lesser evil.
