### ISSUE TITLE
Production Freeze and various other issues

### ISSUE THREAD

**Issue by winlongummy** [LoneGazebo/Community-Patch-DLL#3742]
_1. Mod version (i.e Date - 4/23):_
12/9

_2. Mod list (if using Vox Populi only, leave blank):_
Only use Vox Populi, no-EUI

_3. Error description:_ 
A. Research screen is messed up.
![image](https://user-images.githubusercontent.com/34393276/33794389-57929b34-dc80-11e7-9c17-d07b40c4ae6d.png)

B. Around turn 70+, I can no longer choose production of a random city and therefore cannot move forward in the game.
![image](https://user-images.githubusercontent.com/34393276/33794407-c908efac-dc80-11e7-85a9-e2df8272a6eb.png)

_4. Steps to reproduce (optional):_
I have already tried resinstalling Civ5 and Vox Populi. I've removed all other mods.
Logs and save included.
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before 
[20171209 Production Issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1544526/20171209.Production.Issue.zip)
experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by winlongummy** [comment]
Sorry, I didn't realize the link to the zip file was going to be embedded in the text like that. Here it is again:
[20171209 Production Issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1544527/20171209.Production.Issue.zip)

**Comment by MoiMagnus** [comment]
Check that you have all the required DLC (i.e all of them, except the maps pack)

**Comment by winlongummy** [comment]
I have all the DLC. Even the map pack.

**Comment by winlongummy** [comment]
Tried playing one more game, still the same problem. Right around when I reach Classical, a city's production freezes up, along with every other city's. Cannot change production or queue new production.

**Comment by MoiMagnus** [comment]
Research screen shouldn't be messed up anyway. There is something wrong with your installation. Here is a list of things to check:

1) Have you enabled all the 6 mods of Vox Populi, with number (1), (2), (3), (4), (5) and (6b) ?

2) Did you subscribe to a steam version of More Luxuries or Community Patch ? If yes UNSUBSCRIBE. Because they mess with the auto-installer and steam.

3) Go check into your DLC folder for "things that should not be there", for example : 
+ An old version of EUI (folder name : ui_bc1)
+ A forgotten modpack

4) Check a game without mods (just launch a game and look at the tech tree)

5) Delete the cache folder and the moduserdata folder. Reinstall Vox Populi. Try again (launch a game with VP, and look at the tech tree)

6) Try the EUI version of VP, usually EUI cause more problems that what it solves, but you never know.

**Comment by winlongummy** [comment]
1. Yes
2. No
3. Nothing of interest
4. No problem
5. Deleted the cache folder as well as ModUserData. Loaded old save and still had a broken research screen. Started new game and had the same issue.
6. This, hilariously, fixed it. I'm not the biggest fan of EUI, but I guess this solves my problem. Maybe look into checking your non-EUI auto-installer? Hopefully noone else is facing this problem.
