### ISSUE TITLE
crazy bonuses in lategame

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3776]
so i've been analyzing what's happening in the lategame, and wow, there are some astonishing cities there ...

warsaw:

![image](https://user-images.githubusercontent.com/1358966/34323324-ec25f9fc-e843-11e7-80ef-75675c2b76d5.png)

is this all correct? not working the oasis (-5 food) reduces the surplus to 653, a difference of 24 or almost 500% leverage. i thought we were trying to reduce the % bonuses?

delhi;

![image](https://user-images.githubusercontent.com/1358966/34323419-1d1146b2-e848-11e7-8727-56a94121e863.png)

same here, more than 400% leverage.

now admittedly, those are the most extreme examples, with trait and twokay foods respectively, but is this the way it's supposed to play out?

**Comment by Infixo** [comment]
Tourism Modifier from TR has the same effect on gold value of TRs. Base GPT is reasonable and then +100%, +150% or more from it and TR is out of control. You wouldn’t need any distance penalty if those TR weren’t boosted so much in the first place.
Maybe as a general rule you should put a cap on any modifier at 50 or 75% to avoid stacking to such crazy effects.

**Comment by LoneGazebo** [comment]
Well, growth is a special beast since it is a modifier of the net value post consumption. Also yeah, corporations add a lot, but they need to to be worth the investment late game.

**Comment by Infixo** [comment]
ToolTip for TR shows modifiers, and they can get high. I will check tomorrow what they are exactly, maybe I mixed something.

**Comment by LoneGazebo** [comment]
Hmm, we’ll have to see. May be a lua typo.

**Comment by Infixo** [comment]
![tr calc](https://user-images.githubusercontent.com/25866684/34329543-da5f12d2-e904-11e7-9f21-0c655bb9768d.jpg)

Here are examples. These all should basically be worthless or mediocre TRs, because there's simply not much to trade. But they all get flat 8 from influence, plus Open Borders, plus Sea sometimes and suddenly they are one of best TRs in the game. "Modifiers" - I meant that this flat value is often x2 or x3 the base value.
E.g. case 3 - base value 2 (!), +5 from buildings, +8 influence -> total ~22 GPT!
case 1 - 1 res, base value 4, +8 influence -> total 17 GPT
case 5 - 3 res (good), base value 6.5, +8 influence -> total 17 GPT
This flat bonus in early and mid game is worth much more than entire base TR value.
Late-game, due to many buildings boosting TR value, this effect is not so visible.
