### ISSUE TITLE
Authority Culture from Barbarian Camps Does Not Scale with Gamespeed

### ISSUE THREAD

**Issue by ziadb** [LoneGazebo/Community-Patch-DLL#3885]
1. Jan 14 beta version non-hotfix

2. VP, Civic and Reform, Ethnic Units, JFD CulDiv + Soundtrack, some aesthetic mods

3. Culture from Authority Barbarian camp clears does not scale with gamespeed. It provides 25 culture irrespective of gamespeed. Given that barbarian camp gold returns do scale with gamespeed, this feels inconsistent.

I don't know if camp spawn rate does scale with gamespeed, but from experience, there are way more barbarians in the early game than on Marathon. 

This may be one contributing factor to why Authority AI civs on Marathon tend to lag behind in culture sometimes compared to their Tradition/Progress counterparts. Just a suspicion.

4. Start Game
Play Authority
Clear Barbarian camp
Observe culture on clear

**Comment by cdanger341** [comment]
I thought none of the "on kill" yields scaled with gamespeed (from Authority policies, God of War, and UAs) because it was assumed that there would be more fighting, wars, and unit deaths in Epic and Marathon. If there is more fighting and killing at longer gamespeeds and on-kill yields scaled with gamespeed, then you'd be getting exponentially more yields than on Standard speed, making the Authority policies and such more valuable depending on the speed of play. Maybe I'm wrong about this, but I could swear I remember this exact complaint coming up last year and it being shot down as an intended feature of VP.

**Comment by ziadb** [comment]
Actually on-kill yields do scale. Pictish Warrior for example provides 12 faith on kill on Standard but 36 on Marathon. God of War scales. Morrigan scales. War Chariot production skills.

It's also not true that there is more fighting on longer game speeds. Units take 3 times the amount to recruit, barbarian spawns are slower, and gold costs of unit purchases are tripled. 

You're more likely to win wars however since you are smarter than the AI and they take more time to replenish, but that's not relevant to on-kill yields. T

Regardless that's not the issue being discussed here, as I don't have enough data on what scales and what doesn't when it comes to on-kill bonuses and I'll make a post about it when I do (might be inconsistencies).

What is definitely inconsistent (and the topic of this github report) is that barbarian culture CAMP clears does not scale. Gold however does. From empirical experience, barbarian camp spawns does not scale. I have never faced barbarian armies on Marathon, but frequently do so on Standard. At least not past the initial spawn wave from the very 1st spawn.

**Comment by MoiMagnus** [comment]
@ziadb The number of kill do increase with gamespeed, at least in single player, but not enought to compensate an absence of scaling. If the number of units you kill per war does not change a lot trough gamespeed, the number of war you are able to make do scale. 
In quick speed, you have a reasonnable chance of some civs never being at war during the entire game, while it is not the case in marathon.
Moreover, at hight difficulty, the AI is quicly able to build back and army, and is more limited by its supply cap than by its production, so they do produce more units in marathon than in quick.

I am not sure how barbarians work with game speed. If barbarians spawnrate is independant from gamespeed, then more of them are generated in marathon than in quick, so it is normal that culture on kill and culture on barbarian camp clear does not scale.

**Comment by ziadb** [comment]
Peace treaty durations scale with gamespeed, so you don't do even do more wars if your goal is to enter war -> kill units - > peace treaty -> repeat. 

Again I dont see how it matters that the AI can build back its army. That's independent of gamespeed. Costs do scale so it takes 6 turns to rebuild that unit that would take 2 on Standard.

**Comment by MoiMagnus** [comment]
The duration of a war is mostly idependant from gamespeed, since the units mouvements and damages dealt per turn does not scale.
In marathon gamespeed, assuming a pangea map (and a difficulty low enough), you can reasonable take over the world before rennaissance, while it is unrealistic for quick speed, since you won't have physically the time to make enough wars.
Meaning that the number of civs you can attack during one era, which is strongly correlated with the number of units you can kill during one era, scale with gamespeed.

I am not sure there is a lot of difference between epic and marathon. And the difference between standard and epic is probably lesser then the difference between quick and standard. But in quick there is tons of units that you don't have the time to kill (or even attack) before they get upgraded or disbanded.

**Comment by ziadb** [comment]
We'll make a thread about on-kill and talk about it so we don't spam github.
