### ISSUE TITLE
CS quest reward grants unhappiness rather than happiness.

### ISSUE THREAD

**Issue by aldebaran1997** [LoneGazebo/Community-Patch-DLL#3894]
CS quest "Declare war on someone (Aztec in my case)"'s reward was 4 happiness and my global happiness was -4. But after I declare war on them and pass the turn, my global happiness becomes -8 without any pop growth and there was no deal or TR between me and them. Also there is no war weariness or pillage.

**Comment by Infixo** [comment]
It seems that quests with Hapiness as reward actually give Local Culture. In CvMinorCivQuest::DoRewards there is:
```
if (GetHappiness() > 0) {
    kPlayer.doInstantYield(INSTANT_YIELD_TYPE_MINOR_QUEST_REWARD, false, NO_GREATPERSON, NO_BUILDING, GetHappiness(), false, NO_PLAYER, NULL, false, kPlayer.getCapitalCity(), false, true, false, YIELD_CULTURE_LOCAL, NULL, NO_TERRAIN, this);
```
I think it is intended since doInstantYield() doesn't support Happiness at all. Just yields, GAP, GG/GA points, pop changes and Local Culture. So, better quest description is necessary I think.

**Comment by LoneGazebo** [comment]
Nope. Follow the rabbit hole. :)

**Comment by Infixo** [comment]
Oh, yeah. It is CalculateRewards() then.
Seems that Irrational minor can actually give negative happiness, so that is ok.
But I noticed that this negative is not bottom-limited. Positive is top-limited to 4, but no limit for negative, it can go down to -29 in worst situation (Ancient Era, 2 bad rolls). In later eras this situation is less likely as "initial happiness" gets bigger (*iEra).
```
//Cap it to keep things under control.
if(iBonus > pkSmallAwardInfo->GetHappiness() * 4)
{
iBonus = pkSmallAwardInfo->GetHappiness() * 4;
}
SetHappiness(iBonus);
```
Btw, iBonus is scaled with Era, as if an intention was to give more happiness with passing Eras,
but later is limited to 4 anyway. What gives?

**Comment by LoneGazebo** [comment]
Anything more than 4 gets weird.

My rabbit hole point was that I hijacked yield_local for the minor civ instant yield event to give happiness, as adding new yield types slows down the game.

**Comment by Infixo** [comment]
Ok, you mean the exception for getCapitalCity()->ChangeUnmoddedHappinessFromBuildings(iValue). Right.
Anyway, Irrationals can create big negative numbers when unchecked.

**Comment by LoneGazebo** [comment]
Yeah. Probably should control for that. Mind taking a stab? I think making the min value equal to the initial seed value of the quest reward would be fine.

**Comment by Infixo** [comment]
Do you mean the value which is a quest param in DB, i.e. 1 in this case? So, basically limit it to <initial..4*initial> Sure can do.

**Comment by LoneGazebo** [comment]
Yep.

**Comment by aldebaran1997** [comment]
So, you mean CS actually gives me big chunk of unhappiness as quest reward? It must be displayed properly then, I guess.
