### ISSUE TITLE
Terrace Farm / Colonia showing icon on tech tree (fertilizer) for wrong civs

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#3966]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

 tree should still read the upgrades are there of course, but I read there should be overrides in place to not display icons for civ uniques to other civs that cannot use them- is it not applicable for these CBP additions? This bogs down an already restrictive 5 icon limit unnecessarily, and clutters the interface with some useless info for vast majority of civs

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Sometimes you may get access to them(conquering) to which the techs can grant bonus yields to them.

**Comment by deadstarre** [comment]
thatd be a stretch to justify making fertilizer look much better than it is the other %99 of the time. and besides, theyre hiding an important laborer citizen upgrade that is crucial for me to know at a glance! actually im moving things around the tech tree and sadly those stupid terrace farms are hiding useful icons. but really, you know how many times I took fertilizer only to find out that plethora of upgrades I thought should be coming were just a bag of lies? =)

**Comment by Edaka** [comment]
I don't remember how exactly, but at some point I managed to make all the civ-tied info appear after all the rest. Granted it should already be the case, I remember reading it in the patch notes of some ancient version. Perhaps it's a simple issue of what the mod load firsts. 

In any case, I've wanted to take a look at it for a long time now, so I can try to help with that.

**Comment by deadstarre** [comment]
tech tree seems to me to pick favorites regardless of the order of loading, I tried a couple things out and certain icons were stubborn to show no matter what order I arranged things. if you find out differently thatd be cool though, i'd love to be able to pick which icons show without getting into techbuttoninclude.lua stuff

**Comment by Edaka** [comment]
I'm sorry it's taking so long, just a heads up that I'm still on it.

**Comment by Edaka** [comment]
Here's what I found. Colonia: if the _CivilizationType_ column in the _Improvements_ is empty, the values from  _Improvement_TechYieldChanges_ show up on the tech tree (like in the current official release). Adding _'CIVILIZATION_VENICE'_ into that column for the Colonia makes the yields disappear for civs other than Venice, which is good.

However, for the Terrace Farms  _CivilizationType_ isn't empty already, and the yields still show up for non-Incan civs. I think that's because the tech buffs are handled through other, different tables: _Improvement_TechFreshWaterYieldChanges_ and _Improvement_TechNoFreshWaterYieldChanges_. 
Another, probably related, oddity with these tables: if you look in-game at the Plastics tech, you'll see that there are two buffs to non fresh water plantations that should be condensed into one button, but they aren't.

So, it seems to me that Techbuttoninclude.lua handles _Improvement_TechYieldChanges_ differently from _Improvement_TechFreshWaterYieldChanges_ and  _Improvement_TechNoFreshWaterYieldChanges_. Yields from the latter tables aren't hidden from unrelated civs, neither they are condensed when appropriate. I would appreciate if somebody with lua knowledge took a look at that. I don't remember exactly who worked on hiding civ-unique info on the tech tree, but my intuition tells me it's either @TechpriestEnginseer or @JFDaly .

**Comment by JFDaly** [comment]
Yeap, was me. I'll take a look when I can, and add/fix support for the other tables. Might've just overlooked them.

**Comment by LoneGazebo** [comment]
@Edaka don't fret too much about those two tables, VP is about to condense it all into just techyieldchanges for improvements.

**Comment by Edaka** [comment]
Cool beans!
