### ISSUE TITLE
captured scout

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3972]
since a few versions back, units can only be disbanded in owned territory.

now, my archer is caught. what am i supposed to do? i really need to get rid of it. so i gifted it to a city state. same result as disbanding, or in fact even better. so what was the change about?

![image](https://user-images.githubusercontent.com/1358966/36341159-2721fe30-13ea-11e8-984c-9917cb21e7b2.png)

**Comment by LoneGazebo** [comment]
Players can scum an AI out of a kill by scrapping the unit before an AI gets to kill it. It was a common tactic. I ended that. 

Scouts are supposed to be able to be disbanded but since he’s upgraded he’s no longer able to do so. 

Could probably change the code again to have it check for danger nearby to prevent disbanding. That makes sense.

**Comment by ilteroi** [comment]
the danger check idea sounds good ... but it should also apply to gifting for consistency
