### ISSUE TITLE
Constructing Improvements on Forest/Jungle have the wrong turn tooltip

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4097]
_1. Mod version:_
18-3-11

_3. Error description:_ 
On Marathon, the displayed turns to construct an improvement on a forest or jungle does not match the actual number of turns to do so. For example, a village on flat ground takes 23 turns to build:
![18-3-11-1 turns - village](https://user-images.githubusercontent.com/34615525/37859809-75da3852-2edf-11e8-82ff-40b39423ab78.png)
However, the display says that it takes 36 turns to build it on a forest, and 39 on a jungle. This implies that it takes 13 turns to chop a forest, and 16 turns to chop a jungle.  These only actually take 9 and 13, respectively.
![18-3-11-1 turns - forest village](https://user-images.githubusercontent.com/34615525/37859833-bc3f276c-2edf-11e8-9274-8d69b91b3c07.png)
![18-3-11-1 turns - jungle village](https://user-images.githubusercontent.com/34615525/37859832-b854974a-2edf-11e8-99c0-ae6c70047e1b.png)
The time it takes to actually construct the improvement is still in practice only the 9/13 turns to chop the forest, plus whatever number of turns it takes to construct the improvement on bare ground.

**Comment by UndeadDevel** [comment]
Happens for me as well on 2/27.

**Comment by LoneGazebo** [comment]
It's just an EUI quirk, not much I can do about it without some heavy grinding (@Infixo you like these sorts of things, no? :) )

G

**Comment by LoneGazebo** [comment]
@Infixo mind taking a look?

**Comment by Infixo** [comment]
I'll see what I can do.

**Comment by Infixo** [comment]
Ok, I know where the problem is, actually kind of tricky one. I will fix it.

**Comment by LoneGazebo** [comment]
Tricky? EUI? Well I never.

**Comment by Infixo** [comment]
Situation is as follows.

The game calculates build time in some internal units, e.g. Plantation is 600, Repair is 300, Jungle removal 400, Forest chop 300, etc. Build time is affected by BuildPercentage from GameSpeed and Eras (if you start later, you build faster). Number of turns is calculated as build time / work rate, rounded UP (math.ceil) if necessary. Work rate is 90 for a Worker.

If the game detects that there's a feature to be removed on a tile before actual build, it adds additional build time unique for each build that is kept in BuildFeatures table. The tricky part is that Feature removal has its own unique BuildType, also defined in BuildFeatures. So, basically you can specify a different chop time for each build, and different from only pure removal. And that was the situation. Simple Forest removal is 300, but builds other than removal had it as 400 (some even 500). Same goes for Jungle. Marsh was more or less ok, almost all builds were set ty 600.

I set all forest removals to 300, all jungle removals to 400 and marsh to 600.

**Comment by Infixo** [comment]
Unfortunately there's another problem, I supposed existing from vanilla, because EUI has a workaround for it. Something called "silent progress removal". For reasons unknown, during first turn of the build, the game actually updates progress twice, effectively giving one turn for free.
Because of that, both dll and EUI have some additional checks and adjustments when calculating turns. Messy as hell. The final result is that with current code there's going to be always 1 turn difference between "remove+build" combo vs. remove, then build. It's because in the first case, this "free" turn is added only once, in the second situation it is added twice, because we start 2 separate build actions.

**Comment by Infixo** [comment]
Ah, one more thing. EUI does only 1 calculation, when the worker is not doing anything, just standing. In this case the functions from DLL return INT_MAX as number of turns, because... well, the worker isn't doing anything, so with rate 0 it will never be finished. 
Once you start doing anything (i.e. build action), EUI just displays data from DLL, accounting for that weird free turn error I described earlier.

**Comment by UndeadDevel** [comment]
This seems to be broken again in 8/31 (2019)...in the screenshot below you see that the Plantation gets an estimate of 8 turns even though the chopping only takes one more turn and the Plantation itself only 5 turns; in fact, the window has been showing 8 turns for the Plantation the entire time the forest was being chopped for the previous turns (turns making the estimate correct for one of those turns). The chopping time number was correct throughout, though.
This is with VP 8/31 and some UI mods, standard speed.
![Finishing_Turns](https://user-images.githubusercontent.com/30495439/64480174-8a870880-d1b2-11e9-9153-fe00f94d9999.jpg)
