### ISSUE TITLE
[Question] Must puppet cities has penalty for faith?

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4172]
_1. Mod version (i.e Date - 4/23):_
4-11

_3. Error description:_ 
In puppet city with imperialism branch I have 100% of faith + 25% modifier for puppet. Is it right or not?

![20180411205012_1](https://user-images.githubusercontent.com/13381981/38634127-52738964-3dca-11e8-8a66-5b6103bda05e.jpg)

**Comment by raphaell666** [comment]
Currently there is not a penalty for Faith output of Puppets. The current penalties are: Culture (-75%), Science (-75%), Tourism (-75%), Gold (-75%), Growth (-25%), Production (-25%), Faith (0%). The buff from the Imperialism Martial Law policy applies to all yields increasing their output by 25%. This results in the Faith modifier for puppets being +25%. 

I'm not sure if Martial Law buffing Faith output is intentional or not, I'll see what I can find in the code. Nevertheless, I'd argue Martial Law should not increase Puppet Faith output, as there is no penalty to begin with. This seems counter-intuitive at first glance.

**Comment by raphaell666** [comment]
This should be fixed in the 04/20 version, it now verifies if the penalty modifier is actually negative before applying it:
```
if (IsPuppet())
{
	int iTempMod = GC.getPUPPET_FAITH_MODIFIER() + GET_PLAYER(getOwner()).GetPuppetYieldPenaltyMod() + GET_PLAYER(getOwner()).GetPlayerTraits()->GetPuppetPenaltyReduction();
	if (iTempMod > 0)
		iTempMod = 0;
	iModifier += iTempMod;
}
```

Should work fine now I believe.
