### ISSUE TITLE
AI kills Nau Feitoria

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4174]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Look at Geneva. The Nau was settled some time ago just as they were building an improvement on the tile, and the AI keeps on making the improvement. Upon clicking next turn, Feitoria will be Gon.
[genecvaMaria I_0273 AD-1265.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1903079/genecvaMaria.I_0273.AD-1265.zip)

**Comment by cdanger341** [comment]
I've been seeing this happen for many versions now. If a CS AI worker is building an improvement and a Feitoria gets built on the tile they are working in the mean time (via Nau ability) then the Feitoria gets removed once the workers complete their improvement. Also, I have seen Feitorias disappear because a foreign Civ placed an Embassy on top of them (so rude!). It would be nice if placing a Feitoria in a CS caused active workers on the tile to be interrupted.

**Comment by Enrico-Swagolo** [comment]
Aye I've also seen that for a long time. Makes me paranoid to check where I
put the Feitoria, because... wait, does the sight provided by the UI in CS
work? It says it should be giving sight of the tile and two nearby ones,
but I don't think it does.

**Comment by cdanger341** [comment]
The sight works, and it goes away once the Feitoria is removed.
