### ISSUE TITLE
New-CS turned barbarian, liberation

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4287]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So Antanarivo is a result of revolt in France. I'm fighting France just as Antanarivo falls to barbies (turns black), and I attack and get an option to liberate. It does what advertised, meaning it's returned to France despite me fighting against France, but shouldn't it remain a CS?

**Comment by TechpriestEnginseer** [comment]
Except the bug is that is he's at war with France which he shouldn't be liberating toward France if he's fighting them (Should be no option to liberate toward his enemies then)

Another issue might also be that Antananarivo might cease to exist because of this issue to liberate toward France.

A solution might be to have two liberation option toward the Free City or toward its original owner, but I suppose that's way too much things to code now.

**Comment by LoneGazebo** [comment]
Ant should cease if liberated to France. I’ll look at why it’s offering to go to him though.
