### ISSUE TITLE
City's name turns blank, hovering over city makes it called "City of 1 (sugar icon)

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4291]
_1. Mod version (i.e Date - 4/23):_
current hotfix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I think it might be due to overlapping of hotfixes, because every time I played on a version and implement 2-3 hotfixes, cities start losing names and weird stuff occurs - this is something I've noticed. This is probably just not an exception. Every civ version if I implement one hotfix, it's usually okay - any more, and the game inevitably breaks, becoming either weird or unstable. Still, reporting in case it's not so. Bloodthirster is save with a broken city (French, my southwestern empire), logs is logs. The game also turned very, very unstable, which always happened when a city lost it's name.
[SUMMON THE BLOODTHIRSTER.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1947333/SUMMON.THE.BLOODTHIRSTER.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1947334/Logs.zip)

**Comment by Infixo** [comment]
Please don't assume that others will have the same error as you. It would much easier if you provided a screenshot instead of a puzzle to solve (i.e. which city?)
I loaded your save with 4-20-4 + my hotfix (not 4-20-5, I'm waiting for the code in GH) and I don't see any cities with problematic names.

![20180425164758_1](https://user-images.githubusercontent.com/25866684/39253625-8cd7afde-48a8-11e8-865a-f56bc02f51c0.jpg)

**Comment by Enrico-Swagolo** [comment]
It's Troyes, or was. I didn't tell you which one, because I forgot the name, and it was no longer displayed. Reloading made the bug disappear, strangely enough, and weirdnesses are gone.

**Comment by Infixo** [comment]
And that is why you should take screenshots :)
