### ISSUE TITLE
Multiplayer crash

### ISSUE THREAD

**Issue by besset** [LoneGazebo/Community-Patch-DLL#4356]
_1. Mod version (i.e Date - 4/23):_ 4/30

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  So my buddy and i have been playing 2 vox populi multiplayer games vs AI and they both desynced then crashed at around turn 100 using two different modpacks (4/30 version and the one before that) using no additonal mods just the vox populi modpack.  When we try to reload the game it crashes after having loaded. We were able to play multiplayer a few vox populi versions back (with just a lot of desyncs sometimes but never any crashes).

_4. Steps to reproduce (optional):_

[files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1981371/files.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by raphaell666** [comment]
From my experience crashes are probably not directly related nor due to multiplayer, most likely these crashes are caused by UI issues or something else.

Desyncs are an issue specific to multiplayer. As far as I know they should not directly cause crashes, however. Desyncs cause resyncs (game reloading).  In addition. the most recent version (30/April) should be considerably more stable (less desyncs) than previous versions, as several multiplayer fixes and desync-prevention measures were incorporated.

Can you upload the modpack that you used? I want to take a look at it and try loading your save to see what is up. The logs seem to be fairly incomplete, perhaps you did not have full logging enabled? Do you have access to logs from the other computers as well?

**Comment by besset** [comment]
http://dump.bitcheese.net/files/zypedas/MP_MODSPACK.7z/preview was the link from vox populi forums, no additional mods and its based on the 30/4 version. Tho it has no UI_bc1 folder, maybe i have an old version of UI_bc1?

**Comment by raphaell666** [comment]
>Tho it has no UI_bc1 folder, maybe i have an old version of UI_bc1?

Sounds likely. This is the latest version (4-30-4) of the EUI folder: [UI_bc1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1987660/UI_bc1.zip)
