### ISSUE TITLE
Future tech

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#4371]
_1. Mod version (i.e Date - 4/23):_

4/30

_2. Mod list (if using Vox Populi only, leave blank):_

-

_3. Error description:_ 

I research future tech every turn (whereas the techs befor took 14 turns each. Also, I get to aknowledge the tech several times each turn, and my happiness goes up ~100 each turn.
[Happy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1993911/Happy.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Probably because you are overflowing into it over and over again.

**Comment by LoneGazebo** [comment]
I'm not sure TBH - for me, future tech is more expensive than prior techs.

**Comment by Infixo** [comment]
The problem here is the calculation of the research cost in CvPlayer::GetResearchCost() which in some point goes beyond the range of 32-bit integers due to additional x100 applied in the routine. Somebody tried to counter that by adding a check if(iResearchCost >= MAX_INT) but this check will never work as no (signed) integer can be bigger than MAX_INT (defined as 0x7fffffff) in 32-bit environment.
In this particular game we there's 55 cities that increase tech cost each by 5%. Base cost is 58500 but before going into cities multiplier it is multiplied by 100. Then 5850000 * (100+275) gives a number that is negative when using 32-bit integers. Eventually the routine returns -210120. Since any research progress is bigger than required this tech gets "finished" every turn and so on.
The correct number should be 219375 and it should take 16 turns to finish it. The tooltip from TopPanel actually calculates and shows that correctly by its own.

**Comment by Infixo** [comment]
There's also another bug (?) in the routine which could be a root couse of the problem.
Each civ that knows a specific tech decreases the cost of this tech. It is linear based on num of civs in the game, up to 20%. So, one would assume that if a tech costs e.g. 1000 and 5/10 civs know it, the bonus would be 10% and the tech would cost 900. Nope. It costs 909 because the math used here is not 1000 * 0.9 but 1000 / 1.1. This is also the place where additional x100 modifier is added probably to counter rounding errors of that division.

**Comment by LoneGazebo** [comment]
That’s some weird code. Good sleuthing!
