### ISSUE TITLE
happiness observation

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4469]
AI test game with 6/1. prince, fwiw

![image](https://user-images.githubusercontent.com/1358966/41308965-9d89b188-6e7d-11e8-8008-3771cacb3c2c.png)

i know it doesn't include any of your latest happiness changes, but basically everybody swimming in happiness right now.

i'm starting to wonder if we should treat happiness as a zero-sum game ... so everything is relative, one player's happiness must be offset by somebody else's unhappiness? wouldn't know how to enforce that though.

the global median system is already a step in the that direction - not everybody can be better than average - but with all the modifiers, it doesn't work out apparently.

**Comment by MoiMagnus** [comment]
One of the critic of this system is that when playing in MP, if one of the player is significantly better than the other, he will put the other into unhappiness spiral without even wanting to do so.

(And it is not fun for a player to be confronted to unreasonable unhappiness just because the other are doing too well)

Moreover, the AI only seems to swim into happiness once ideologies are reached. The state of unhappiness around 1800AD seems reasonable.

(And if I remember correctly, the main critic of previous system was that the era before ideology was very though in term of happiness, so I'm glad to see it is more reasonable here)

**Comment by ilteroi** [comment]
well it might actually be an interesting strategy to try and make your neighbors jealous of your excellent yields. but too late to explore that now :)
