### ISSUE TITLE
Khan heals as Vanilla instead of as BNW

### ISSUE THREAD

**Issue by furkhail** [LoneGazebo/Community-Patch-DLL#449]
In Vanilla civ the Khan healed +2hp but in G&K and BNW healed +15hp. Here is healing +2hp

**Comment by LoneGazebo** [comment]
I'll make it +5, so +20 total.

G

**Comment by furkhail** [comment]
If you feel that that is balanced by all means, but it is 1/3 of his intended purpose right?

**Comment by LoneGazebo** [comment]
The tooltip is misleading you. The bonus from the khan's unique medic promotion is in addition to whatever bonus he gets from the other medic promotion he already has.
G

**Comment by furkhail** [comment]
Which is not working then. Either if it is for his own bonus or for a diff promotion it was intended to heal additional 15hp. That is what it says the civilopedia. "Additional". Unless when you say "+20 total" you wasn't talking about the 15 from own territory as a base. But any way. Adjust what you feel right. It is better trying in game anyways :D

**Comment by LoneGazebo** [comment]
I'm telling you, looking at the XML and the DLL it is plainly clear that Firaxis's goal was to make the Khan boost healing over the medic promotion by +2. Their tooltip is just really poor at explaining that.

**Comment by furkhail** [comment]
Man, you made me open up a game with Mongolia to try it. First game without CBP since I found it. 25hp healed next to a Khan outside friendly territory. 

Maybe you just saw the code from Vanilla. It got changed in G&K. There is no +2 anywhere, unless you are saying that the medic promotion gives +13hp haahahah. There is no other way to look at it. If you don't believe me, open up a game. :dancers:

**Comment by Radost** [comment]
Didn't you know the numbers you see in the game are WRONG, only the code is right?

**Comment by LoneGazebo** [comment]
I'll take another look at it – my look at the DLL was cursory.

@ radost: what I don't think you understand is that the LUA and the DLL are not always in perfect sync. So yeah, in many cases the numbers that appear in the UI ARE incorrect because of how the language is interpreted from DLL -> LUA hooks -> LUA -> game interface -> user.

**Comment by furkhail** [comment]
G, I checked the health of the unit, before and after. I checked the number sprouting from the unit as it healed. I checked outside and inside friendly territory.

The tooltip says something and the game does exactly that.

Did you ever hear about Occam's Razor? haha :dancer: 

Btw, "looking at the XML and the DLL it is plainly clear" this is not ok to say when "my look at the DLL was cursory". No matter how you look at it.

**Comment by LoneGazebo** [comment]
It is okay to say when it is precisely what I intended. Like I said, I went into the XML, found the value I needed, and I traced it to its origination point in the DLL. It is 'plainly clear' that the XML is passing into the DLL correctly at the origination point, which is where my investigation stopped, as I have not messed with the unitcode for that particular function (but perhaps ilteroi has). So yeah, this is 'cursory,' as it doesn't involve any hooks or stack tracing, but it is accurate to my statement.

Now, what is NOT clear, and what I now need to do, is trace the stack up through to the LUA and interface to see if it is being modified somewhere along the way. This is something wholly different from my original effort, and takes much more time, which is why I haven't done it yet.

I'm not in the habit of lying or falsifying my efforts. If I say something, I mean it.
G

**Comment by furkhail** [comment]
Ok, I apologize if I offended you, but you should acknowledge that the whole "I'm telling you" is not the way. It seems dismissive. We all are pretty grateful to you for this mod, but one thing doesn't grant the other. We weren't talking about an obscure weighing rating, either it heals 2hp or it heals 15hp. One look ingame. All that it takes.

Also, I never said that you lied. Neither I imply it.

**Comment by LoneGazebo** [comment]
No worries, not angry at all. It is difficult to illustrate the debugging process of stuff like this without getting into the nitty-gritty of the DLL and all the language included therein. "I'm telling you," is a crude attempt by me to hand-wave this detail-heavy process (especially when I'm on a mobile device, which is all-too-common these days), which may not be what you or others want. Sorry about that. In any case, I'm going to trace the issue and see if I can figure it out.

**Comment by furkhail** [comment]
Glad to hear. If it is of any help, just remember that the Khan did in Vanilla exactly what is doing in CBP. It got changed at G&K. Maybe something changed in CBP is voiding the G&K change over the original Khan.

**Comment by LoneGazebo** [comment]
I found the bug - there's a line of code that overwrites the khan's promotion because he's not technically a combat unit, thus lowering the value. It wasn't where I thought it'd be.

G

**Comment by furkhail** [comment]
If I can give you a little advice. Never trust code. Never, ever. It doesn't matter what you think it does. You wouldn't believe the shit fixes we do in the business in order to release something on time. The only thing that matters is what it does. Saying the code does X is meaningless unless you did all the app and have a perfect memory. And even then... Meh. ;) The testers exists for a reason.

**Comment by LoneGazebo** [comment]
Well, it isn't so much a matter of 'trusting the code' as it is not having written all of it myself - the spaghetti code of the DLL obfuscates whatever attempts at logic exist on my end. I don't trust it at all, but when I look where something should be (from my mobile device, no less) and it is there, that's pretty much all I can do at that point until I get further along.

It also doesn't help that many (the majority) of issues I'm given are red herrings that are related to mod conflicts. :-1: 

I've bumped the khan's bonus up so that it'll override the conflicted value - should heal +10 to self, self plot, and adjacent plots regardless of location.

G

**Comment by LoneGazebo** [comment]
Also, sounds like you do code-work yourself. If so, are you holding your skill set out on us? :)

**Comment by LoneGazebo** [comment]
Fixed. I think. We'll see.

**Comment by furkhail** [comment]
I do. Android mostly. But I can work with pretty much any language that is not brainfuck-like. If I can help in any way lets talk.

**Comment by LoneGazebo** [comment]
Well, we're looking at C++ for Civ 5 - it is a pretty straightforward language (I took some courses in college about 10 years ago for fun, and then I've simply taught myself the rest since then.) I'm  historian by day, so if I can (kind of) figure this stuff out autodidactically, I'm sure anyone can.

Any particular element of Civ you are interested in working on?
G

**Comment by furkhail** [comment]
Whatever you need help with. Maybe map generation? I don't know.
