### ISSUE TITLE
Crash when trying to load game

### ISSUE THREAD

**Issue by m4ti140** [LoneGazebo/Community-Patch-DLL#4491]
1. Mod version: 5/20

2. Mod list:
Vox Populi: Patch+Balance+EUI+43 civs (1,2,3,4,5,6c) - could it be due to civ number?
City Limits v7
Faster Aircraft Animations v3
Gibraltar, Reef and Krakatoa fixes v101
Improved Air Recon v1
Improvement - Airbases v14 - with the fixed xml
Improvement - Tunnel v5
Ingame Editor v39 - disabling didn't help
Lake Victoria fix v2
Mechanized Infantry with Soldiers, Resized v2
Promotions - Flagship v2
Thal's FlagPromotions - non EUI version, but disabling didn't help

3. Error description:
Game crashes when trying to load a saved game. Very early saves load fine, but 90+ fail to load. In particular I have a turn 212 I'm trying to salvage, can't do anything.

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2112791/CvMiniDump.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2112792/Logs.zip)
[Bismarck_0212 AD-0580.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2112800/Bismarck_0212.AD-0580.zip)

**Comment by MoiMagnus** [comment]
In mod installer log, I see 

> [185022.187] ERR: There was an error installing the mod. (F:\AppDataCache\Local\Temp\Civ5ModInstaller\Krakatoa Fix (v 100).modinfo)

(The slower research mod also fail to install correctly because "%" is not allowed in the name, but it is not enabled here, so it is probably not the problem)

Another error is:

> [184849.953] Validating UnitGameplay2DScripts
[184849.953] Missing Entry for UNIT_BARBARIAN_HORSEMAN
[184849.953] **** VALIDATION FAILED *****

Not sure what to think about this one.

I don't have the tool to open the CvMiniDump, so I can't see what is the cause of the crash.

**Comment by TechpriestEnginseer** [comment]
````
[184849.953] Validating UnitGameplay2DScripts
[184849.953] Missing Entry for UNIT_BARBARIAN_HORSEMAN
[184849.953] **** VALIDATION FAILED *****
````
Common mistake doesn't really matter.
