### ISSUE TITLE
Lakes only producing 2 food (possibly goddess of purity related?)

### ISSUE THREAD

**Issue by vide0gamer** [LoneGazebo/Community-Patch-DLL#4504]
_1. Mod version (i.e Date - 4/23):_
6/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2130466/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0042 BC-2320.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2130465/AutoSave_0042.BC-2320.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![civ5lake](https://user-images.githubusercontent.com/28330477/41816021-7f404204-7748-11e8-9d6e-a6e49015f79c.png)

**Comment by vide0gamer** [comment]
The map shows the correct yields, but it only shows me producing a total of 12 food in this situation

**Comment by kawyua** [comment]
I would like to open this issue up because I believe this is related. 

I'm pretty sure the lakes were giving the correct yields, but AFTER loading the game the yields are NOT calculated correctly. (loading games are very bad):

_1. Mod version (i.e Date - 4/23):_
7/15

_2. Mod list (if using Vox Populi only, leave blank):_


_3. Error description:_ 
So everything is okay when playing the game normally, but loading the game messes up the food yields such that lakes are only 2 food and cities are 2 food 1 production 1 gold

_4. Steps to reproduce (optional):_
play a civ that starts next to a river

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2216892/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2216893/auto.zip)


3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![beforeloadingandpreviousturnhuns](https://user-images.githubusercontent.com/12496046/43044542-cbc6b5f2-8d75-11e8-8c29-92bcb5784af6.PNG)
![beforeloadingandcurrentturnhuns](https://user-images.githubusercontent.com/12496046/43044543-cd98a6b0-8d75-11e8-8b4d-45381c14566a.PNG)
Now notice in the next picture in the same turn I have 1 more gold and food count is 4 when it should be 5
![afterloadingandcurrentturnhunslocking wheat](https://user-images.githubusercontent.com/12496046/43044545-d00cebfe-8d75-11e8-99a5-fef27059b1e5.PNG)
Here notice that I have 1 less production, 1 more gold, and food count is 4 when it should be 6
![afterloadingandcurrentturnhunslockinglake](https://user-images.githubusercontent.com/12496046/43044546-d15fd3a4-8d75-11e8-850c-3050afe35846.PNG)
![afterloadingandnextturnhunslockinglake](https://user-images.githubusercontent.com/12496046/43044548-d28f487c-8d75-11e8-95c3-cf7bc6809948.PNG)

**Comment by Adonis-VII** [comment]
1. Mod version:
7/15 (Modpack)

2. Mod list:

3. Error description: Lakes show 3F1P on map, but only give 2F1P to the City

4. Steps to reproduce (optional):
Create bug:
1) Start new Game
2) Found city by lake turn 1 (yields correct)
3) Save game & Exit
4) Load game (yields incorrect)

Fix bug:
5) Load game with IGE installed (yields incorrect)
6) Open & Close IGE (yields corrected)

@LoneGazebo Another weird bug I can confirm. I've uploaded modpack + save to dropbox, as zip was too big for github. I'm assuming this is a caching issue as toggling IGE corrects the yields.

https://www.dropbox.com/s/4jr0dkn80odxyzy/Reload%20Game%20Lake%20Yield%20Issue.zip?dl=0

**Comment by Iamblichos** [comment]
@ilteroi I think this is a fresh water cache issue on load.

**Comment by ilteroi** [comment]
fixed
