### ISSUE TITLE
tech progression

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4505]
compare this:

![image](https://user-images.githubusercontent.com/1358966/41818429-5f3427a2-77af-11e8-8d61-b8104a6a963c.png)

and this:

![image](https://user-images.githubusercontent.com/1358966/41818436-7f7cabba-77af-11e8-88b7-dd58f2a04636.png)

how is it possible that greece has a much higher science output than everybody else yet no real tech lead?

picture for culture/policies is similar btw.

**Comment by Cozzolino92** [comment]
Founded/Annexed a lot of cities?

**Comment by ilteroi** [comment]
nope. a lot of puppets for sure but their science lead comes mainly from the scholarship belief and big cities

**Comment by LoneGazebo** [comment]
espionage, maybe?

**Comment by ilteroi** [comment]
hmm. tech costs are rising over time, so it's hard to estimate how large the greek tech lead should be. unfortunately i don't have the logs to check how many techs have been stolen.

anyway i think we can conclude that a high science output doesn't necessarily pay off ... which is a bit disappointing.

**Comment by tu-79** [comment]
If Greece has roughly the same number of cities than the others (which is difficult to accept, seen how raw science diminishes for many civs, what can be caused by lack of gold or lost cities), they could be using fewer great scientists. Instant science does not show up in InfoAddict, does it?

The tech lead is there. The question is how Poland managed to catch up. Trade routes or spies? Step forward sounds likely.
