### ISSUE TITLE
AI Immediately Wars and Makes Peace Under Vassalage

### ISSUE THREAD

**Issue by austin-wangyu** [LoneGazebo/Community-Patch-DLL#4596]
_1. Mod version (i.e Date - 4/23):_ 5-20-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/22928672/43249666-220640b6-9070-11e8-9d0f-86de7ee21adb.png)
King difficulty, marathon speed. Assyria is my vassal, India is nearby. For the past several turns the little newsfeed displays that "Gandhi has declared war on Ashurbanipal!" and immediately after that "Gandhi has made peace with Ashurbanipal!" 

I assume it has something to do with him being my vassal but I thought I was supposed to protect vassals from attacks or something and they could war independently of me? Is this normal?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by JanSobus** [comment]
I had this problem in my games as well, cannot dig a save at the moment though. The problem occurs if you have a war with a major civ, sign peace and during peace treaty they vassalize another civ. Then, you can start war with the vassal on your turn but it will stop on the turn of the master since you have a peace treaty. Some additional check (have a master)&&(peace with master) before giving option to declare war on the civ would solve this I believe

**Comment by bigcat88** [comment]
In my game I see the same issue.
