### ISSUE TITLE
Need reducing buildings less potent than in description

### ISSUE THREAD

**Issue by JanSobus** [LoneGazebo/Community-Patch-DLL#4617]
_1. Mod version (i.e Date - 4/23): 7/15

_2. Mod list (if using Vox Populi only, leave blank):VP+Flag Promotions+3&4UC for VP

_3. Error description: Buildings like library, circus, university etc provide only a fraction of needs reduction showed by their description (more like 5% instead of 50% in case of university). Very hard to keep up with happiness, especially as India

_4. Steps to reproduce (optional): See save, screenshots
[needs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2261703/needs.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
The % modifier is a modifier to the algorithm, not a flat % modifier. It’s working as designed.

**Comment by TechpriestEnginseer** [comment]
The tooltip already addresses this. When you hover over a building that reduce its need it will show you the now need and after need.

**Comment by JanSobus** [comment]
I know. As per screenshot, my point is that having "culture need decreased by 25%" directly followed by "old need 1.21 , new need 1.19" is not exactly intuitive for someone who doesn't know exact formula sitting behind the numbers.
![needs1_cr](https://user-images.githubusercontent.com/17416468/43754877-65418770-9a50-11e8-83c9-26f132b76310.png)

**Comment by Zarggg** [comment]
To be fair, the player doesn't *need* to know the formula behind the calculation, only the end result.

**Comment by TechpriestEnginseer** [comment]
Not to mention the value serves as a tool of estimation among modmods and help mod modder understand the impact of the unhappiness reduction. The formula behind the calculation as far as I remembered was

- Add every city's yield/turn in each separate certain yield category (Science, Culture, Gold, etc, but we will do gold in this instance).
- Use the gold yield to divide by the global population of the world (even those unmet, but not including minors).
- This gives us the average gold/turn per citizen regardless of affiliation. Seem simple enough?
- We put this average global yield into finding a "middle ground" function (we don't want behind-civ cities to be super-punished for neglecting infrastructure, while at the same time we want to punish ahead-civ cities who neglect their infrastructure)
- Now, this middle ground yield is now taken to your citizens.
- Now the citizens begin looking at their potential worth {([known technologies * something] - somethingelse) / possible technologies} These something and somethingelse keep constantly changing due to balance changes. Note that knowing technology is not researched technology. As long as you meet a civilization with that technology. It counts as a known technology.
- Now seeing their potential worth and taking their **middle ground yield value** to combine(forgot if it was additively or multiplicative) with it, they'll compare it to their own city's gold output divided by their the city's total citizens. Now 1 of 2 outcomes happen:
- Poverty is a myth.
- Poverty exist in 8 out of 9 citizens today. We need to protest!

And that's the formula. Where does the reduction come into effect? Into the bolded text. Now how do these bonuses stack? I would assume multiplicatively, but I could be wrong since this information was gathered years ago.
