### ISSUE TITLE
Supply doesn't work properly

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4620]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Several things don't provide proper supply, including all the buildings, Citadels (and likely great admirals) and wonders, or so they say on civfanatics

**Comment by pandasnail** [comment]
Here's a screenshot and save of a test game where a conscripted unit takes supply. I included the lua log even tho I saw nothing weird in it. Should add that I used FT quite a bit to set this up, but this happened in the real game too.

Also the barracks Marrakech is building did give supply when finished, so that seems to working for me. But in my real game, when I conquered (and chose annex) an AI capital, my supply instantly went down three. That's not supposed to happen, is it?

![civ5screen0007](https://user-images.githubusercontent.com/16260521/43792987-38496ccc-9a48-11e8-8c32-3fedf16b3920.jpg)

[supply.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2267472/supply.zip)

**Comment by Rafs041** [comment]
Though I'd add my own log + screenshots. Neither citadels nor teracotta army are giving supplies.
Aside from the base mod I'm using events and decisions by sukritact and 3rd and 4th Unique Components for VP by pineappledan and the rest of the team.

![20180808084628_1](https://user-images.githubusercontent.com/19327087/43822049-42603440-9aeb-11e8-8459-677d7eeb976f.jpg)
![20180808084634_1](https://user-images.githubusercontent.com/19327087/43822050-427a3836-9aeb-11e8-9539-61b10aae2dd4.jpg)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2269279/Logs.zip)

**Comment by tu-79** [comment]
I used a great general for a citadel and my supply went from 15 to 17 in a few seconds. But it really goes down with new techs, so it was back to 15 in some turns, and dropping to 13 next era. I was not expanding.

**Comment by RockettSJ** [comment]
Can confirm in my own game. 11 cities, medieval era, all with barracks/walls. Only 17 supply cap, and -27 from tech level. A little too low in my opinion.

**Comment by BorussiaVox** [comment]
Supply is extremely low in my games. The buildings and wonders seem to have no effect.

**Comment by Enrico-Swagolo** [comment]
Agreed, extremely low supply here. I have Barracks/Walls almost everywhere and have 17 supply. As I'm Authority, 11 (ok, 9 cuz puppets) are garrisons. How am I meant to warmonger with such a small squad? Armories might fix it, but at least Walls do nothing.

**Comment by Sasha-alTherin** [comment]
Version:
Using beta 8.6.1 - fresh game

Mods:
Aside from Full VP with EUI using Wonder Race mod from Steam Workshop

Description:
I'm at 15/15 supply. In war with Ethopia.  I have 9 built cities. Capital is at constant growth now, other cities pop lock at 4 while working on their infrastructure.  Just built two barracks back to back without earning new tech and supply did not raise at all. Barracks state that they provide ONE full supply.  Walls which I built didn't seem to do anything either.  But I don't expect a 10% increase to be noticeable until a single town can supply 10 by itself

**Comment by rudpes** [comment]
I can confirm: in 2 games I had Terracotta, Great Wall and 1 Citadel with 7 cities: by early Medieval supply falls below 20, with a lot of handicap from Techs

**Comment by ColonelCarter** [comment]
I think that the supply reduction from tech level might be increasing based on the "supply from cities" as well as the "supply from population". Gazebo said that supply was supposed to increase less from number of cities, but "supply from cities" seems to include stuff like the XP buildings, citadels/admirals, and wonders with flat supply.
I've attached a screenshot from mid-renaissance, it lists 38 from owned cities:
10 cities + 9 barracks + 9 armories + 3 Terracotta + 5 Himeji + 2 from a Citadel = 38; everything is accounted for.
But then i have -68 from tech level with 34 technologies. I can't remember what supply reduction from tech level was like before, but I don't think it was that high for 117 population with 34 techs.
Maybe my population is too low, but I was hampered in growth early trying to have enough units to take Babylon. I only had 8 supply at that time because I stole Terracotta from him and was working on Himeji to help get my production and growth back.
![8-6_supply](https://user-images.githubusercontent.com/42220044/43860919-d2850e22-9b1a-11e8-96c7-993a1c09cb0c.jpg)
