### ISSUE TITLE
Vassal attacked

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4902]
_1. Mod version (i.e Date - 4/23):_ 11-9

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Not sure if a bug. If not, a clarification would be much appreciated.

I'm Babylon, Songhai is my vassal (capitulated). My neighbor is Russia with whom I've got very good relations, defensive pact and declaration of friendship.

All of a sudden Russia declares war on Songhai. Ok, that's weird. What's more weird is that I'm not at war despite the fact that my vassal is attacked by another civ, and my relations with Russia are still wonderful: we are friends and have defensive pact.

**Comment by LoneGazebo** [comment]
How recently was Songhai vassalized? My guess is that, if recent, there was a 'coop war' with another party that wasn't properly reset.

**Comment by UndeadDevel** [comment]
I don't want to make a separate issue for this, but I just want to add some evidence since I don't think it's all coop-war related:

I'm using version 30-11-18 (21-11-18 with all hotfixes) and I've seen civilizations DOWing on Vassals multiple times now, including on my long time vassals (>75 turns of vassalage) that last only one turn and don't drag me into the war; the next turn the war always ended abruptly.
