### ISSUE TITLE
Ice Breakers (?) allows movement through mountains

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#5003]
_1. Mod version (i.e Date - 4/23):_
11-21-1-3

_3. Error description:_ 
I am fairly positive that Ice Breakers allows Workers and Archaeologists to traverse through mountains, and Workers to build roads on those mountains.  Other civilian units still can't traverse mountains, and Icebreakers is the only promotion that affects exactly these two civilian units.
![image](https://user-images.githubusercontent.com/34615525/50058667-b4426000-0149-11e9-843e-88d5a80bff11.png)

I think that this a great, if unexpected ability to unlock (how did governments build roads through the Rockies?), but the tooltip should be updated to let people know.

**Comment by TechpriestEnginseer** [comment]
afaik any other units can travel on a mountain as long as it has a road or railroad built on top of it(to prevent an inca player suddenly chokeholding you...

I think I know why.

![image](https://user-images.githubusercontent.com/13937047/50455956-10ee0980-0906-11e9-9120-9cda0a88f1e7.png)
Technically CanPassImpassable is given to Air Units which means air units can fly above mountains, etc while in vanilla they couldn't pass over ice because they'd be embarked thus losing the property. So Workers can technically traverse mountains...

I'll make a poll to see how people feel about this.

**Comment by TechpriestEnginseer** [comment]
Polling Passed. Ice Breakers will be renamed to Traverser.
