### ISSUE TITLE
Quinquereme travels to a space and explores but cannot return to origin

### ISSUE THREAD

**Issue by ryanmusante** [LoneGazebo/Community-Patch-DLL#5011]
_1. Mod version (i.e Date - 4/23):_
12-18

_2. Mod list (if using Vox Populi only, leave blank):_
  AI - No CS Annexers,
  Diplomacy - Auto-Denounce,
  Global - Commander Influence Borders,
  Global - Local Generals,
  Global - No Ocean Plundering,
  Global - Pro-rata Buildings Purchase,
  Global - Religious Settlers,
  Units - No Mechs,
  Units - Subs Immune Under Ice,
  Units - Visible Trade Units,
  Tectonic Map Script
And many UI Mods

_3. Error description:_ 
Quinquereme travels to the southeast which I had believed was by jumping across the coast tile pictured to the coast tile below. Yet, it cannot travel back to its origin, how is this possible? 

---------------------------
Supporting information:
![quinquereme](https://user-images.githubusercontent.com/26808646/50359985-f16f7d80-05a1-11e9-8e83-6102800f6b1d.png)

**Comment by TechpriestEnginseer** [comment]
![image](https://user-images.githubusercontent.com/13937047/50361089-38fcf780-0517-11e9-9137-77936395e398.png)

**Comment by MoiMagnus** [comment]
You need a line of sight on the target tile to go back. The rule is the same as the rule for going trough ennemy units, land or sea. Since you can't stop you movement on a unit, you have to know that the target tile is empty before starting the movement.

For example, if you get any land unit on the incense, you will be able to go back. Not sure how you first manage to pass this deep see without units on the other side to see the target tile.

**Comment by ryanmusante** [comment]
Confirmed. Apparently a friendly/neutral unit was in proximity when I initially moved to the opposite square. I forgot about the line of sight rule.
