### ISSUE TITLE
unit gift sanity

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5029]
here we have 4 corvettes and 1 frigate in an inland sea.

![image](https://user-images.githubusercontent.com/1358966/50524790-071c0000-0ad8-11e9-83cb-e9798bc21fa0.png)

doesn't make much sense to have (melee) ships if there are no enemy cities on the body of water ... so how can this happen?

we do have checks in place for the AI and they mostly seem to work - i found only one ship ever being built:

142, Germany, Berlin, POST: Building, East India Company, 12280, 1
142, Germany, Berlin, POST: Unit, Trireme, 10040, 2
142, Germany, Berlin, POST: Building, Herbalist, 5521, 2
[...]
142, Germany, Berlin, SEED: 717075332592967006, CHOSEN: Trireme, Do not rush, TURNS: 2

and they probably never even finished it. next turn:
143, Germany, Berlin, SEED: 16879120493671848816, CHOSEN: Borobudur, Do not rush, TURNS: 3

(in general i see a lot of turn-by-turn switching between different build orders ... is that by design? i can't even tell why and when build orders are due to be reconsidered. but that's a different issue)

so i guess those units were gifts from CS allies. can we extend the sanity checks to gifts?

**Comment by UndeadDevel** [comment]
Just to add to your observation about build order switching: in my current game (version 30-11-18) I check my spies almost every turn and I see the AI switching buildings extremely often, even World Wonders, which has allowed me to actually snatch some from them. Units less so, it seems, though it churns those out pretty fast so that may be why I see it less with units.

I can't exactly remember whether this was similar in earlier versions but I simply assumed it was due to me playing on Emperor, where the AI is supposed to generate a list of possibilities and then randomly choose from the top 2 and I thought that it just does this every turn instead of finishing the build order first.
