### ISSUE TITLE
Caravan won't use my road

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#5424]
_1. Mod version (i.e Date - 4/23):_
6-2

_2. Mod list (if using Vox Populi only, leave blank):_
Improved city view
Filters in traderoutes
Calypso's colored religion
city-states leaders v.10

_3. Error description:_ 
I built this long road from Athens to Mycenae, for my caravan to use while travling to Jerusalem to the north of the city - but it simply refuse to use it. I now have one tile left on the road to Jerusalem (see worker top left corner), and has built/building an extra short cut road, going out to the left of Athens, but still the caravan insists on travling next to the river when I try to set up this "new" route.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/59156194-750d2000-8a97-11e9-8b15-ea68a134b988.png)

[CARAVAN.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3269315/CARAVAN.zip)

**Comment by LessRekkless** [comment]
Even if the road wasn't there, the shortest route looks like it should be in the left side side of the river. There are fewer tiles to pass through and only one tile cost extra movement compared to the 5 tiles that it is currently passing through. Both routes have only one river crossing.

**Comment by LoneGazebo** [comment]
@ilteroi worth a look re: river code?

**Comment by psparky** [comment]
I've noted before that mixed connections of road and rails (between a pair of cities) don't seem to get any priority when the path of a trade route is chosen. I thought that was intended to prevent a strategy of only upgrading roads under villages and towns. If any of those workers are now building railroads that might explain what is happening here.

**Comment by ilteroi** [comment]
interesting. the code for movement cost is quite simple actually.

two consecutive railroad tiles: 1/6
two consecutive road tiles: 1/4
two consecutive river tiles: 1/2 (no crossing)

switching between road and rail is normal cost. this may be an unintended feature or not.
rough terrain only costs extra if movement is not accerated.

but all this doesn't explain the observed behavior. i'll keep an eye on it ...

**Comment by LessRekkless** [comment]
> interesting. the code for movement cost is quite simple actually.
> 
> two consecutive railroad tiles: 1/6
> two consecutive road tiles: 1/4
> two consecutive river tiles: 1/2 (no crossing)
> 
> switching between road and rail is normal cost. this may be an unintended feature or not.
> rough terrain only costs extra if movement is not accerated.
> 
> but all this doesn't explain the observed behavior. i'll keep an eye on it ...

implications:
- two consecutive river tiles ignore terrain like a road would
- researching Railroads immediately upgrades the tile underneath a city, meaning that a city goes back to being two movement to enter and one+terrain to leave, and consumes all movement if crossing a river at a railroad/road transition.
- improved road and railroad techs have no bearing on trade routes

This would explain quite a bit. In this case, the current trade route path takes 5 turns, my suggested route takes 5 turns, and the road takes 5 turns. 

How does the trade route prioritize between two potential routes taking an equal number of turns? The route with the fewest tiles between source and destination? Should it be prioritizing something else, like maximizing the number of roads it passes through?

For the road: there is a river crossing from Mycenae with a road/railroad transition, and also a road/railroad transition in the hills; each end the trade route's movement. The railroad/road transition from Athens onto the road doesn't hinder the route, but only because the hill with the worker on it is a road/railroad transition.

If NewFellow's desired route had been 100% road, then it would have only taken 3 turns (he's currently lacking a road on the deer next to Jerusalem). Adding a road to the deer next to Jerusalem, would reduce the route by 1 turn.
His cities automatically upgrading to railroads cost the desired route 1 turn. The railroad under the worker near Mycenae cost one turn.

**Comment by ilteroi** [comment]
yeah i will change it so that mixed road/rail also gives a speedup. still don't understand why the route isn't on the other side of the river though

**Comment by LessRekkless** [comment]
How do you break ties? Both routes take the same number of turns and take the same number of tiles.

**Comment by MoiMagnus** [comment]
> Still don't understand why the route isn't on the other side of the river though.
> Both routes take the same number of turns and take the same number of tiles.

(I will assume there is no road/railroad on the tile just south to Jerusalem, as I don't manage to see what is there)

The north path is:
River Athens (0) -> 9 River (9 x 1/2) -> River Road (1/2) -> Road (1/4) -> Forest (2) -> Jerusalem (1)
So 8.25

The "intuitive" south path is:
Railroad Athens (0) -> 2 Railroads (2 x 1/6) -> Road Hill (2) -> 6 Roads (6 x 1/4) -> Railroad Hill (2) -> Railroad and Railroad Mycenae (2 x 1/6) -> Forest Road (2) -> Road (1/4) -> Forest (2) -> Jerusalem (1)
So 11.33

A better south path is:
River Athens (0) -> River Road (1/2) -> 7 Road (7 x 1/4) -> Railroad Hill (2) -> Railroad and Railroad Mycenae (2 x 1/6) -> Forest Road (2) -> Road (1/4) -> Forest (2) -> Jerusalem (1)
So 10.08

=> **North is the best**

The responsible here are railroad -> road changes on a forest or hill, which cost 2 instead of 1/4.

**Comment by ilteroi** [comment]
re tiebreaking etc: turns do not matter here, it's only about the "path cost". each tile has a base cost of 120, and all modifiers are applied to that number. so it's all integer math, no floating point rounding problems that way.

**Comment by LessRekkless** [comment]
How much does it cost a river?

**Comment by ilteroi** [comment]
normal cost, ie 120 - unless there is a road

**Comment by LessRekkless** [comment]
- moving along a river is 1/2
- moving across the river is 1
- moving across a river into forest is 2 (?)
- moving across a river with roads on either side is 1/4?

**Comment by ilteroi** [comment]
moving into rough terrain without a route is 3/2

so how does the modified code perform in the latest version? did anybody observe unexpected behavior?

**Comment by ilteroi** [comment]
seems to be ok apparently
