### ISSUE TITLE
AI doesn't flee from Zeppelin or shoot back

### ISSUE THREAD

**Issue by TheRealAyCe** [LoneGazebo/Community-Patch-DLL#5461]
_1. Mod version (i.e Date - 4/23):_
Vox Populi (6-12).exe

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Only once the unit was almost dead did the AI attempt to flee... towards my city. Before that the ship just stood there for 3 turns, happily being bombed by my zeppelin without retaliating or moving away (Zeppelins cannot shoot in deep water, so moving one tile would have sufficed). This was far away from any cities the AI had.

![doesntflee](https://user-images.githubusercontent.com/11407231/59983283-0d6ddd80-961e-11e9-9df1-feda4c8010b1.jpg)

**Comment by ilteroi** [comment]
need to reproduce. probably attacking was net negative, so the caravel is taking a defensive position until it got too dangerous. AI doesn't differentiate between danger from melee (where the enemy has a limited amount of attacks because of self damage) and danger from ranged (where the enemy will eventually always kill you). as for fleeing in the wrong direction, no idea.
