### ISSUE TITLE
Local Unhappiness Weird Numbers

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5545]
_1. Mod version (i.e Date - 4/23): 7/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

As you can see in the screenshots, local unhappiness for boredom is **0** even though the [actual number] - [reduced] is bigger. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/62832135-b0140700-bc32-11e9-99e7-b15001da4963.jpg)
![Civ5Screen0003](https://user-images.githubusercontent.com/49090452/62832136-b1453400-bc32-11e9-81e4-7bb8c5d16f54.png)

**Comment by bentakacs** [comment]
That's because local Unhappiness follows a hierarchy (the order is the same as shown in the tooltip from top to bottom, as far as I know). If you count the Unhappiness numbers before (= above) Boredom you'll see that their sum is the same as the Population of that City (and Cities can't have more Unhappiness than their Population).

So briefly speaking, you "have" those Unhappinesses from Boredom it's just "hidden", because your citizens have bigger concerns (distress, poverty, etc.).  If let's say the City grows, and / or you can reduce the Unhappiness above the hierarchy, you can / will get Unhappiness from Boredom. 

I hope I made things bit clearer, feel free to ask if you have some questions left! :)

**Comment by Aqinu** [comment]
@bentakacs, first of all thanks for the clarification, I didn't know that this is the case and nowhere is explained this, and you say that cities can't have more unhappiness than their population but in the second screenshot I have 8 unhappiness and 7 citizen in the city (I guess that urbanization is an exception to the rule?)

**Comment by bentakacs** [comment]
@Aqinu you're very welcome my friend!

Ahh, yes, sorry! I forgot about that Urbanization went back to its previous state. It used to be for a while that you can't assign Specialists if you don't have surplus local Happiness (or buildings providing free specialists), but it got changed back couple patches ago that you can assign Specialists even if you're capped at Unhappiness (= City Population). That's why they are at the bottom of the hierarchy.
