### ISSUE TITLE
health bars for units with dreadnought promotion still don't work

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5662]
see screenshot. the unit has 17 hp left.

![image](https://user-images.githubusercontent.com/1358966/65546433-cf7f9e80-df17-11e9-8b67-aabdae349a97.png)

**Comment by LoneGazebo** [comment]
I still can’t figure out which health bar that is. I’ve searched far and wide for it.

**Comment by TechpriestEnginseer** [comment]
isnt it because it's the unitflagmanager mod thing that doesn't have the updated hp bar?

**Comment by ilteroi** [comment]
well, two things.

1. both the default and the modded EUI unitflagmanager useunit:GetMaxHitPoints() so they should work out of the box?

2. there's a bunch of places in VP lua where GameDefines["MAX_HIT_POINTS"] is still used

**Comment by TechpriestEnginseer** [comment]
I wouldn't know. I remembered when WHoward69's Base HP Increase from Promotions didn't have this issue and all he did was unit:GetMaxHitPoints()

**Comment by LoneGazebo** [comment]
I'm guessing that 
local function UpdateFlagHealth( flag, damage, unit )

in UnitFlagManager.lua for that unitflagmanager mod is the culprit.

**Comment by ilteroi** [comment]
i do use promotionflags EUI, that's true, but it also has flag.m_MaxHitPoints = unit:GetMaxHitPoints()

**Comment by Stalker012345** [comment]
I was going to open a new ticket, but I think its in line. Its not just the health bar itself, the combat calculator has trouble with the extra health.

In the screenshot below, not only is the Frigate killed (instead of left with a decent amount of health), but the Corvette only takes 18 instead of the estimated 29 damage it was supposed to take. I notice this commonly, the combat calculator dramatically underestimates the power of dreadnought ships.

![image](https://user-images.githubusercontent.com/20593976/66155805-0d4e8800-e5e6-11e9-8c9c-007d72246bc9.png)

**Comment by LoneGazebo** [comment]
@Aqinu tinkered with the combat panel - perhaps something has gone awry there?

**Comment by Aqinu** [comment]
This issue was present even before I made any changes (#5362,  #5354).

**Comment by LoneGazebo** [comment]
aha, I think I know why. Fixed.

@Aqinu cant' confirm second issue you mentioned.
