### ISSUE TITLE
is trade confederacy working?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5664]
i've been trading with two city states forever, but it seems i'm not getting any influence points for it. is the description wrong or is there a bug in the code?

**Comment by LoneGazebo** [comment]
Is it just offsetting your decay?

**Comment by ilteroi** [comment]
nag, decay is just 0.25 per turn

**Comment by Adonis-VII** [comment]
I had the same issue in the August 5th version; when decay was less than the 1 per turn, it wouldn't increase (it used too): https://github.com/LoneGazebo/Community-Patch-DLL/issues/5548

**Comment by ilteroi** [comment]
good tip - that means the description is wrong?

**Comment by Adonis-VII** [comment]
Well it used to be the case that that it would increase very slowly when decay was low (and was part of my Venice strategy) which the description matches. My August playthrough is when I first noticed it not working.

Unless there was an intentional change, then my view is its a bug. I do not remember seeing anything discussed in the changelogs over the past year, but I may have missed something as I don't get to play every version.
