### ISSUE TITLE
Bombardment Promotion Defends against Cities, but UI/Tooltip doesn't show it

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5679]
_1. Mod version (i.e Date - 4/23):_
9/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In the screenshot below, you will see that the frigate is getting a 90% combat bonus to defend against the city. In the second screenshot, I show a targeting frigate that is not getting the bonus.

If the bonus is intended, than the combat UI needs to reflect it, AND the text of the promotion needs to be updated (it currently says the bonus is for attacking cities). Otherwise, if it is meant for attacks only, than the promotion needs some correction.

![image](https://user-images.githubusercontent.com/20593976/66163885-fa907f00-e5f6-11e9-9ed4-eff9af0a189c.png)

![image](https://user-images.githubusercontent.com/20593976/66163912-08460480-e5f7-11e9-86bd-50e0074f9521.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
Something weird is going on, I tested it further and I've noticed these:
1. When a city attacks range naval unit (doesn't matter what promotions they have) their defense is calculated with 'range strength'
2. When any other unit beside the city (land, air, naval) attacks the frigate with bombardment promotion the defense is calculated using just 'melee strength' without any other bonus from bombardment promotions (here is something different because with land range unit vs another land range in defense is used the 'range strength' not like here where land/air/naval range unit vs naval range units is used 'melee strength')

Example:
![c](https://user-images.githubusercontent.com/49090452/66265826-7708a500-e825-11e9-9c51-4654e02dfb7f.png)

**Comment by LoneGazebo** [comment]
@ilteroi same issue as other - damage calc issue?
