### ISSUE TITLE
CTD after first turn

### ISSUE THREAD

**Issue by theonehitpupper** [LoneGazebo/Community-Patch-DLL#5695]
_1. Mod version (i.e Date - 4/23):_
Every beta version after the 7/29-1 release. Tried 10/8 with same results.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After settling city and clicking next turn, game crashes halfway through processing AI turns.

_4. Steps to reproduce (optional):_
Crashes no matter what setup I go for. Doesn't seem like a specific Civ is causing it either. Running no other mods. I even tried disabling Vox Populi and only leaving the Community Patch enabled with no success.

[Ramkhamhaeng_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3709445/Ramkhamhaeng_0000.BC-4000.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3709448/CvMiniDump.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3709450/Logs.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by theonehitpupper** [comment]
Tried turning off all mods except the Community Patch. Still crashes after the first turn.

**Comment by JohannesGaessler** [comment]
I also have this issue.
I noticed that this problem is especially prevalent when I play on the Communitas map with high sea level and all players starting on the same continent.
I eventually noticed that with the above settings two players can essentially start right next to each other.
Perhaps there is a bug when two players immediately spot each other after they spawn?
The (8/31) update gave the AI extra sight radius on higher difficulties, so maybe a preexisting bug is now more visible?

[AutoSave_Initial_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3721546/AutoSave_Initial_0000.BC-4000.zip)

**Comment by ilteroi** [comment]
does this happen in every game you start or just with this save?

in the latter case i might have found/fixed the problem

**Comment by JohannesGaessler** [comment]
I do not experience a CTD on the first turn of every game that I play.
It only happens sometimes (~10%), but if I play Communitas with high sea level and Terra it happens very often (~85%).

**Comment by theonehitpupper** [comment]
For me, it happens on every game and with seemingly every map type.

**Comment by theonehitpupper** [comment]
Seems like the problem has been fixed with the 10/23 beta release.
