### ISSUE TITLE
why does digging for artifacts destroy the improvement on the plot?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5699]
see title.

might be another vanilla thing, but do we really want it that way?

**Comment by pineappledan** [comment]
Didn't realize it was an option. The archaeologist is making an improvement, so the previous improvement has to be removed. In my own headcannon it makes total sense; if an archeological site is discovered in some farmer's field/pit mine/etc all work stops there until the researchers get what they came for

**Comment by LoneGazebo** [comment]
fixed to not remove. no reason, really.

**Comment by UndeadDevel** [comment]
This seems to have caused another issue now: when a dig is conducted on a non-improved tile and the archaeologist is used to extract an artifact, the "Archaeological Dig" improvement actually remains there instead of getting erased as was previously the case, such that one can now send another archaeologist and construct a Landmark on that spot despite the site already having been used to get an artifact.

This is on version 23/10, though; should I make a separate bug report?
