### ISSUE TITLE
Mounted_Ranged unit promotion tree linked to attack range instead of IsMounted Flag

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#5712]
_1. Mod version: 09-21

_2. Mod list: Inuit for VP

_3. Error description: 
The Inuit UU is a harpoon-throwing crossbow replacement that has 1 range. The unit gains access to parthian tactics etc. promotions instead of range and infiltrator like a normal crossbowman. The only thing I can think that would cause this is that the unit has 1 range, the same as a skirmisher, and the game is using Range to determine what promotion tree to use, rather than IsMounted.

I'm wondering if this could be changed? I would prefer the UU be given the same promotion tree as any other crossbow.

**Comment by UndeadDevel** [comment]
I'll take a look.

**Comment by UndeadDevel** [comment]
Ah I misunderstood; I thought your issue was with the Promotion Tree UI, but it's actually with the way VP distinguishes the two land ranged lines. There is too much interdependence for me to assess any changes, but just from a cursory look I see that IsMounted is used e.g. for the anti-mounted combat bonus...if this were now given to e.g. Light Tanks you'd have the odd situation that Fusiliers get a combat bonus against them, though maybe there's a way to introduce / use another attribute like "IsArmored" or something...

Anyway, someone else needs to look into it; if this leads to any changes, however, I'd appreciate if the new way to distinguish between the two land ranged lines were outlined here and the appropriate functionality exposed to LUA so that I can update the Promo Tree UI accordingly.

**Comment by pineappledan** [comment]
There must be some good AI reason that G didn't just set up a separate unitcombat class for mounted ranged/armor. The current system requires lua if modders want to give promotions or bonuses vs mounted/unmounted archer units.

**Comment by LoneGazebo** [comment]
The reason is that unique combat classes don’t play nice with all animations.

**Comment by LoneGazebo** [comment]
I'll fix by adding a unitpromotion variable 'IsMounted'

**Comment by UndeadDevel** [comment]
Hmm well I guess I'll wait until someone uses it and complains about Promo Tree UI not working properly 😃 
But seriously, once the new version is here and the special unit mods make use of the new functionality, someone should probably send over those mods so I can make Promo Tree UI compatible with them.
