### ISSUE TITLE
Potentially unnecessary MOD_BALANCE_CORE define checks?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5724]
_1. Mod version (i.e Date - 4/23):_ Latest

In the code for opinion modifiers in CvDiplomacyAI, I notice there's a fair number of modifiers where the old opinion calculation is kept separate from the mod version by an #if defined(MOD_BALANCE_CORE) // #else // #endif check.

This can result in the code being somewhat confusing to look at, here's one example:
https://gyazo.com/1ac35361a1cce137b1fe669bcb433086

It's not by any means a huge deal, but are these really necessary? Aren't AI improvements a Community Patch thing, not a balance thing? If they're not necessary, I can clean up the code.

**Comment by ilteroi** [comment]
initially these defines were a way to mark the limited amount of non-vanilla code for people who don't know git. but we're long past that stage. 

then there was the modularity aspect so that individual changes can be disabled, but
nowadays it's impossible to compile without this define anyway.

so from my perspective all the old code should just be removed to increase readability.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Any thoughts?

**Comment by LoneGazebo** [comment]
I think instances where we've #elsed code with the core MOD_BALANCE_CORE or any other 'core' MOD_BALANCE_X modifiers, we can remove the else'd code.

**Comment by HeathcliffWarriors** [comment]
Can do.
