### ISSUE TITLE
10/23 - Drill Appears to be granting Defense Bonus against cities

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5741]
_1. Mod version (i.e Date - 4/23):_
10/23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
It looks to me like Drill is now giving defense bonuses against city attack. My city is doing way too little damage to this unit.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/67614143-fc280f80-f77c-11e9-9b85-7f1f1e5c9402.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
It actually may be something more. My notes initially aside, my cities just seem to be doing way too little damage in general. Some the following, that is a full Arsenal City with a Tradition Garrison, aka about the strongest you get...and its barely scratching either the field gun or G gun.

![image](https://user-images.githubusercontent.com/20593976/67614172-c0da1080-f77d-11e9-827f-4f0cf7183322.png)

**Comment by LoneGazebo** [comment]
I'd page @ilteroi on this

**Comment by UndeadDevel** [comment]
Wasn't Drill giving a defensive boost (as well as offensive boost) against cities an intentional change in some recent beta? That other problem (second post) would be a different issue.

**Comment by ilteroi** [comment]
again, it's unclear what's the desired behavior here.

cities have a defensive strength (shown on the city banner) but for attacking the contribution from defensive buildings is ignored. on the other hand, castles etc boost the ranged attack strength. in your case that works out to 23.4 - so it's actually fair that you barely scratch the 78.3 fieldgun. 

also i think the "garrisoned unit bonus" doesn't actually exist, but that's just a lua problem - garrison presence is already factored into the city strength value.

the whole system is crazy, stuffed full of hidden ad-hoc modifiers ...

**Comment by LoneGazebo** [comment]
@ilteroi should ranged attacks or defense even use 'getExtraCombatPercent' in CvUnit? I feel like that should be exclusively looked at for melee only. We have ranged attack/defense modifiers already...

**Comment by ilteroi** [comment]
in general i'm totally in favor of abandoning modifiers. but what's the connection to this issue?

**Comment by LoneGazebo** [comment]
@ilteroi well note that 'Combat Bonus' in first picture is giving him +60% defense, but that's from CombatPercent, not rangedcombatdefence. So effectively in that instance combatpercent is giving both melee and ranged defense.

**Comment by LoneGazebo** [comment]
@ilteroi I wonder if we could more easily use the 'tooltip sink' method used in CvCity for modifiers for attack/defense modifiers, and get rid of the nightmarish enemyunitpanel code?

**Comment by ilteroi** [comment]
well i certainly agree it's a nightmare. tooltip string would be nice, but a lot of effort.

anyway the change in the DLL is a one-liner. but i don't have the overview on all the promotions it would affect.

**Comment by LoneGazebo** [comment]
I think we should probably ask the forum about it first, but it does feel counter-intuitive to have two promotion attributes that do the same thing for defense.

**Comment by ilteroi** [comment]
also, there is CITY_RANGED_ATTACK_STRENGTH_MULTIPLIER, currently set at -25, meaning 25% reduction. if ranged attacks from cities are too weak, this is the value to tweak.

**Comment by Stalker012345** [comment]
Just to note one more example:

![image](https://user-images.githubusercontent.com/20593976/68078268-95b87800-fda0-11e9-9c3d-e89aec57fcbf.png)

And before the drill promotion, I was taking about 40-45 damage from my single attack. I should not be taking so much damage from such a weak city.

**Comment by HeathcliffWarriors** [comment]
City attacks are doing almost no damage in my playthrough.

**Comment by UndeadDevel** [comment]
I'll add my experience as well: City attack damage does seem too low now; it's coming close to being insignificant.
At the same time Cities have now become almost unassailable with melee units; example: Knight (24 CS) with Drill attacks City with 14 Def and would take 45 damage! The city doesn't even have Walls, just a garrison (Mandekalu = 14 CS). Knights normally obliterate Mandekalu (take 20 damage, deal 50 if odds are NOT in Knight's favor...other times it can be take 10+ damage, deal 60+). A City with a (relatively) weak unit just tanking the damage like that and dishing out so much despite not having a single defensive building is, frankly, ridiculous and unfun.
Let me show you:

Knight vs. measly City:
![Knight_v_City](https://user-images.githubusercontent.com/30495439/68083390-18344c80-fe20-11e9-81c2-f30852c2ef73.jpg)

Knight vs. Mandekalu:
![Knight_v_Cavalry](https://user-images.githubusercontent.com/30495439/68083393-23877800-fe20-11e9-8a76-f51d37fc1cf2.jpg)

This leads to some pretty serious issues as you can see in the next screenshot; Netherlands and the Celts have been at war with Askia for about 15 turns now and the Warscore is 0 for all, because despite the Celts damaging Kumbi Saleh every turn, it just takes so incredibly long to bring it down...there is very likely no big fight there, because more than half Askia's army is in the East (I've been monitoring it with my Scout) and the Celts have twice his Military Score, while the Dutch have about equal score so they likely outmatch him greatly but the City takes ages to fall due to this insane damage it does when melee units attack.
![City_madness](https://user-images.githubusercontent.com/30495439/68083401-34d08480-fe20-11e9-8602-c292f64df540.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi is aware as shown in another thread (can't find ATM).

**Comment by UndeadDevel** [comment]
An odd observation to counterbalance: My Trailblazer III scout within range of my GG (CS 9, +15% or +45% CS, depending on whether TB III counts against city attacks) received 35 damage from a 14 Def City without any defensive buildings and only 1 garrison (14 CS Mandekalu)...I honestly didn't expect that much damage in this case, given how little is being dealt by better upgraded and much stronger Cities in the other examples here...if anything, it's incredibly unpredictable.
