### ISSUE TITLE
Recon and Sea Units should not trigger CS Trespassing

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#5756]
It makes no sense that a neutral CS does not get mad when a unit moves through their territory, but does get mad when they stop there for 1 turn. I propose either a default promotion that gives recon and sea units immunity, or having a timer so the CS gets mad after 2 turns in territory, or having the trespassing trigger ignore recon and sea units all together.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo I just had an idea, any thoughts?
1 - If you have 0 or more Influence with a City-State, you can have one scouting unit within their borders without penalty. If you have < 0 Influence, you do not get this privilege.

2 - If you have more than one scouting unit _or_ any military units within their borders without permission and your Influence is >= 0, you will take an Influence penalty that disregards one scouting unit. 

Early game exploration can be somewhat annoying because of the need to avoid CS borders and the lost Influence from it is more of an irritant than anything meaningful, I think this would be a nice change.

**Comment by usadefcon1** [comment]
This! ^

**Comment by usadefcon1** [comment]
I would include sea units in the equation since they also tend to trigger trespassing while scouting.

**Comment by Edaka** [comment]
You could also check out the modmod that gives scouting units the ability to enter foreign territory without open borders. It removes the CS influence penalty.
