### ISSUE TITLE
Coastal City: Defense lowered by second garrison unit

### ISSUE THREAD

**Issue by 4CV** [LoneGazebo/Community-Patch-DLL#5800]
_1. Mod version (i.e Date - 4/23):_ 10-23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ I had a ship as garrison in a coastal city, then I moved a land unit in. After that, the defensive strength of the city was lowered from 40 to 36. 
Should the defense of the city not at least remain the same?

![CityDefense2](https://user-images.githubusercontent.com/25335477/68222403-3f8b4500-ffeb-11e9-981b-64696254e6a6.jpg)

[AutoSave_0218 AD-1540.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3809910/AutoSave_0218.AD-1540.zip)

_4. Steps to reproduce (optional):_ Could be reproduced with IGE and different units.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ryanmusante** [comment]
To clarify, does an air unit ever count as garrison? Or will it not affect CS?

**Comment by ilteroi** [comment]
only land and naval units are used as garrison. naval units are considered to have only half their base CS as a garrison.

did the elephant have a lot of promotions?

**Comment by UndeadDevel** [comment]
This seems to still be broken in 12-1-1 @ilteroi ...have you added fixes for this since the early December version or should I file a new bug report?
Basically a Coastal City (puppeted) on a Hill without defensive buildings will have 60 City Strength with an Ironclad in it as the sole garrison, but moving a Fusilier in reduces the CS to 38, which both seems to be exactly this bug and seems to not apply the halving of CS for naval unit garrisons.

**Comment by UndeadDevel** [comment]
Do I need to open a new issue or is no one actually reading this? I just tested with 12-24-3 and 1-6 DLL and it's still broken.
@ilteroi

**Comment by 4CV** [comment]
Well, I could not reproduce that issue right now: 
Rome (14 CS) >> 17 CS with a spearman garrison. Moving an additional trireme in made no difference. Moving the spearman out: 16 CS. Then trireme out: Back to 14 CS.
Just for fun: With an IGE-made cruiser garrison, Rome got 55 CS, an additional spearman made no difference. Without the cruiser CS dropped back to 14 CS. So for me all seems well atm.
I play the latest patch and hotfix DLL. 
If needed, I can add some pictures and/or savegame later.
Happy New Year, btw.

**Comment by UndeadDevel** [comment]
Happy New Year and Merry Christmas; may God always guide us and watch over us.

On to the issue:
First, in your example, the Cruiser giving 55 CS isn't supposed to happen as ilteroi stated that "naval units are considered to have only half their base CS when used as a garrison", so the City is using the RCS, not CS, of the Cruiser and nothing is being halved.
Second, the lowering of City Strength by land units happens when you use contemporaneous units in low-CS Cities (such as a newly conquered City, which won't have any defensive buildings, which is, after all, the precise case this whole mechanic was introduced in the first place)...I just retested it with the newest patch (12-24-3 and 6-1 DLL); see for yourself:
![_CS1](https://user-images.githubusercontent.com/30495439/71916294-8de8cb80-3175-11ea-89e4-3b9d5871fd61.jpg)
![_CS2](https://user-images.githubusercontent.com/30495439/71916312-93461600-3175-11ea-883f-e36a904c24f5.jpg)
![_CS3](https://user-images.githubusercontent.com/30495439/71916318-96410680-3175-11ea-8833-c50f2e5cdc71.jpg)
![_CS4](https://user-images.githubusercontent.com/30495439/71916326-9a6d2400-3175-11ea-8e66-00677d012fb4.jpg)
![_CS5](https://user-images.githubusercontent.com/30495439/71916333-9d681480-3175-11ea-82d8-042eb0d184da.jpg)
![_CS6](https://user-images.githubusercontent.com/30495439/71916342-a0fb9b80-3175-11ea-8424-e6265c516e21.jpg)
![_CS7](https://user-images.githubusercontent.com/30495439/71916347-a3f68c00-3175-11ea-9d5e-2d02d7da5376.jpg)
