### ISSUE TITLE
Merged and Fixed

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#5808]
@ilteroi @HeathcliffWarriors @Aqinu 

I merged a ton of bad and conflicted commits. My beta code for upcoming changes is in there, but it works.

CHECK THE CODE IN MASTER AND MAKE SURE YOUR CHANGES ARE IN.

Thanks!

G

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Checked the full code changelist: just a couple minor issues, sent a pull request. Everything else is merged correctly.

**Comment by LoneGazebo** [comment]
@HeathcliffWarriors a few of your edits were busted - sure they’re good? Still not using the IDE? :)

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo I went through the code looking for any issues and taking notes, after fixing the small issues, my list is:

Curiosities
- Apparently the C++ ceil function doesn't work? Or do I need to put a second (int) before it?
- Did GetNumTurnsLockedIntoWar cause a compatibility issue? I was attempting to factor in 3rd party trade wars along with coop wars. Or was it a decision for other reasons?

Notes
- Facepalmed about the DoUpdateVictory levels fix. My bad there. :)
- Have noted how to call policy branches properly.
- Have noted to check LuaPlayer when editing any existing diplo AI function, since Github's search function can't find a search term within a word, apparently.

Re: the IDE, I tried but got confused during the installation process, heh :)...I'll take another look at the tutorial you sent and see if I can un-confuse myself.

**Comment by LoneGazebo** [comment]
Ceil wants floats, int isn’t a float.

**Comment by LoneGazebo** [comment]
GetNumTurnsLockedIntoWar wasn’t taking a reference for me.

**Comment by HeathcliffWarriors** [comment]
Ah, gotcha. Well, I checked the code and saw no other issues - for my changes that is. :)

**Comment by LoneGazebo** [comment]
@HeathcliffWarriors re: GetNumTurnsLockedIntoWar, you called it without calling GET_TEAM (it is a CvTeam function, so you have to reference CvTeam to get to it). Besides, it is cheaper to put that call in ::IsLockedIntoCoopWar, which is what I did.
