### ISSUE TITLE
Function to check for visible city in danger?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5851]
So there's logic in the diplo AI (specifically, it checks for willingness to make peace) that checks to see if the other civ has any cities in danger.

If the other civ has cities in danger and the AI player's own civ does not have any cities in danger, then they will be unwilling to make peace. The function call is HasCityInDanger from CvPlayer.cpp.

I copied this code over to IsWantsToConquer since it seemed like a good idea.

However, the function doesn't check if the city is visible or even revealed to the evaluating player (it doesn't have a player parameter).

It _is_ cheating for the AI to magically know whether any of the player's cities are in danger if it can't see them. So is there any function which checks only for cities that are visible being in danger? @ilteroi

**Comment by UndeadDevel** [comment]
By "visible" do you mean revealed or visible as in the FOW is lifted because I have units there to check what's currently going on? Because it's definitely possible for the player to check the health of a city even when the tiles aren't visible (as long as they are revealed) and checking that health over a couple of turns can tell you whether someone is blockading it or damaging it.

**Comment by HeathcliffWarriors** [comment]
True - so I guess

if city health < 100% then return true

if city is visible (FOW lifted) then return true

otherwise return false

...is what I'm looking for.

**Comment by UndeadDevel** [comment]
Well, ideally it would actually check the health over some turns, because a city may have been damaged in the war and now be recovering without further damage because the attacker has been repelled, which I as a player would interpret as the city likely not being in danger anymore. Don't know if that's feasible in the code, though.
Another idea is this: check if anyone else is at war with that player; if not, then the only danger for his cities are going to be my units; therefore, if I don't see a city it's probably not in danger as my units aren't close to it.

Overall, though, I'm not sure whether this "cheat" on the part of the AI is all that bad...after all a player will be able to judge the status of his opponent much better than the AI can due to a better grasp / overview of what's going on that doesn't rely on functions like this but inference and experience. So maybe it's fine that the AI uses that plot danger method for cities it can't see, even if it is a bit of a cheat.

**Comment by ilteroi** [comment]
IsWantsToConquer is used a bit differently now.

earlier it was used to suppress targeting a certain player completely. today it only makes the AI require a higher score for potential targets.

so i think we don't have to make it so complex.

**Comment by HeathcliffWarriors** [comment]
Will take note of that for adjustments, then. :)
