### ISSUE TITLE
12/1 - Outdated Firaxite Materials description regarding TR pillaging

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5926]
_1. Mod version (i.e Date - 4/23):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Even though I am at war with the Iroqouis, my sub is unable to pillage this cargo ship.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/69943737-38047200-14ab-11ea-9635-6b4ad841d2df.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
Did you check corporations? Unless I misremembered, one corporation makes your trade route imune to pillage.

**Comment by Stalker012345** [comment]
Ah you nailed it, my apologies, no issue here.

**Comment by UndeadDevel** [comment]
If you're talking about Firaxite Materials, it states "[...] Trade Units cannot be pillaged (except as a result of a Declaration of War).".
Since you seem to be at war with the owner of the Trade Unit the corporation shouldn't prevent pillaging; pillaging should only be prevented when barbarians or Morocco is involved (without DoW)...either that or the corporation description needs to change.

**Comment by Edaka** [comment]
I think the "except as a result of DoW" part was written back when DoWs automatically destroyed all trade routes between belligerents, without having to be pillaged manually. Since that's no longer the case, it's likely just the text that needs to be updated.

Although, as of consequence of the new mechanic, it's a much stronger effect now.

**Comment by UndeadDevel** [comment]
If that's the case, the text should indeed really be updated since I've thought so far that it works as described...but I'd also say that it seems incredibly powerful this way; maybe too powerful.
