### ISSUE TITLE
cannot dig in minor's territory

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5973]
this is with the latest master (a2803fecccc4d208dcac2c3eef12bba77688c174)

![image](https://user-images.githubusercontent.com/1358966/70867438-d695d600-1f75-11ea-85c5-431b67dea26a.png)

seems to be new behavior? is it intended? what would be necessary to allow digging in that spot?

**Comment by Stalker012345** [comment]
I don't know if CS are different, but I can't dig in a spot where I have my own workers for example, so its possible the worker is blocking you.

If that is the case it looks like an exploit, because then if I see people coming for artifacts I could just put a worker there to block it until I get my own archeologist there.

**Comment by HeathcliffWarriors** [comment]
Seconded, I think it's the Worker.

**Comment by ilteroi** [comment]
uh, how did i miss that worker? 

anyway the exploit is rather minor, to do it perfectly you even need two workers ... also i really don't see an easy way out.

so let's close this.

**Comment by Edaka** [comment]
I think a worker only prevents digging if he's currently constructing something, like a farm in your example. I believe you can't block digging with an idle worker. 

The logic's the same for two or more workers standing on the same tile - one can work on it, and others just standing there won't prevent it.
