### ISSUE TITLE
minor civ quests

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5998]
i was allied with buenos aires. then arabia finished a quest:

208, Arabia, Buenos Aires, FINISHED QUEST, Build X Buildings, Friendship: 0 to 255, MINOR_CIV_BUENOS_AIRES

now, arabia is their ally and the tooltip says:

![image](https://user-images.githubusercontent.com/1358966/71298328-de93b280-2387-11ea-8415-cf413b184972.png)

how can that happen? first of all 255 friendship earned seems like a lot but also why do i need 316 to surpass arabia again?

**Comment by HeathcliffWarriors** [comment]
If you were at war with Arabia they're not supposed to be getting quests?

**Comment by UndeadDevel** [comment]
As for the numbers: you are currently at -60 due to the war; Arabia is now at 255. This means you need

255+60+1 (so you have more) = 316

to take the lead.

**Comment by ilteroi** [comment]
ah. so my previous friendship points were all lost? that's annoying.

also the quest was created before the war. but i agree that it should not be possible to fulfill a quest for a minor you are at war with.

**Comment by UndeadDevel** [comment]
If Arabia fulfilled the quest while it was at war with that CS (e.g. due to you being at war with Arabia and that CS being your Ally) then that should definitely count as a bug, IMO.

The Influence ("friendship points") is only permanently lost if you declare war on the CS directly, I think; otherwise, if your war with the CS is due to his alliance with a major civ you're at war with, your previous Influence level will be restored once you make peace; at least that's what I've seen so far, if I'm not mistaken (haven't paid super close attention to it, but it seems to work more or less like that). Directly declaring against the CS will also lower his Influence base to -20 and lock you out from any quests for a certain number of turns (it will say so in a tool tip), which doesn't happen if you are at war for other reasons.

**Comment by HeathcliffWarriors** [comment]
@UndeadDevel I've seen the "You aggressively attacked this City-State" tooltip without declaring directly on them before, think that's another bug.

**Comment by UndeadDevel** [comment]
Hmmm...maybe it's from taking heavy tribute? I'm not sure if you're supposed to get that from heavy tribute, however, but I kinda, sorta, maybe remember that happening after heavy tribute...only kinda sorta, though 😄

**Comment by HeathcliffWarriors** [comment]
I recall it occurring when a City-State ally declared war on me with no provocation, hence why I think it's a bug.

**Comment by HeathcliffWarriors** [comment]
This is fixed now, looks like.
