### ISSUE TITLE
Nitpick: Red Fort description overflowing; suggestion inside

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6024]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
The Red Fort's build screen looks unpolished due to its description overflowing into the border of the window; this is easily fixed, however, by simply shortening the text a bit. Here's my suggestion:
Change the current description:
`Requires completion of [COLOR_MAGENTA]Fealty[ENDCOLOR] Branch. Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_ENGINEER] Great Engineer and a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Arsenal in the City in which it is built. City [ICON_RANGE_STRENGTH] Ranged Strike Strength increased by 50%, and [ICON_RANGE_STRENGTH] Ranged Strike Range increased by 1. Greatly increases the [ICON_STRENGTH] Combat Strength and Hit Points of the City, and increases the Military Unit Supply Cap from population by 5% in all Cities.`

to

`Requires completion of [COLOR_MAGENTA]Fealty[ENDCOLOR] Branch. Receive 1 [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] [ICON_GREAT_ENGINEER] Great Engineer and a [COLOR_POSITIVE_TEXT]Free[ENDCOLOR] Arsenal. City [ICON_RANGE_STRENGTH] Ranged Strike Strength and Range increased by 50% and 1, respectively. Greatly increases [ICON_STRENGTH] Strength and HP of the City and increases the Military Unit Supply Cap from population by 5% in all Cities.`

Check out the screenshots to see how it currently looks and, in the second screenshot, how the last line would disappear if my suggestion is implemented (I constrained the text in the same manner as the game does in that circumstance and used the same Font; icons were replaced by two capital letters each, which should be approximately of the same size).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![text_Red_Fort](https://user-images.githubusercontent.com/30495439/71448904-d8605600-273a-11ea-8b98-db176ee1fc84.jpg)
![Red Fort text comparison](https://user-images.githubusercontent.com/30495439/71448906-e44c1800-273a-11ea-95d0-509a6acfbdf2.png)

**Comment by Aqinu** [comment]
Yeah, I've tried some time ago to address this issue but it wasn't accepted, check the bottom of this page: 
https://github.com/LoneGazebo/Community-Patch-DLL/pull/5592

I you want I can tell you what to do to implement this for your game if you like this solution (the overflowing is present in 5-6 wonders)...

**Comment by UndeadDevel** [comment]
I see; making the box bigger does make sense, since for the WWs with even longer descriptions (like Bletchley Park) the description simply cannot be sufficiently shortened.

Well, maybe this issue will make Gazebo reconsider? It's pure polish, of course, but since we're supposed to be in the polishing phase it makes sense.

**Comment by HeathcliffWarriors** [comment]
@Aqinu I'm not sure it was "not accepted" so much as "removed in a merge". Merge errors do happen, especially when multiple people merge changes at once.

**Comment by Aqinu** [comment]
@HeathcliffWarriors If your read all the text you would know that I didn't provide any code to be merged cause I didn't know how to do it, I just supposed the locations where the file should be added... (It's also necessary to add the path of those added files in their respected **.modinfo file** and with that I don't know how to work with, that's why I asked @LoneGazebo to resolve it).

**Comment by HeathcliffWarriors** [comment]
Ah, then it might have been overlooked.

**Comment by Aqinu** [comment]
Maybe it will be fixed this time if that's the case...

**Comment by LoneGazebo** [comment]
If you want to repush @Aqinu I'll make sure it makes it into the next merge.

**Comment by Aqinu** [comment]
@LoneGazebo If your read all the text you would know that **I didn't provide any code/pull request** (except the downloadable changed file for wonders popup, [here](https://github.com/LoneGazebo/Community-Patch-DLL/pull/5592)) to be merged cause **I don't know how to do it**, I just supposed the locations where the file should be added (It's also necessary to add the path of those added files in their respected .modinfo file and with that I don't know how to work with, that's why I asked **you** if you can solve it).

**Comment by LoneGazebo** [comment]
i see four referenced pull requests in the link...

**Comment by Aqinu** [comment]
Can you **just read** the comment with the **2 screenshots** of the wonder popup fix from that [page](https://github.com/LoneGazebo/Community-Patch-DLL/pull/5592), those pull request doesn't have anything to do with what we talk here... (It's also necessary to add the path of those added files in their respected **.modinfo** file and with that I don't know how to work with, that's why I asked you if you can solve it).

**Comment by Aqinu** [comment]
@ilteroi why did you close this issue? it's not fixed...
