### ISSUE TITLE
DB corrections

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6090]
1. Mod version : 12-20-3
2. Mod list: only VP
3. Error description: I post lines that fixed some issues in current VP build. If I find more, I will post them as well.

UPDATE Buildings SET **NumPoliciesNeeded = 7** WHERE Type = **'BUILDING_BOROBUDUR'**; -- was 8
UPDATE Buildings SET **NumPoliciesNeeded = 8** WHERE Type = **'BUILDING_KREMLIN'**; -- was 7
UPDATE Buildings SET **NumPoliciesNeeded = 4** WHERE Type = **'BUILDING_FORUM'**; -- was 3
UPDATE GreatWorks SET **Audio = 'AS2D_GREAT_ARTIST_ARTWORK'** WHERE Type = **'GREAT_WORK_THE_CROWN_JEWELS'**; -- all other art has it
UPDATE Language_en_US SET **Text = 'On the contrary. Every Bison dollar will be worth [NEWLINE]five British pounds. That is the exchange rate [NEWLINE]that the bank of England will implement [NEWLINE]after I kidnap their queen.[NEWLINE] - M. Bison[NEWLINE]'** WHERE Tag = **'TXT_KEY_GREAT_WORK_THE_CROWN_JEWELS_QUOTE'**; -- did not fit the screen

4. Steps to reproduce (optional): correct them

**Comment by HeathcliffWarriors** [comment]
@adaneslavo Are you sure those policy requirements for Wonders are correct, and if so, why?

**Comment by adaneslavo** [comment]
I compared tech tiers.

**Comment by HeathcliffWarriors** [comment]
There may be a balance-related reason why the policy requirement is different than normal for those Wonders.

**Comment by UndeadDevel** [comment]
I also thought it was intentional...I'm not attached to it but it's a nice "perk", depending on how you look at it, either for people who are a bit ahead of the curve in Social Policies to know that they will have less competitors for some WW even if they're not the fastest in Tech, or, from another perspective, for players who are fast in Tech to have a better chance to make use of that at least for some Wonders even if they are lagging behind a bit in Social Policies.

**Comment by adaneslavo** [comment]
Borobudur and St. Peters looks like they were swapped with places and someone forgot about policy requirement :)

**Comment by Aqinu** [comment]
@LoneGazebo, if Roman Forum is indented to have 3 policies req. than this issue can be closed.

**Comment by LoneGazebo** [comment]
It is, yes.
