### ISSUE TITLE
performance issue in CvDiplomacyAI::IsUntrustworthyFriend()

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6095]
this line seems to be new:

	if ((GET_PLAYER(ePlayer).GetDiplomacyAI()->GetWeDeclaredWarOnFriendCount() >= 1) || (GET_PLAYER(ePlayer).GetDiplomacyAI()->GetWeDenouncedFriendCount() >= 2))
	{
		return true;
	}

problem is, this is called millions of times during combat sim (indirectly via CvUnit::GetResistancePower() ...) and each call iterates over all players twice.

@HeathcliffWarriors : what would be the best place to cache the result for the current turn slice?

**Comment by HeathcliffWarriors** [comment]
@ilteroi Ah, I didn't realize it was called in GetResistancePower - I think that's a consequence of the warmonger penalty revamp, since I never intended for it to be called while at war.

Easiest way would be to cache the value in memory, update the cached value in the diplo AI's DoTurn function so it's only called once a turn rather than millions of times - and update it early only when a player takes an action that would change the value (such as declares war on a friend).

I'll examine what's changed later today and post a fix.

**Comment by HeathcliffWarriors** [comment]
Ahhh, I see what the problem is. Okay, will fix. :)

**Comment by HeathcliffWarriors** [comment]
@ilteroi In the short term if it's an issue you can fix the performance by replacing lines 20972 and 20973 with the following code:
```
	bool bAtWar = GET_TEAM(GetPlayer()->getTeam()).isAtWar(GET_PLAYER(ePlayer).getTeam());
	bool bUntrustworthy = false;
	if (!bAtWar)
	{
		if (IsUntrustworthyFriend(ePlayer) || IsDenouncedPlayer(ePlayer) || GET_PLAYER(ePlayer).GetDiplomacyAI()->IsDenouncedPlayer(GetPlayer()->GetID()))
		{
			bUntrustworthy = true;
		}
	}
```
For the next version I'll cache it in the diplo AI memory as described above to improve performance.

**Comment by ASCII-Guy** [comment]
@ilteroi Is it a big enough issue to warrant a hotfix?
