### ISSUE TITLE
AI not aggressive enough

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6105]
this is one for @HeathcliffWarriors 

![image](https://user-images.githubusercontent.com/1358966/72276344-fdf0c900-362f-11ea-9272-4d0e7925a1ad.png)

i often see similar situations, one AI settles aggressively (in some cases too aggressively, but for polynesia i thinks it's fine) and the new neighbor just lets it go on for a loooong time. eventually they might declare war and capture it, but my feeling is a human would do so much earlier.

what do you think? can this be changed, should it be changed?

**Comment by UndeadDevel** [comment]
Personally I tend to go by how close they settle to my capital, which in this case is definitely pretty close; they don't deprive Persepolis of any workable tiles but in the mid to long term Persepolis would have expanded to the fourth row and claimed that Perfume, for example, so it's definitely damaging to their interests.

In some cases, such as being involved in other, more important, conflicts (Persia is at war with Zulu, but doesn't really seem threatened) or being Friends with the offender and the Friendship being important to me (not the case here) I may hold off retaliation for a while, especially if the offender is in a good position to defend his new settlement (definitely not the case here).

So yeah, if I were Persia I'd capture and raze that City pretty soon after it was founded, perhaps even immediately, so I don't have to deal with Walls. Considering Persia's military and their likely personality I think they should do it, as an AI....the AI probably already considers Cities with access to resources they like as targets for conquest, but does it take into account a sort of "affront" factor when someone settles close to their capital? And this isn't just about the emotional component, obviously, as Cities can be excellent staging grounds for invasion so you don't want a foreign City next to your capital.

**Comment by HeathcliffWarriors** [comment]
@ilteroi I did mame changes so the AI is more likely to make opportunity attacks on weak targets.

However if it's at war and the state isn't offensive (-3 is the war score in this case) they won't do so.

The likely problem here is that the diplo AI doesn't have a mechanism to evaluate how well-defended an individual aggressively settled city is, and are just comparing Polynesia's overall military strength to their own.

It's probably worse than usual given Polynesia's UA allowing them to settle anywhere from game start.

I think it'd be sensible for the AI to punish aggressive settling in this way, but the issue is A) teaching the AI how well-defended a nearby city really is (taking into account both overall strength and local defenses) and B) teaching it when the state of a war is safe enough that they can divert some forces to capture a nearby city like this.

I'm not sure how to go about doing that, but if there's a well-designed function to do it, I'd totally add that.

**Comment by HeathcliffWarriors** [comment]
Also, what's the (0) in the opinion table? I have a feeling there may be an issue in LuaPlayer somewhere.

**Comment by ilteroi** [comment]
* well we could check the difference between their closest and second-closest city. if the closest one is close and the other one isn't it means we have an isolated target for a hopefully easy & short war.

* for "well-defended", there are the tactical zones, but enemy strength is tricky to estimate without good visibility. also the dominance flags are relative strengths per zone. comparisons across zones are even more difficult.

* that war with the zulus was a phony war ... nothing happening at all. they should have made peace much earlier, maybe after X turns without a battle?

**Comment by UndeadDevel** [comment]
Sorry to interject, but I've been wondering for a while: is there some sort of specific scouting routine that the AI engages in? Like building a scouting unit or naval melee with Navigator promotions and then deliberately sending them around possible targets to evaluate the amount of enemy units there?

**Comment by ilteroi** [comment]
nah. there is a "spotter" that tries to make the target of an attack visible for ranged attacks but that only happens if the AI is already committed to attack

**Comment by UndeadDevel** [comment]
I see, thanks. Maybe such a scouting routine should be added then? It would be a possible solution to the "well-defended" question and the human certainly uses such tactics very often; the AI also has an advantage (usually) regarding the sheer number of units they can churn out and since a scout is only a single unit it seems that this would be a cheap way for the AI to gain some valuable info even if it isn't as good as the human at anticipating danger to keep the scout alive.

In late game there is actually an even easier option for possible targets that are close to AI Cities or Carriers: the mod [Improved Air Recon](https://steamcommunity.com/sharedfiles/filedetails/?id=288579237) allows using the Sweep action of air planes to relocate the Air Recon tile visibility area...so the AI could simply send a fighter to a City near the potential target or move a Carrier there and then do a Sweep to have visibility over the area of interest for purposes of counting units, for example.

**Comment by HeathcliffWarriors** [comment]
Easy Target: Good point there. I'm not super familiar with the distance and military functions, but I'm certain there's a "get city distance in plots" function; I'll look.

Phony Wars: I can train the AI to recognize phony wars and make peace more willingly; is there a function that checks if the AI currently has any ongoing attack operations against a player?

Well Defended: This one remains tricky; but the diplo AI already has checks for overall military strength and target value. What's needed is a way to estimate how well an isolated city target would fare against the AI's military forces. If visibility is lacking, perhaps an assumption could be made as to how much military force could be there - I recall you saying the AI doesn't have any kind of "heat map" for unit positions.

**Comment by ilteroi** [comment]
@HeathcliffWarriors : check out CvPlayer::GetCityDistanceInEstimatedTurns() / GetCityDistanceInEstimatedPlots(). if that's below a threshold, it makes sense to look at the second-closest city, but there's no ready-made function for that, need to iterate over all city pairs, not so nice unfortunately.

then there is CvPlayer::haveAIOperationOfType() but it's kind of stupid, you have to feed it all possible operation types and there are many. better make a new one in the spirit of StopAllLandOffensiveOperationsAgainstPlayer()

assuming enemy strength is tricky, imagine we just divide the total strength by number of cities, that's obviously typically incorrect. scouting isn't easy either, because the AI will forget what it saw in the very next turn. so i would go for the isolation measure.
