### ISSUE TITLE
Feature request: A-bombs never obsolete.

### ISSUE THREAD

**Issue by stevenkxu** [LoneGazebo/Community-Patch-DLL#6151]
Drawing from:
https://forums.civfanatics.com/threads/quick-questions-quick-answers.573489/page-291#post-15646633
 https://forums.civfanatics.com/threads/quick-questions-quick-answers.573489/page-292#post-15646660

When A-Bombs obsolete at Advanced Ballistics, the production does not seem to transfer to Missiles, causing it to be lost. This may encourage delaying researching Advanced Ballistics. I think there wouldn't be any real harm if A-bombs either never obsoleted or obsoleted several techs later, akin to a UU instead of a regular unit.

**Comment by UndeadDevel** [comment]
This actually is the case already in the current version...I've updated my posts in the relevant threads that you linked. I was working off of outdated info when I posted there because I was still finishing a game with the 12-1 version, but now, in the January version, A-Bombs don't obsolete anymore and Nuclear Missiles are pushed back to Lasers or something, so this issue is solved.
