### ISSUE TITLE
Naval Melee Units can attack into Forts

### ISSUE THREAD

**Issue by JohannesGaessler** [LoneGazebo/Community-Patch-DLL#6249]
_1. Mod version (i.e Date - 2/9):_
(2/9-4b)

_2. Mod list (if using Vox Populi only, leave blank):_

- Really Advanced Setup
- Wonder Race

_3. Error description:_ 
If you put a Fort on the coast it allows enemy Naval Melee Units to attack Land Units that are stationed in the Fort. I'm assuming this is a bug.

Unfortunately I do not have a save file that can reliably reproduce the behavior.
I will attach one when I encounter the bug again.

**Comment by ilteroi** [comment]
so you're saying it's not reproducable?

**Comment by JohannesGaessler** [comment]
I am saying that when I reloaded the autosave and just clicked next turn without moving my units the AI did not attack the Unit in the Fort.
However, this may be due to AI decision-making algorithm evaluating the situation differently compared to before.

**Comment by UndeadDevel** [comment]
I can confirm that melee ships can attack enemy Forts on the Coast, at least back in the 12-1-1 version...this doesn't display a Combat Preview IIRC but it's still possible.

**Comment by Vyyt02** [comment]
I think it is intended. It has been like this since you can park ships in coastal forts.

**Comment by UndeadDevel** [comment]
You can't park them in hostile Forts, though...but my issue is less about whether it should or shouldn't be possible but more about consistency: either it shouldn't be possible or the combat preview should be properly generated as with attacks on Cities or other other units.

**Comment by ilteroi** [comment]
the code right now doesn't differentiate between forts and cities ... you want to be able to attack cities, so it's legal to attack forts. 

i doubt whether it's worth to change this and run the risk of introducing new bugs.

**Comment by UndeadDevel** [comment]
@ilteroi Well could there at least be a check introduced that if it attempts to generate a combat preview for a City attack but finds no City that it generates the combat preview for the unit on the same tile (like with Guided Missiles) instead? It's just weird having this situation where you can attack but have great uncertainty regarding the outcome of the attack...plus every other attack generates a combat preview so it sure feels like a bug.

Also, if you're working on City-attack code already: attacking Cities with Guided Missiles generates an incorrect combat preview...here's a screenshot after such an attack (before both units were full Health), with the same combat preview:
![after_GM_attack_cropped](https://user-images.githubusercontent.com/30495439/74597740-0471c680-505c-11ea-887e-7cd98ca42c81.jpg)
Guided Missiles do one-shot Cruisers, but it obviously targeted the Gatling Gun garrison instead of the Cruiser garrison.

**Comment by SuperNoobCamper** [comment]
as far as i remember it's the case since i started but the combat damage predictor never worked.
