### ISSUE TITLE
Cities starving lose pop 1 turn earlier

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6338]
3-1b

![civbugfood](https://user-images.githubusercontent.com/53142313/76401559-5d462d80-6382-11ea-88a6-d7731eb2c5cc.png)

In a situation where the UI and the food calculation displays my city would lose 1 pop in 2 turns (hence I'm expecting one turn of leeway before reassign citizens to food tiles), in practice I click next turn and lose pop right away. First version this is happening afaik, I use to push starving to the limit pretty often and would have noticed this in past.

**Comment by LoneGazebo** [comment]
That code hasn't been touched in a while, probably an edge case due to UI rounding.

**Comment by ilteroi** [comment]
well it might have been me, i added some sanity checks so that a city can never have less then zero of anything. unfortunately starving involved dipping into negative food for one turn, so i had to fix that.

this might be a side effect ... somebody decided to do the "turns to starvation" calculation in lua.

			instance.CityGrowth:SetString( " [COLOR_RED]" .. (math_floor( city:GetFoodTimes100() / -foodPerTurnTimes100 ) + 1) .. "[ENDCOLOR] " )

**Comment by LoneGazebo** [comment]
That'd be firaxis...

Let's make an exception for food for the negative yield issue?

**Comment by ilteroi** [comment]
i'd rather do it right
