### ISSUE TITLE
Entering a CS territory means war

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6356]
3-15b

Reported on page #1 of the beta thread and here for good measure

![civpathwar](https://user-images.githubusercontent.com/53142313/76729238-ed0c2300-6758-11ea-9a66-d0a4e4f77247.png)

**Comment by randomnublet** [comment]
Oh I see what you were trying to do in #6342 ... I do wonder if Greece is allowed to use CS territory.

Anyway, this caused some pathfinding bugs. One more here:
![civpathbug](https://user-images.githubusercontent.com/53142313/76756824-c1a02d00-6786-11ea-8ff5-044503b25f27.png)

I'm trying to move my pathfinder in between Mongolia and France borders. I do have Trailblazer so the game calculates the shortest path through the SE forest (in Mongol territory) instead of through the E hill (neutral); I don't have open borders, hence it's not allowing me to move my scout at all, or asks me if I want to declare war on Gengis. In this specific case I could work around that moving first to the NE forest and then clicking on the jungle, and finally my unit went through that hill.

**Comment by randomnublet** [comment]
More about CSs:

I'm allied to Bratislava, I can enter its territory with no penality but I am allowed to pillage that banana hill tile :|

![civpathbug2](https://user-images.githubusercontent.com/53142313/76757471-ee087900-6787-11ea-90df-8d1ceb8ed355.png)

**Comment by ilteroi** [comment]
well, i tried to restore the "do you want to declare war" popups which happen when you do something that is forbidden during peace.

as a consequence, moves through not-yet-enemy territory are now allowed for humans. but this obviously leads to some unintended results. since i dislike the popups anyway, they are gone again now. you have to declare war explicitly.

regarding minors, the idea is to allow movement into their territory when there is no influence penalty, ie for civilians, when you're friends or when they are under attack from barbarians. these rules are identical to the rules used for the AI.
