### ISSUE TITLE
3/15. Text spam relating to vassal taxes.

### ISSUE THREAD

**Issue by AnemoneMeer** [LoneGazebo/Community-Patch-DLL#6384]
_1. Mod version (i.e Date - 2/9):_ 3/15-2

_2. Mod list (if using Vox Populi only, leave blank):_ Ingame Editor was used for Reproduction testing only. SlowMo Science 50 used to slow science gains down (What can I say, I like the midgame)

_3. Error description:_ AI spams dialogue related to vassal taxes. Was not a problem in previous versions.

_4. Steps to reproduce (optional):_ Honestly have a 100% reproduction rate simply by setting player to vassal. AI will spam text on raising taxes every single turn even when it cannot do so and it doesn't create the popup. Persisted across 3 reproductions without fail.

**Comment by HeathcliffWarriors** [comment]
Only potential cause I can think of are the anti-CTD changes to DoDetermineTaxRateForOnePlayer. Apparently max(1, (int) teamvector.size()) causes spam every turn?

I can revert it since it was working fine before, and I fixed the bug I introduced by accident already. Not sure why this is happening, though; an issue with Putmalk's code, perhaps.
