### ISSUE TITLE
Effect of const functions?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6385]
What does making a function "const" do?

I've observed two effects in the diplo AI:
1) It appears to have some kind of positive effect on performance.

2) It prevents calling some functions (non-const functions?) from within the diplo AI directly; GetPlayer()->GetDiplomacyAI()->FunctionCall(args) must be used instead.

**Comment by LoneGazebo** [comment]
Const tells the compiler that the function will always return the same value and has no ‘math’ within the function regarding what ever registered value is in the function. In short, const means constant, which means consistent.

**Comment by HeathcliffWarriors** [comment]
So const functions can only call const functions, excluding the workaround?

**Comment by LoneGazebo** [comment]
Correct

**Comment by LoneGazebo** [comment]
Purpose is that it is consistent within the function - no outside variables affecting the end result.

**Comment by HeathcliffWarriors** [comment]
But since there are functions which insert outside variables via GetPlayer()->GetDiplomacyAI()->FunctionCall(args), I don't see why it's in use?

**Comment by ilteroi** [comment]
the whole const-correctness idea is meant to allow better compiler optimization, avoid concurrency bugs and to force yourself to think about side-effects in your code.

please don't take any lessons from the coding style used in this project!

what you are referring to is a hack. the member function GetPlayer() gives you a const pointer, which can only be used to call const functions. the macro GET_PLAYER() gives you a non-const CvPlayer object, which can be necessary in some rare situations, since half-implemented const-correctness sometimes leads to situations where you don't want to fix a million other functions you need to call and which you know could be const but aren't marked as such.

to  be fair, the standard also has const_cast<> and mutable members to help deal with tricky situations. but they should be used sparingly.

**Comment by HeathcliffWarriors** [comment]
Hmm, I see. Thanks for the info! :)
