### ISSUE TITLE
Can't move a ship on top of a non-hostile embarked unit

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#647]
https://d.maxfile.ro/tyakieuksf.webm

**Comment by LoneGazebo** [comment]
It's not a civilian, but I'll see about making a change here.

**Comment by Radost** [comment]
The thing is I can move just fine on top of embarked units if the movement points end right on them.

**Comment by LoneGazebo** [comment]
Civilians and non-civilians? Because moving onto a military unit, embarked or not, with another military unit is generally illegal.

**Comment by Radost** [comment]
Technically the embarked state is a "civilian" state anyway.
https://d.maxfile.ro/fvfickunpb.webm

**Comment by LoneGazebo** [comment]
That's why I said 'generally' - things get tricky because embarked units are, essentially, quantum, in that they're combat units but also unable to attack, thus rendering them civilian units. I'm considering just cutting out the 'declare war move' function for units entirely, making it so that you have to enter an enemy's lands, or DOW on the leader screen, to engage in war. It'd definitely fix a lot of this nonsense.

**Comment by Edaka** [comment]
Have you tried moving the ship by manually assigning the command via the move command button? The issue might be that the cruiser as a ranged unit treats right clicks like ranged attack commands, hence it doesn't move.
