### ISSUE TITLE
AI not spreading religion

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6560]
4-17-2

Tradition Byzantium with a faith wonder and incense monopoly. 

Founds second religion, with Divine Inheritance, a bonus pantheon and a wide-friendly follower. Enhances first, with another wide follower and a wide enhancer. 

As of t130, Theo didn't build a single missionary, not even to convert a new city without pantheon. I am in a DoF next to her, without a religion and she doesn't spread to me or friendly CSs either. She was building borobudur but got beaten to it, maybe she wanted to build missionaries after that? Whatever, she prefers to build holy sites on plain desert tiles. It feels like she's actively crippling herself, she could have been a religious powerhouse by now.

![byzspread](https://user-images.githubusercontent.com/53142313/80362504-0b4e5e00-8883-11ea-8df9-2f60b921e9dd.png)

**Comment by ilteroi** [comment]
this is weird. the code is a bit involved but i cannot see how this would happen ... also i've never seen this.

expected behavior is roughly:

* they should always try and convert their core cities first (using missionaries or inquisitors, whichever is more appropriate).

* afterwards, they either go on converting their puppets or try to enhance.

* spreading to foreign cities depends on the chosen beliefs and leader religion flavor.

* finally, they buy buildings or units.
