### ISSUE TITLE
CS Quest: Build Road is being auto-completed

### ISSUE THREAD

**Issue by grmagne** [LoneGazebo/Community-Patch-DLL#6616]
1. Mod version: 
4/17

2. Mod list (if using Vox Populi only, leave blank):
(9) Wonders Expanded (v 2)
(over) More Unique Components for VP (v58)
(ui) City-States Leaders for VP (v 10)
Even More Resources for Vox Populi (v 5)
Krajzen's Great Artists Pack (v 1)
Krajzen's Great Musicians Pack (v 1)
Krajzen's Great Writers Pack (v 1)
Unique City-States (v 6)

_3. Error description:_ 

When I receive a "Build a Road" quest to a coastal City-State, I'm always able to complete the quest without building a road. I never encountered this error on previous versions of VP, with basically the same mod list.

_4. Steps to reproduce (optional):_
I'm not 100% sure, but it seems that building a Lighthouse to get an ocean connection is required.

**Comment by ilteroi** [comment]
yeah the lighthouse is a good guess, but the quest should not be created in the first place if it's already fulfilled ...

**Comment by adaneslavo** [comment]
Maybe it should be restricted to land connection? Sometimes even coastal city-states need roads around.

**Comment by JamesNinelives** [comment]
I got this as well, and it if it helps it only occured with city-states that share a landmass with one of my cities but not a road connection.

Most city-states in my games are islands and they don't auto-connect - I need to send trade routes to fulfill the quest. However, one of the islands was large enough for me to settle and when that CS gave me a 'road to' quest it auto-completed. Which was actually quite interesting because there was a mountain in the way, so I didn't think I was going to be to do that one.

Mod Version: 4/17

**Comment by ilteroi** [comment]
i made it so that the quest will only be handed out by landlocked city states.

that reduces the frequency a bit but it's the simplest fix.

**Comment by adaneslavo** [comment]
I agree it's the simplest solution, but not the best one. Maybe some day...
