### ISSUE TITLE
6/19 HF 1- Civ with no cities still in game

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6719]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I know Shaka hasn't been so well lately, but this looks a bit extreme. He has no cities, no anything.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/85655837-abebaf00-b675-11ea-9626-dc23eb9b46de.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by JamesNinelives** [comment]
Do you have 'complete kills' enabled in your settings? That will cause a civ not to be considered 'defeated' if they still have units somewhere.

**Comment by RecursiveVision** [comment]
It's not Complete Kills - Shaka has no techs or policies.

He must have never settled a city.

**Comment by LoneGazebo** [comment]
Weird.

**Comment by azum4roll** [comment]
Can you check your turn 0 autosave with debug mode to see his starting position?

**Comment by JamesNinelives** [comment]
I'm confident that I've found the reason for this occuring. Saw a similar situation with Germany in my games - 0 cities, 0 techs, 0 policies. Two of their warriors were fortified east of me, seemed to have no interest in moving. Their pathfinder has upgraded to a scout and was running around doing fine apparantly. Then I found the German's initial settler in a barbarian camp!

![20200704144512_1](https://user-images.githubusercontent.com/61379041/86509005-42a73100-be17-11ea-8fa1-10116b0a21f0.jpg)
![20200704144515_1](https://user-images.githubusercontent.com/61379041/86509007-4470f480-be17-11ea-98b6-b021ee8ed1dc.jpg)
![20200704145704_1](https://user-images.githubusercontent.com/61379041/86509008-45a22180-be17-11ea-8473-f059198e1f70.jpg)

I have to assume they moved their settler to a superior starting location only to have it captured by barbarains on turn 1 or 2. I had it happen to me one time - I couldn't see the barbarians because they were behind a hill, but they could move through it and into the tile my settler occupied because of their promotions.

**Comment by RecursiveVision** [comment]
@ilteroi Related to #6751. I've had it happen where I move my Settler in the first couple turns and suddenly Barbarians are there! AI needs special logic to guard its initial Settler with a Warrior if it has one, or its Pathfinder if not, IMO.

**Comment by ilteroi** [comment]
never seen that, must be quite rare. anyway we can make barbarians ignore units from civilizations with zero cities.

**Comment by RecursiveVision** [comment]
Also, just to note I already fixed the "We have similar Social Policies" mod appearing as negative - just a visual issue.
