### ISSUE TITLE
6/19 - Zeppelins can remain stacked with Naval Unit

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6724]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Maybe working as intended, but I've never seen this before. The zeppelin and cruiser are both able to attack and remain stacked like this.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/85805109-0a19a000-b711-11ea-90fe-2707c8350abf.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
same cause as #6713

**Comment by ilteroi** [comment]
ok turns out it wasn't the same root cause.

in fact fixing it properly required rewriting the whole stacking logic. so now we have a beautiful and simple system:
* combat units cannot stack, independent of their domain and the domain they are in
** exceptions apply of course for cities etc
* civilian units can stack anywhere

this saves about 500 lines of code and is easy to handle, so i'm quite content.

**Comment by RecursiveVision** [comment]
@ilteroi Can combat units still capture civilian units? If yes, this sounds like everything is working great.

**Comment by azum4roll** [comment]
Also ships stacking with embarked combat units.

**Comment by ilteroi** [comment]
of course you can capture.

embarked stacking only for civilians. that is the point, you see? otherwise the symmetry is broken.

**Comment by RecursiveVision** [comment]
I think BNW had ships stack with embarked units to protect them from damage as an "escort", since embarked units can be easily oneshot by other units. Changing this does weaken amphibious assaults...does the AI even do amphibious assaults?

If the stacking rule is removed, you may want to consider modifying the defensive combat strength of embarked units to make them less fragile.

**Comment by ilteroi** [comment]
well the strength of embarked units is a secondary discussion. the important rule is, if you can defend you cannot stack.

**Comment by LessRekkless** [comment]
Surely, the important rule could just be "if you are embarked, you can stack". How does that break symmetry?

**Comment by Tekamthi** [comment]
> Surely, the important rule could just be "if you are embarked, you can stack". How does that break symmetry?

i'd like this a lot better... i can see how the code would be more complicated, but gameplay would be much better imo.  Symmetry might be achievable in other (albeit more complicated) ways... say the naval combat units piggy-backed off the air interception function, allowing them to provide protection as though stacked when sufficiently nearby... then AI just has to have a unit close, even if it misses the optimal stack setup

**Comment by RecursiveVision** [comment]
If any embarked units can stack, how would attacking them work?

**Comment by Tekamthi** [comment]
the same as before?

**Comment by RecursiveVision** [comment]
No, I mean, if you could stack say, 5 embarked Warriors on the same tile. Maybe I misunderstood - but "if you are embarked, you can stack" does break symmetry. I don't have a strong opinion on breaking symmetry being good or bad, though.

**Comment by Tekamthi** [comment]
Oh i understand -- well I understood the suggestion to be embarked units can stack with a non-embarked unit... it is unclear on reread.  Anyway, i have yet to give the latest a proper go, will reserve judgment til after i've played it a bit

**Comment by azum4roll** [comment]
The old behaviour was:

- An embarked combat unit can stack with a naval combat unit and civilians, but not with another embarked combat unit
- A naval combat unit can stack with an embarked combat unit and civilians, but not with another naval combat unit
- Civilians can stack with anything

It went slightly complicated in combat:

- Civilians get instantly destroyed by enemy melee naval units on touch, and 40 damage from any ranged attack (takes an attack chance)
- Embarked combat unit has its own embarked combat strength and can retaliate against melee attacks, but cannot attack anything
- A naval/embarked combat unit stack takes at least 2 attacks to destroy and can hold a position better than any single ship. Maybe that's a problem?

**Comment by cdanger341** [comment]
From a tactics perspective, the important thing is that there are only so many tiles around a city to attack from and embarked combat units can only move 4 tiles until the Industrial Era. So if I have melee and ranged naval units taking up at least the first two "rows" of tiles (if not more), and if embarked combat units can not stack with naval units, we would now have to make sure to leave space within our armada for embarked units to get within 4 tiles of where they need to land in the next turn. That introduces micromanagement that wasn't necessary before as you could stack your embarked units under your "blanket" of naval units.

If you want to move forward with naval and embarked combat units not being able to stack, then I think the combat strength of embarked combat units needs to be reevaluated, especially in regards to received ranged damage. In previous builds embarked combat units without a naval unit stacked on top would take more ranged damage than they would on land due to the difference in embarked combat strength versus unembarked combat strength. This meant that ranged units stationed on the shore could usually destroy incoming embarked combat units in 1-2 attacks, thus why it was so important to shield embarked combat units with navel units. Due to the movement speed of embarked combat units it is still possible to make landfall without taking ranged damage of units on the shore, but it requires much more micromanagement. My question is, is the AI capable of understanding this and managing it like an human would, or would they allow embarked combat units to get within 1-3 tiles of the shore prior to disembarkation, allowing for them to be bombarded by ranged attacks for at least a turn.

There is also the loss of the ability to shield retreating combat units when they embark. Previously you could retreat damaged land units by embarking them and then shielding them with a naval unit stacked on top. Currently it would be suicide to do so unless you are certain there are no enemy ranged units within range as naval units cannot stack with the damaged embarked units to absorb the damage until they have the movement to fully disengage the following turn.

I am not saying this new behavior is wrong, but it will certainly confuse many players at first who are used to the old way of how this system worked. It makes embarked combat units even more fragile, and I feel that this change should only come hand-in-hand with a significant adjustment to the combat strength of embarked combat units so that they are not as helpless against ranged and melee naval units and ranged land units.

**Comment by ilteroi** [comment]
i would in fact set the defense strength of embarked units equal to regular defense strength. much easier that way. so the only difference is they cannot attack when embarked.

**Comment by Stalker012345** [comment]
So I'm playing a bit of catchup here, but a few notes:

1) It seems that with this change, melee ships will take a lot of damage
attacking embarked units.
2) 1 UPT will grow worse as there will be more space needed for a given
invasion.
3) Amphibious combat will be both better and worse. Better in that the AI
can send units across the water without them getting super quickly killed.
Bad in that ships no longer can protect embarked units.

Personally I think the negatives outweigh the positives of this change. But
regardless of that... Why are we even having this debate on Github instead
of the Forum? This is not just a bug fix, this is a gameplay
altering change, and a very noticeable one at that

**Comment by LoneGazebo** [comment]
I'd be okay with treating ALL land units on water as 'civilian' units, and allowing simple stacking rules with boats. Simply limit water stacking to 1 naval unit + 1 civilian unit and we'd be good.

G

**Comment by LoneGazebo** [comment]
My primary concern is that, watching the AI, it's not doing a good job of keeping the water clear for mustering purposes. It leaves land units in the water too often, which is bad for both domains.

**Comment by ilteroi** [comment]
if that's the case i believe it can be fixed. i also believe the current system is much better because there is only one rule (when you're embarked you cannot attack). this has already simplified a lot of the code and people will get used to it.

if you don't want it you can revert all the changes to tactical ai, homeland ai, unit, ai operation, pathfinder etc. that will be a fork.

relevant xkcd:

![workflow](https://user-images.githubusercontent.com/1358966/88370391-39fca780-cd92-11ea-9e72-4efe4e8c5397.png)

**Comment by Stalker012345** [comment]
hehe that xkcd is not quiiiiiite relevant for this one. Its more like:

"Hey there's an issue. I was supposed to get Report A, but the program
keeps sending me Report B".

"Oh that, yeah we fixed a bug"

"Oh great, so I will get Report A again?"

"Oh no, the program sends Report B now. But the code is much cleaner and
simpler, the program is really much better".

"But...I needed Report A..."

"Code is better!"


hehe its not that extreme, but it is somewhat true.

**Comment by Stalker012345** [comment]
One other scenario we would need to watch for in this change.

So often when you first take a coastal city, it is important to send a
garrison to reinforce it, else the enemy will simply retake it.

This will be more difficult with the rules change, as I won't be able to
keep garrisons on hand, and will have to keep them farther in the back. So
depending on the size of your fleet surrounding the city, this may be a non
factor, or may inhibit the ability all together. For the AI, the question
will be will it be smart enough to get the garrison through the ship lines,
or will it just leave the city without a garrison.

**Comment by RecursiveVision** [comment]
@Stalker012345 Your most recent comment had your name and email address attached to it - removed that for you in case you didn't intend to publicize that. :)

**Comment by Stalker012345** [comment]
Wow thanks, is that because I've been replying by email? If so....what a major privacy issue!

**Comment by RecursiveVision** [comment]
@Stalker012345 I believe so, the message contained a "reply to a reply by email" kinda deal. Very strange that they display personal information like that.

**Comment by azum4roll** [comment]
As civilians while embarked, can the melee units attack from water against land units? If not it's a massive nerf to the Amphibious promotion.

And changing embarked units to civilians hurts Songhai a bit (War Canoes) already.
