### ISSUE TITLE
Vox Populi no longer seems to have "out of the box" compatibility with City States Evolved

### ISSUE THREAD

**Issue by hawkseye17** [LoneGazebo/Community-Patch-DLL#6758]
_1. Mod version (i.e Date - 4/17):_
6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_
City States Evolved

_3. Error description:_ 
The compatible mods list on CivFanatics shows that the above mod is "out of the box compatible" but that no longer seems to be the case. The nation-state does not seem to found new cities; they build the settlers but the settler just sits in the original city and does not leave. 

(https://forums.civfanatics.com/threads/mods-compatible-with-community-balance-patch-cbp.542679/)

**Comment by RecursiveVision** [comment]
Probably a conflict with the new settling logic. You'd have to ask @ilteroi if you want it made compatible again.

**Comment by hawkseye17** [comment]
@RecursiveVision, how do I do that exactly, I'm kind of new to this whole GitHub thing

**Comment by RecursiveVision** [comment]
He's already been mentioned which should do it again, but I'll do it again: @ilteroi 

If no one here is willing to fix the compatibility issue then you'll need to find someone to do it or the mod won't be compatible.

**Comment by ilteroi** [comment]
if it ever was compatible, it hasn't been in a long time.

the problem is, city states don't explore the map so how would they know where to settle?

for that matter, how would they know where to send their trade routes?

it's a quite a bit of work to make it truly compatible ... and it would have a significant performance impact.

so unless there is a broad consensus that we want this, i'll pass.
