### ISSUE TITLE
No city range attacks! No close city proximity Barbarian warnings.

### ISSUE THREAD

**Issue by soeb80** [LoneGazebo/Community-Patch-DLL#6837]
1. Mod version (i.e Date - 4/17):
Latest to date; 6-19 (including the latest july 27th patch)
2. Mod list (if using Vox Populi only, leave blank):
CP 6-19 installer (1,2,3,4,5,6a,7a,7b)
+Infoaddict
3. Error description:
No city range attacks! No close city proximity Barbarian warnings. 

Jha, barbarians can camp just outside of the city. No warnings of close enemies, nor is it possible to make city range attacks. 

Ok, here is another one @ilteroi. Great work on the update though; zoos and universities give the bonuses, and it stays after save/restart/load.

**Comment by ilteroi** [comment]
works for me ...

![image](https://user-images.githubusercontent.com/1358966/88591989-8a5b5a00-d05d-11ea-9ff1-c0218e897c3c.png)

**Comment by RecursiveVision** [comment]
Hey @ilteroi, unrelated but there's speculation on the forums that your account issues on the forum are due to some kind of secret pact between Firaxis and CivFanatics - which seems ridiculous to me given that VP has five subforums and Gazebo is still there, and I said as much here: 

May help if you explained the issue you're having?

**Comment by soeb80** [comment]
🤦🏼‍♂️My bad guys. The Barbarians was not in line of sight. I jumped the gun to quick. 🤷🏼‍♂️

I played a couple of more rounds and found out. Think I just was tired to start over and all...
