### ISSUE TITLE
Inquisitor logic

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6843]
From what I read in CvReligionClasses.cpp, @ilteroi, you changed the logic so that it factored in population because of the population loss mechanic.

However, G reverted that change as the players found it unpopular - so you may want to modify the logic. Now it only causes 1 turn of resistance.

**Comment by RecursiveVision** [comment]
I think there were also reports on the forums about the AI "never" or "rarely" using Inquisitors in the most recent version, which may be related.

**Comment by ilteroi** [comment]
well the comment is maybe a bit misleading, it's just that you wouldn't want to waste an inquisitor on cities which have no significant presence of other religions.

anyway i'm loathe to do anything because of anecdotal evidence. we need logs. i've slightly improved the logging, every inquisitor use should be marked with "Removing heresy at ..."
