### ISSUE TITLE
Request Prisoner of War duration to be based on game speed setting instead of fixed at one value

### ISSUE THREAD

**Issue by jayeye2011** [LoneGazebo/Community-Patch-DLL#6921]
_1. Mod version (i.e Date - 4/17):_

Vox Populi (any version since POW promotion was implemented)
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Since it was implemented, the POW promotion has been set at 50 turns regardless of game speed. So it is makes it a more useful
strategy to capture workers for the player on marathon game speed and an almost useless strategy for the player on quick speed.  
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Zanteogo** [comment]
While on game speed.. the revolt effect of inquisitors is also the same across game speeds. (1 turn) 
Should really be scaled to game speed somewhat. (I would do 1 turn for quick and standard, 2 turns of epic and 4 for marathon) 

There is also an issues with the American tile buy out cost for production gained across game speeds. Did experiments and the American civ gets screwed on the slower speeds due to tile cost scaling per buy out and production increase for tile buying scaling poorly.  They only get 10 more production per game speed which is way too low. ( Currently 10/20/30/40 think 10/20/40/60 would work better)
