### ISSUE TITLE
Wrong movement points preview

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#6954]
_1. Mod version : 8-23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: See screenshot below. Warrior needs 1 additional movement point to go through forest.
![20200824153133_1](https://user-images.githubusercontent.com/64471766/91051652-b0562900-e620-11ea-896a-78c6d586d15b.jpg)

**Comment by RecursiveVision** [comment]
Use the most recent hotfix.

**Comment by Zuizgond** [comment]
This was with the 8-23 version.

**Comment by RecursiveVision** [comment]
Oh, in that case @LoneGazebo

**Comment by LoneGazebo** [comment]
I don't see an issue with the image.

**Comment by Zuizgond** [comment]
The second move should end on the forest.

**Comment by ASCII-Guy** [comment]
Can confirm this issue in 8/23

**Comment by silentreply** [comment]
Here is an example with 8-23-3. In one of my earlier games (on 8-23-1, I think) it appeared to be fixed for military units and workers, but NOT diplomatic units, so that may be something to look out for with any potential fix. 

![image](https://user-images.githubusercontent.com/59859911/91451585-9187aa80-e84b-11ea-8ef8-73742dd3ff26.png)
