### ISSUE TITLE
Tribute policy mess

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#7155]
10-7-2

Upon spending a great general as a tile bomb anywhere in the empire, the capital receives tribute yields (gold/production) equivalent to the tiles gained. Basically GGs are better than GEs.

The culture you receive upon demanding tribute to a CS also scales with eras (getting 150% of tribute as culture in Renaissance for example, it should be 50% with full authority)

**Comment by randomnublet** [comment]
The culture bomb issue might actually be related to the modified .dll I installed to test pad's Spain rework (I'm not playing Spain tho, I just forgot to revert to old file)

**Comment by Mileslewis** [comment]
The GG interaction is intended #6788 

The culture scaling with era I brought up here #7101 Could be intentional but it doesn't apply to tribute of food or gold for some reason.
Also culture yields from tribute policy scale with gamespeed which isn't necessary since tribute amounts scale with gamespeed already.
