### ISSUE TITLE
AI cities not appearing when settled after moving

### ISSUE THREAD

**Issue by KungCheops** [LoneGazebo/Community-Patch-DLL#717]
I'm currently playing a game observing AIs and I noticed what I believe to be a bug where the AI loses it's settler without the city being settled if it is moved on the same turn as the city is to be settled.

Attached are some screenshots of Denmark's settlers disappearing.
![2015-10-25_00007](https://cloud.githubusercontent.com/assets/6018217/10715493/b3e93abc-7b18-11e5-8c61-1f62a7e51d57.jpg)
![2015-10-25_00008](https://cloud.githubusercontent.com/assets/6018217/10715494/b3ea5ee2-7b18-11e5-8c2e-7a061d50071f.jpg)
![2015-10-25_00009](https://cloud.githubusercontent.com/assets/6018217/10715496/b3eac512-7b18-11e5-8ce4-3b558e4d3cbb.jpg)
![2015-10-25_00010](https://cloud.githubusercontent.com/assets/6018217/10715492/b3e7dfc8-7b18-11e5-9098-8a29784de2bd.jpg)
![2015-10-25_00011](https://cloud.githubusercontent.com/assets/6018217/10715495/b3eab400-7b18-11e5-9711-5aa8d41d673e.jpg)

**Comment by ilteroi** [comment]
i think i've seen that once before, but i wasn't paying much attention so i gave it no mind afterwards.

will check

**Comment by LoneGazebo** [comment]
I guess the found action isn't being processed before the AI unit is killed?

**Comment by KungCheops** [comment]
Kind of looks like that yeah.

**Comment by ilteroi** [comment]
i think it's a coincidence - they are being scrapped.

@g: you changed IsTestStrategy_EnoughExpansion() recently? i guess that's the culprit.

but to be safe i made it so that only settlers outside of an operation can be scrapped. in fact, it's probably better not to scrap them all, but to keep one settler around instead without starting a found city operation. just in case the situation changes.

**Comment by LoneGazebo** [comment]
I wonder if this is also in relation to the happiness cap being hit mid-found - if a civ goes under the settlement cap, it might cause the unit to return false on founding, thus expending it. Does this seem possible? I haven't looked at code, but a forum user pointed this out with pioneers/colonists.

**Comment by ilteroi** [comment]
yeah, that sounds logical. i was always sceptical if the happiness check belongs in CanFound(). it should be somewhere in the FoundCity operation code and just put it on hold.

**Comment by LoneGazebo** [comment]
Yeah - I think the happiness check happens in the CvPlayer::canfound check.

G

**Comment by ilteroi** [comment]
i have to correct myself. CvUnit::canFound() calls CvPlayer::canFound() and so it's entirely possible that the settle operation is canceled

**Comment by LoneGazebo** [comment]
Is this something you've fixed, or do I need to fix?

**Comment by ilteroi** [comment]
i made it so that settlers return to their muster plot when the empire is unhappy. might need some testing

**Comment by LoneGazebo** [comment]
Cool - what if we just test for unhappiness at the 'canfound' level? Then the AI won't even try (and it'll be grayed out for players).

G

**Comment by LoneGazebo** [comment]
Or perhaps we could make a bool exception for the 'foundmid/late' trait?

G

**Comment by ilteroi** [comment]
unhappiness is tested in CvUnit::canFound() also!

the issue is only what happens if an operation is set up before happiness drops into red. currently it's canceled and the settler disbanded.

in the new version, the settler should return to it's muster plot and wait for better times.

allowing pioneers etc to settle in spite of unhappiness could be an idea though. should be easy to implement

**Comment by LoneGazebo** [comment]
Sometimes I think that Firaxis designed the code to be as unfriendly as possible. Then I remember that they are human.
