### ISSUE TITLE
landmark does not increase happiness

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7201]
the description for a landmark says it gives 3 global happiness, but when you build one happiness does not change.

**Comment by silentreply** [comment]
Are empire sources already capped out by population in all cities?

**Comment by ilteroi** [comment]
how would i know?

**Comment by Mileslewis** [comment]
You can only have happiness up to the pop in each city and the overall happiness seems to just be happiness in all cities added up. this means if all cities are already at their pop in happiness, when you increase happiness it has no effect until your pop increases and you need more happiness.

Perhaps the bug here is that global happiness should just add up happiness from each source before it is distributed to each city rather than after. This would mean overall happiness would increase even if the extra happiness wasn't used in any city.

**Comment by silentreply** [comment]
I agree there is a UI issue here. You have to look through every city to see if there is any room for an extra happiness. But even with things like luxuries, AFAIK it only shows the total happiness distributed (as opposed to available). So you have to do some guesswork to determine if an extra population/city would actually receive the extra happiness from lux/landmarks.
