### ISSUE TITLE
Oil resource Issue

### ISSUE THREAD

**Issue by MilkyP** [LoneGazebo/Community-Patch-DLL#7281]
_1. Mod version (i.e Date - 12/1):_
New Official Version Dec 1st

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Oil resource amount not correct. Resource amount says I am producing 5 oil and using 8 oil on units hence -3 oil. I have no units requiring oil so something seems off or maybe i'm just missing something obvious.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5683963/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Washington_0413 AD-1993.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5683959/Washington_0413.AD-1993.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Vyyt02** [comment]
I think this sometimes happens (also with other resources as well), but is very difficult to reproduce/debug. It used to happen to me a lot last year, then it got better, but people still report this here from time to time. Sometimes restarting the game helps, sometimes something else like ending a trade deal resets the resource amount. It is very elusive. If you play unmodded VP, please post a save game. Otherwise, devs don't have much of chance to fix it.
