### ISSUE TITLE
AI having too many outdated UUs

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#7353]
AI typically spams their UU once they've unlocked it, and before it obsoletes. It isn't a problem for most civs, but there are two cases where it makes them vulnerable in later eras:

1. Bandeirantes. It's a recon unit that's meant to be sparingly trained for exploration, not mass produced. Brazil still has lots of them fortified around their cities way into Modern era, taking up precious supply.
2. UUs that don't require a strategic resource but their upgrades do, e.g. Camel Archers, Mohawk Warriors. It feels cheap oneshotting camels with gatlings and rifles when I fought against Arabia, just because they don't have enough horses to upgrade them.

**Comment by CokolwiekUnni** [comment]
This happens not only for UUs which upgrade requires a resource. Pretty sure I always see Hoplites, Pictish Warriors, and Immortals en masse in renaissance or industrial, not sure for how long because they would be wiped out because of this outdated army. Drags the difficulty very low for conquerors.
