### ISSUE TITLE
City border growth choices

### ISSUE THREAD

**Issue by CokolwiekUnni** [LoneGazebo/Community-Patch-DLL#7354]
![Civ5Screen0003 (1)](https://user-images.githubusercontent.com/75467145/103639648-f6b48080-4f4e-11eb-9dcc-5fba9eddf2b5.jpg)

The problem is rather evident. Both natural wonder and lakes ignored in favor of weak tiles. Furthermore, just after clearing a barb camp to the east, I revealed a 3 food, 1 production tile, cause the jungle had iron underneath it. Curious if border will grow there, I bought a tile next to it. 6 iron, along with higher yields isn't just enough to the governor. I removed the jungle to reveal plains iron, bison was too interesting still.

If coding different types of tiles separately will prove too cumbersome, maybe just go with the highest yields tile first? It would yield a similar results most of the time, as natural wonders, lakes, tiles with resources have the highest yields before any buildings will be constructed. Player would be allowed to even up chance of wheat against lake by building a granary and so on.

**Comment by azum4roll** [comment]
Wait, you still get jungle iron? I thought I removed all of those.

**Comment by CokolwiekUnni** [comment]
I use Milae's map. It has some things imported from the previous versions of Communitu, I believe. Either this or I don't know how to use override Assign starting plots, which I leave default as yes. So cattle or horses can be under marshes, on which in real life they obviously can't graze, not to mention time to get pasture online.
I am fine with jungle iron though. IRL the largest iron ore mine currently, Carajás Mine, is in the heart of the Amazon, Brazil is the second largest producer of iron ore worldwide, and Brazilian company Vale is the world's leading extractor of iron ore. It doesn't screw balance either.

**Comment by ilteroi** [comment]
i can remove the focus on bonus resources, but there is a lot of code there to take into account roads, rivers, terrain etc, so it won't be "highest yields first".

**Comment by CokolwiekUnni** [comment]
I suggested highest yield first because I thought it may be simple to code, if crude in philosophy. If its indeed not, then I am kinda clueless what to propose. Now it is a mess, but any change/suggestion can be dangerous. For example, removing focus on bonus resources would be beneficial in this city but would screw 90% percent of other situation. Right now I am having a lot of situation when the city complete ignores mining luxuries or bonus resources on hills, or stone which are many times 4 yields in favor of bare grassland.
Can something like focus on natural wonder first whatever the yields/other tiles are be added? I think we can agree that's the way to go.
Another thing would be mining luxuries/luxuries in general. Today I had a city preferring to grow on 3f marsh without resources to forested furs 3f 1p. When I have a hill copper/silver/gold monopoly, I always need to buy them manually or settle right next to them. Is that a desired state, considering plantation/fishing boats luxuries are nearly always a priority?

**Comment by ilteroi** [comment]
in fact there is a database value PLOT_INFLUENCE_YIELD_POINT_COST which can be adjusted - the more negative the more focus on yields. you can play around with it ...

**Comment by azum4roll** [comment]
If performance allows, each potential tile (neutral tiles) in radius 5 should be considered and given a score based on the following criteria:

- Tile yields. Culture, science and faith should be worth more than other yields. Border growth/golden age points should be worth less. 0 points on this for tiles outside radius 3.
- Potential improvement yields. We can keep it simple: farm on flat tiles, mines on hills, the respective improvement on resources. Only consider base improvement yields + pantheon bonus. 0 points on this for tiles outside radius 3.
- Civ UAs. Add some score on mountains for Inca. Not sure if we should consider trees for Iroquois and rivers for Songhai since that opens up lots of other possibilities to complicate matters.
- City Connections. Prioritize growing those tiles first, slightly.
- Natural Wonders, Strategic Resources and Luxury Resources. Add some more points for them even if they're out of radius 3.
- Distance from city. Prioritize tiles closer to city first, slightly.

After that, each tile on the path from the city to tile X should get bonus points based on the score of tile X. Doesn't have to be much, just a slight nudge to grow towards great tiles not adjacent to the borders.

Lastly, zero out non-adjacent tile scores and sort all the tiles based on score.

**Comment by ilteroi** [comment]
sounds like a good project to get your feet wet
