### ISSUE TITLE
"Missing great work of art" - solved

### ISSUE THREAD

**Issue by bentakacs** [LoneGazebo/Community-Patch-DLL#7370]
_1. Mod version (i.e Date - 12/1):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

More people reported on the forum that they have missing great works of art, and I noticed it as well in my latest game.

The culprit is the Castle, which has a great work of art slot, but the building itself is not part of the Culture Overview panel. That explains why it's missing, but when the optimize button is clicked, it's visible again (it's being moved from it).

I'm not sure if the panel can be expanded, or should it even (it can be easy to miss horizontal slide-bars).

Any ideas? This can be confusing if people are not aware of it.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by CokolwiekUnni** [comment]
I've noticed it, but I think Castles are part of Culture Overview? On far right? Was that changed? Maybe I am auto-remembering it from old versions.
I thought it's madding/bug but after searching for a while I had found it, in my case I could see a great work on the city view in the castle of my capital. However in the Culture Overview it wasn't showing in the castle (?) slot (the last one on the right). Clicking on the empty slot wasn't moving the work. When clicking on the city panel I could only view it, not move it. When clicking optimize, nothing was happening because I hadn't had any theming slots available IIRC (wonders or buildings with more than one slot) because I was authority Japan after chivalry but before archeology. Oh, I had Notre Dame so the others I had were there.
I think after museum, or had I had one more wonder with arts slots it would be moved? It was certainly there and generating culture though.
