### ISSUE TITLE
How to run the performance profiler?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7382]
@ilteroi How do I run the performance profiler? I tried attaching it to a release build and enabling CPU performance profiling, then hitting Break All after 50 turns of autoplay, but I just got this error:

![a365147ba26600597e6c79583522043e](https://user-images.githubusercontent.com/66801010/104113670-cb70bf00-52c9-11eb-8683-4ddef218b993.png)

There are reports of turn time issues...one suspected culprit is AI Rome, but may also be issues with Barbarians/City-States

**Comment by RecursiveVision** [comment]
Report on the forums:
> The last attack for Capturing cities takes so much time and freezes before the dialogue to puppet/annex/raze shows off.

There's a chance your changes may be related?

**Comment by HungryForFood** [comment]
I got a similar error, I'm guessing the callstack went outside the DLL or something?

Either way I chose the option to ignore error of this type, and it seems to be working now.

**Comment by RecursiveVision** [comment]
@HungryForFood Well do let me know of your findings when you're done :)

**Comment by HungryForFood** [comment]
Hmm, where is the option to ignore error of this type, I swear I did it just now, I can't find it again....

Anyway, I think I found something better. I'll detail it from the top.

Firstly, we launch Civ 5 in debug mode, as usual.

So, when trying to use the CPU usage tool thing in VS2019, by enabling CPU profiling:

![image](https://user-images.githubusercontent.com/22621937/104116756-7af37300-5356-11eb-955f-cf0e8e556ed7.png)

It will throw this error, presumably because it is looking for functions from the main exe instead of our DLL.

![image](https://user-images.githubusercontent.com/22621937/104116737-4a133e00-5356-11eb-93cb-e6ccfa02d235.png)

We ignore the error, and click on open details.

![image](https://user-images.githubusercontent.com/22621937/104116774-ae360200-5356-11eb-9452-0a5c99fdcb36.png)

Click on the CPU usage tab, then change current view to modules.

![image](https://user-images.githubusercontent.com/22621937/104116792-ce65c100-5356-11eb-889c-4736fb08737c.png)

Now expand the first CivilizationV_DX11.exe list, then look for CvGameCore_Expansion2.dll. Expand that dropdown, then we should now see some familiar function names.

![image](https://user-images.githubusercontent.com/22621937/104116815-fa814200-5356-11eb-8d57-9b8a80368972.png)

These should contain only our stuff which we are interested in. I haven't run the game long, but the numbers seem sensible?

**Comment by RecursiveVision** [comment]
If CvPlayer::doTurn is only taking up 3.28% of CPU I don't think my changes can be responsible, as they're largely called in doTurn

**Comment by RecursiveVision** [comment]
Although it is a large chunk of the GameCoreDLL part to be fair

**Comment by HungryForFood** [comment]
Ran until I crashed. Last call was this:

![image](https://user-images.githubusercontent.com/22621937/104118020-beeb7580-5360-11eb-84f0-9ce19b5fdaf3.png)

In CvGameCoreUtils.h. Call stack was this:

![image](https://user-images.githubusercontent.com/22621937/104118024-cc086480-5360-11eb-9606-b20926aa2462.png)

Maybe we need a null check here?

Or maybe it just ran out of memory?

![image](https://user-images.githubusercontent.com/22621937/104118148-c2cbc780-5361-11eb-9d6c-ed86a800c7ff.png)

Anyway, game ran until Renaissance, top CPU usage is as follows:

![image](https://user-images.githubusercontent.com/22621937/104118048-fa863f80-5360-11eb-92f8-1576fcddf16a.png)

The only function I remember I changed which showed up:

![image](https://user-images.githubusercontent.com/22621937/104118125-80a28600-5361-11eb-8083-4c7c659b6500.png)

I don't think that was a good test though, game was too peaceful. I'll do another test, with more warmongers and higher difficulty, and also enable BUILDINGS_THOROUGH_PREREQUISITES.

**Comment by HungryForFood** [comment]
Actually ignore the CPU usage stuff, turns out I didn't select enough of the recording session.

**Comment by HungryForFood** [comment]
CPU profiling of mostly just an AI capturing a city state in Classical. Highlighted is my function.

![image](https://user-images.githubusercontent.com/22621937/104119551-0aa31c80-536b-11eb-8be6-6387700c7f7d.png)

Test still running.

**Comment by HungryForFood** [comment]
![image](https://user-images.githubusercontent.com/22621937/104119712-4b4f6580-536c-11eb-9eb0-72671c22fccc.png)

Another city state conquest.

**Comment by RecursiveVision** [comment]
Well, good news for me is, diplomacy AI doesn't seem to be ranking high on any of those. I think that means my performance optimizations were helpful...

**Comment by HungryForFood** [comment]
I did a test by taking over an AI player, then conquering a city with the help of IGE.

Yes, it was my function.

![image](https://user-images.githubusercontent.com/22621937/104125318-e6f2cd00-5390-11eb-952d-7ab4bd6de57c.png)

Specifically CvCityBuildings::GetBuildingTypeFromClass when called by CvCity::UpdateHappinessFromBuildingClasses.

![image](https://user-images.githubusercontent.com/22621937/104125346-0db10380-5391-11eb-8bd1-70ba7f8e2c7b.png)

This line specifically.

![image](https://user-images.githubusercontent.com/22621937/104125392-59fc4380-5391-11eb-80ea-5627d89ebceb.png)

Now that I see it, I understand why. There's 4 layers of nested for loops there, all BuildingClasses ->all BuildingClasses -> each city for the player -> each building that ever existed in the city. I'll do a quick rewrite to hopefully fix it.

The next chunk of free time I have is Tuesday night my time though, so hopefully the refactor is good.
