### ISSUE TITLE
war goal logic etc

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7388]
can you explain the logic behind the war goals? i just found that WAR_GOAL_DEMAND is never set, which breaks the whole sneak attack logic ...

also, the more i look into the diplo AI the more horrified i am ... nothing against you but my feeling is you are not radical enough. let's forget about the current mess for a second and think about what would be the minimal set to replace the N non-orthogonal enums which are used now.

* MajorCivOpinionTypes, MajorCivApproachTypes, MinorCivApproachTypes
    * could become a single "CivApproachPrivate"
* WarFaceType
    * would be "CivApproachPublic"
* WarStateTypes, WarProjectionType, WarDamageLevelTypes
    * replaced by WarScore, mapped to WarState if necesssary
* WarGoalTypes, StrengthTypes, TargetValueTypes
    * WarGoal is enough?

then there is the question of approach - should it be strictly per player or are there dependencies between players? i think doing it per player is fine, then select one "war target" from all players where approach is conquest (for example).

effort aside, does this make sense? it seems impossible to debug the whole thing right now.

**Comment by ilteroi** [comment]
anyway i did some radical work on the demand logic, there is a new branch called demands, take a look and tell me what you think ... especially the casual way WAR_GOAL_DEMAND is set will probably cause issues?

**Comment by RecursiveVision** [comment]
@ilteroi No offense taken...if you want to see something horrifying, check out the logic pre my changes. Or even worse, the vanilla logic :)

Honestly it was a huge effort just to get it to where it is now, that's how badly Firaxis handled diplomacy. With my recent changes I've gotten it to a point where it at least can be understood, I think...before this current round of changes diplomacy may as well have been throwing darts at a board.

And keep in mind I've been learning C++ by trial and error and reading others' commits, so I've only reached anywhere near my current level of ability in the last few months...but I'm certainly open to further improvements.

Opinion/Approach is a divide I'd like to keep, it's useful because it provides a level of transparency/consequences for the player's actions.

WarDamageLevelTypes can probably be removed entirely, as long as some mechanism for decaying war value lost is kept for the war score calculation.

WarFaceTypes can probably be replaced as you say. Actually it's probably easier to have a public and private approach.

Work aside, WarStateTypes and WarGoalTypes could be combined into one value, and so could StrengthTypes + TargetValueTypes + ThreatTypes. Difference here is that strength assessments are used during peacetime as well.

All of these enums are vanilla logic by the way, I've just cleaned it up into something resembling sanity. If I were to write a system from scratch it certainly wouldn't be this overcomplicated.

So this would leave us with the following core enums:
Opinion
Approach (PrivateApproach and PublicApproach values)
WarGoal
StrengthType

**Comment by RecursiveVision** [comment]
@ilteroi Your current code doesn't set the demand target player, so the check to see if the existing target is valid in DoUpdateDemands() will always return false...that's easy to fix.

Additionally is it wise for the AI never to bully/demand unless they're not at war? What about phony wars?

Aside from these, this does seem easier to work with, thanks for the assistance! :)

**Comment by RecursiveVision** [comment]
@ilteroi Okay I pushed a few fixes, but generally your changes should work...I recreated the demands branch using the latest RSI, use that if you want to make further alterations...

**Comment by RecursiveVision** [comment]
I think I'll see about consolidating those approach enums, that should be tedious but not too difficult...

**Comment by ilteroi** [comment]
don't fret - you're better than the professionals at firaxis :)

**Comment by RecursiveVision** [comment]
@ilteroi Hah. Not fretting, just explaining. Thoughts on this?

> Is it wise for the AI never to bully/demand unless they're not at war? What about phony wars? GetPlayer()->IsNoNewWars() should already handle whether it's a good idea for majors...may be good for the AI to bully for additional resources if they're at war. Unless the AI isn't capable of handling multiple conflicts like this.
> 
> I notice bullying operations are blocked in the military AI if there's already an ongoing city attack operation, and that city attack operations will fail if there isn't a preferred target. I'm wondering if the AI should just declare war in these cases but not try to attack...or for failed war operations, maybe change to a demand...
> 

Also regarding demands, if you're looking for something further to work on - and since you've rewritten a fair amount of deal logic - you may want to check out the very messy code regarding how the AI responds to demands (human demands in CvDealAI, AI demands in CvDiplomacyAI, IIRC). Badly done; it's a patchwork adjustment to Firaxis's logic.

**Comment by RecursiveVision** [comment]
```
	// We're making a demand of this player
	else if(eStatement == DIPLO_STATEMENT_DEMAND)
	{
		// Active human
		if (bHuman)
		{
			szText = GetDiploStringForMessage(DIPLO_MESSAGE_DEMAND);
			CvDiplomacyRequests::SendDealRequest(GetID(), ePlayer, pDeal, DIPLO_UI_STATE_TRADE_AI_MAKES_DEMAND, szText, LEADERHEAD_ANIM_DEMAND);
		}
		// AI player
		else
		{
			// Apply diplomacy penalties!
			GET_PLAYER(ePlayer).GetDiplomacyAI()->ChangeNumDemandEverMade(GetID(), 1);

			if (IsMaster(ePlayer))
			{
				GET_PLAYER(ePlayer).GetDiplomacyAI()->ChangeNumTimesDemandedWhileVassal(GetID(), 1);
			}

			// For now the AI will always give in
			bool bValid = false;
			if (GET_TEAM(GetTeam()).canDeclareWar(GET_PLAYER(ePlayer).getTeam(), GetID()))
			{
				if (GC.getGame().getSmallFakeRandNum(10, m_pPlayer->getGlobalAverage(YIELD_CULTURE)) < GET_PLAYER(ePlayer).GetDiplomacyAI()->GetWarmongerHate())
				{
					bValid = true;
				}
			}
			if (bValid && ((GET_PLAYER(ePlayer).GetDiplomacyAI()->GetBoldness() >  7) || GET_PLAYER(ePlayer).GetDiplomacyAI()->GetMeanness() > 7))
			{
				if (m_pPlayer->GetDiplomacyAI()->DeclareWar(ePlayer))
				{
					pDeal->ClearItems();
					GetPlayer()->GetMilitaryAI()->RequestCityAttack(ePlayer,3);
				}
			}
			else
			{
				if (IsMaster(ePlayer))
				{
					GET_PLAYER(ePlayer).GetDiplomacyAI()->SetHasPaidTributeTo(GetID(), true);
				}

#if defined(MOD_ACTIVE_DIPLOMACY)
				if(GC.getGame().isReallyNetworkMultiPlayer() && MOD_ACTIVE_DIPLOMACY)
				{
					GC.getGame().GetGameDeals().FinalizeMPDeal(*pDeal, true);
				}
				else
				{
					CvDeal kDeal = *pDeal;

					GC.getGame().GetGameDeals().AddProposedDeal(kDeal);
					GC.getGame().GetGameDeals().FinalizeDeal(GetID(), ePlayer, true);
				}
#else
				CvDeal kDeal = *pDeal;

				GC.getGame().GetGameDeals().AddProposedDeal(kDeal);
				GC.getGame().GetGameDeals().FinalizeDeal(GetID(), ePlayer, true);
#endif
				if (GET_PLAYER(ePlayer).GetDiplomacyAI()->GetBoldness() >= 8)
				{
					GET_PLAYER(ePlayer).GetDiplomacyAI()->DoDenouncePlayer(GetID());
				}
			}
		}
```

Wow this is really bad...AI agreement to demands is entirely based on flavors and randomness...

**Comment by RecursiveVision** [comment]
@ilteroi I looked into it and combining MajorCivApproachTypes and MinorCivApproachTypes isn't worth the effort IMO, especially as leaders have XML values for all the approaches separately.

However I did eliminate WarFaceTypes as it was useless, and converted GetMajorCivApproach's bHideTrueFeelings argument into a separate function: GetSurfaceApproach - no need for a separate enum/memory value, honestly.

Simplifies the code :)

**Comment by ilteroi** [comment]
your change to RequestCityAttack seems a bit far-reaching to me, considering it's called from a lot of different places.

so i refactored it a bit, there is now an additional parameter which takes the place of your "easy target" flag for use in the right circumstances.

**Comment by RecursiveVision** [comment]
@ilteroi Works for me, seems like it'll work better actually. :)

**Comment by ilteroi** [comment]
i think you don't have to call it twice ... 

```
				// failed, try again but be less careful.
				if (!GET_PLAYER(eAllyPlayer).GetMilitaryAI()->RequestCityAttack(eTargetPlayer,3) && !GET_PLAYER(eAllyPlayer).HasAnyOffensiveOperationsAgainstPlayer(eTargetPlayer))
				{
					GET_PLAYER(eAllyPlayer).GetMilitaryAI()->RequestCityAttack(eTargetPlayer,0,false);
				}
```

and

```
				GET_PLAYER(eAllyPlayer).GetMilitaryAI()->RequestCityAttack(eTargetPlayer,3,GET_PLAYER(eAllyPlayer).HasAnyOffensiveOperationsAgainstPlayer(eTargetPlayer));

```

should have the same effect

**Comment by RecursiveVision** [comment]
@ilteroi Fair enough...will fix

**Comment by RecursiveVision** [comment]
@ilteroi I've been thinking about it, and I think MINOR_CIV_APPROACH_PROTECTIVE is actually pretty useless? It's meant to distinguish between wanting to befriend a City-State and wanting to protect it, but I don't think that distinction is necessary at all...

If I remove that and simply disregard the bias (or use the higher of FRIENDLY and PROTECTIVE) then I can map the CONQUEST, BULLY, IGNORE and FRIENDLY approaches to the WAR, HOSTILE, NEUTRAL and FRIENDLY approaches for major civs and simply turn it into a single enum. PROTECTIVE was the only outlier.

That said it will still take work to implement. :)
