### ISSUE TITLE
Can't build Stable even with horses tile in the working range

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#739]
![8930_2015-11-03_00001](https://cloud.githubusercontent.com/assets/1131228/10908348/08b9d844-8253-11e5-9309-64b4a13cb403.png)

**Comment by LoneGazebo** [comment]
Is another city working the tile? If so, that's the problem.

**Comment by Radost** [comment]
No it doesn't. The occupied by another city tiles are shown in dark blue.

**Comment by LoneGazebo** [comment]
I'll take a look at code (can't really see map very well on mobile).

G

**Comment by LoneGazebo** [comment]
I can't reproduce this currently, but I'll keep trying.

**Comment by Plockets** [comment]
I may be able to shed some light on this, since it is something that has annoyed me in the past. As far as I can tell, whichever city "claims" the horse tile first with it's culture is forever after considered the owner of that tile. That means, that even if 2 cities are within workable range of a specific resource tile, it is only consider owned by whichever of them claimed it, and any other cities cannot use it for building prereqs.

You can kind of tell which cities own a tile by hovering over them on the map, and seeing what resources are in the pop up, although can get murky in the case of multiple resource tiles of the same type (i.e. which ones is it claiming for itself?). I could be wrong about my assumptions here, as this is just what gibes with my untested past experience.
