### ISSUE TITLE
Slow AI expansion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7431]
so i analyzed a case where babylon stayed with 4 cities although their island had space for like 8.

turns out they simply were below the unhappiness threshold.

so from that perspective it's the right thing todo, also all their exisiting cities were avoiding growth ...

![image](https://user-images.githubusercontent.com/1358966/105627117-ff54f400-5e34-11eb-9126-17f275602c7c.png)

the real question is therefore whether something is wrong with happiness or happiness management by the AI?

**Comment by RecursiveVision** [comment]
There have been a _lot_ of complaints about Distress in particular.

**Comment by azum4roll** [comment]
It's only about distress since it's the first one on the priority list. I've seen the screenshots, the complainers have unhappiness in pretty much everything.

**Comment by R3P0FFXI** [comment]
In My experience its about the same for a player. My biggest gripe is AI unhappiness if you don't give them something when they ask for it (gift). The AI does not seem to spend gold like players do and maybe that's part of the issue. Players will spend gold if they have excess on making buildings faster or even on must have wonders.

**Comment by ilteroi** [comment]
maybe some happiness relief for smaller empires (measured in number of citizens) could help.

but then that's adding another mechanic on top of an already inscrutable system ... what happened to the guy who was working on a new happiness system based on stability points?

**Comment by RecursiveVision** [comment]
I don't think that's gone beyond the conceptual stage yet.

**Comment by RecursiveVision** [comment]
https://forums.civfanatics.com/threads/conception-of-a-new-happiness-system.665492/

**Comment by Stalker012345** [comment]
So after several games on this version, are my thoughts.

1) I think happiness is actually working as intended. Generally when I expand, I go through an unhappiness period. I have to stop expanding, build infrastructure, get cities connected, all the good stuff. This is what happiness is supposed to do, slow down expansion.

2) Once I pass this phase, I have found happiness very managable on this version (as compared to the previous one). I sometimes have to do a round of public works building in the Industrial Era if I pushed to 7-8 cities, but that's about it. I can generally keep happiness below 50%, and when playing Tall happiness is trivially easy to maintain (which no issues there, I think that's a benefit of playing Tall).


So ultimately I think the AI expansion rate is fine, is it slower than it used to be...it absolutely is, but I think that's the system working as intended. That said, I do think the game is easier as a result, the combination of slower expansion and the reduction of other bonuses has led to an easier AI overall.

**Comment by Stalker012345** [comment]
I also posted this thread in terms of happiness discussion: https://forums.civfanatics.com/threads/alternate-happiness-modmod-brainstorm.664895/

hehe but covid, and the fact happiness is more manageable on this version, derailed my initial efforts.

**Comment by ilteroi** [comment]
lockdown is good for modding :)

**Comment by ReanKW** [comment]
It seems wrong that it's working the 2f/3p horses over the 4f/3p deer when that would reduce distress by 1. Also it doesn't seem to have barracks in the city which would remove another distress. Urbanization is more forgiveable since it's Tradition, but if it's causing severe problems it should probably chill on specialists aswell.

Happiness in general feels rough, sometimes it's easy to manage and other times I'm getting absolutely wrecked by it and have to lock most of my cities to stop things falling apart.

**Comment by ilteroi** [comment]
the governor doesn't care about surplus food if the target is to avoid growth ... but yeah, that might lead to further distress? seems like a bad feedback loop.

also production choices are randomized (this is on king ...) so the missing barracks might just be bad luck.

**Comment by azum4roll** [comment]
In my experience, 7-9 cities with Progress/Authority is very manageable. The amount of happiness actually doesn't matter late game - it's always capped to your non-puppet population since there are so many happiness sources. Which makes urbanization in cities with high needs unhappiness is the only _excess_ unhappiness. You can easily get at least 50% happiness if you stop working all specialists. Not sure if it's a good thing, but it's how it works now.

**Comment by ilteroi** [comment]
it looks like there is a mismatch between the logic for stopping growth and the logic for stopping expansion ... let's see

**Comment by NewFellow** [comment]
I'd say that this problem of slow expansion is a really big problem due to the fact that the game has become so much easier because of it. In the old days you had to fight for land and had to be on your toes in the 'expansion phase' and really think carefully on how to go about getting the land you wanted. Today, it's like a smorgosboard of land, where I can just relax and pick whatever of my own choosing (that's how it feels).

I remember how I used to think hard on how to get my resource 'monopoly'. Today I don't even give it a thought. I just know that I'll get it and I also know that I might be able to forward settle somebody else and take a huge chunk of what would had been their monopoly.

I always get my 6-7 cities minimum (mostly depending on how I feel) and there's no rush or sense of urgency at all. Look at the _Aztecs_ in this screenshot. They got 2 cities (!) because they didn't seem to care. They are blocked by this mountain chain, but that matters little - in the old days they'd forward settle me and my city of 'Old Sarai' would have been replaced with an Aztec city - that's 100 % sure! Maybe they'd also built another city above _karakorum_ much earlier than after 4000 years! (it's razed in this screen).

This slow AI-expansion makes the game much easier because my 6-7 cities (or more) compared to, let's say, '4-5 cities before' gives me a huge _momentum_ - and my war engine has so much more 'fuel' to pummel the AI (bigger armies, more yeilds etc.). Also I can build those cities safely without annoying or upsetting the AI too much - since he doesn't expand - it takes a while until I grow _into_ him (bordertension is easier to avoid).
 
![image](https://user-images.githubusercontent.com/20144751/105881859-4f82b080-6005-11eb-9652-6356b447fb6e.png)

**Comment by ilteroi** [comment]
also early wars are a problem ... AI does not build settlers during wartime. maybe that needs to be changed.

**Comment by azum4roll** [comment]
Perhaps you should settle more in huge maps like that... but in standard maps AI only settles 6-7 cities max before Astronomy and all big islands are filled up as expected. They don't blatantly forward settle very early anymore like previous versions, which is good play for all non-warmongers since those cities are rarely defensible.

**Comment by NewFellow** [comment]
> also early wars are a problem ... AI does not build settlers during wartime. maybe that needs to be changed.

I had the perfect save describing my game even better... _and an early war was in this game not the problem_, since they had yet (600 b.c) to declare their _first_ war against the Koreans. Looking at this screenshot down below, we can se how I'm about to settle my fifth city 'Old Sarai' to the west of 'Beshbalik' - and the Aztecs still has only two cities! In the old days Old Sarai would had been Aztec land, but for some reason the AI just stop expanding and let me choose whatever I want.
![image](https://user-images.githubusercontent.com/20144751/106019444-f37e6180-60c2-11eb-9933-7f2023bcc01f.png)

**Comment by ilteroi** [comment]
it seems much better now, wait for the next version ...

**Comment by NewFellow** [comment]
> it seems much better now, wait for the next version ...

You deserve a 🥇 I can hardly wait. :)

**Comment by ilteroi** [comment]
ok maybe not ... this is turn 90:

![image](https://user-images.githubusercontent.com/1358966/106112856-0ee27e80-614e-11eb-831b-0415206ba409.png)

@LoneGazebo : they built 4 wonders, but no settler ...  in PRE settler is always highly valued but not so much in POST.

074, Russia, Moscow, PRE: Unit, Settler, 11100, 4
074, Russia, Moscow, PRE: Building, Great Library, 7700, 11
074, Russia, Moscow, PRE: Building, Granary, 4118, 1
...
074, Russia, Moscow, POST: Building, Granary, 1695, 1
074, Russia, Moscow, POST: Building, Great Library, 1469, 11
074, Russia, Moscow, POST: Unit, Settler, 1319, 4
074, Russia, Moscow, SEED: 3480119261507362663, CHOSEN: Wonder, Great Library, NoRush, ERA: 1, TURNS: 11

086, Russia, Moscow, PRE: Unit, Settler, 11300, 3
086, Russia, Moscow, PRE: Building, Writers' Guild, 5360, 6
086, Russia, Moscow, PRE: Unit, Worker, 4830, 2
...
086, Russia, Moscow, POST: Building, Writers' Guild, 4103, 6
086, Russia, Moscow, POST: Unit, Settler, 2260, 3
086, Russia, Moscow, POST: Building, Amphitheater, 1935, 6
086, Russia, Moscow, SEED: 7756223271603392581, CHOSEN: Wonder, Writers' Guild, NoRush, ERA: 1, TURNS: 6

093, Russia, Moscow, PRE: Unit, Settler, 11300, 5
093, Russia, Moscow, PRE: Building, Parthenon, 10475, 21
...
093, Russia, Moscow, POST: Unit, Settler, 1984, 5
093, Russia, Moscow, POST: Building, Amphitheater, 1810, 8
093, Russia, Moscow, SEED: 4775666482560323582, CHOSEN: Building, Amphitheater, NoRush, ERA: 1, TURNS: 8

**Comment by Stalker012345** [comment]
Just showing a counterexample. Currently Washington has 5 cities, Askia has 6. I have 4 and I'm drowning in unhappiness (with all growth now stopped). So sometimes happiness really does just stop your expansion.

![image](https://user-images.githubusercontent.com/20593976/106396240-5ece7900-63cc-11eb-8563-1b7187a2e122.png)

**Comment by Stalker012345** [comment]
Also...this is the other reason its not always good to expand quickly. The AI is a lot more cutthroat on its military pushes now.

![image](https://user-images.githubusercontent.com/20593976/106397421-ec14cc00-63d2-11eb-9667-628c21069f67.png)

**Comment by azum4roll** [comment]
Ouch. Deity sure is tough. You shouldn't be unhappy if you were playing in a lower difficulty.
