### ISSUE TITLE
1/15 - New Great Musicians getting "blocked", from More GPs Forum Thread

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7448]
_1. Mod version (i.e Date - 12/1):_
1/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm highlighting this from the More GPs thread on the main forum. Apparantely there is a bug where when a GM is born, the program thinks all the remaining GMs in the list have already been born. The effect has been to hugely reduce the number of Great Musician works that are available.

The link to the post is below.

_4. Steps to reproduce (optional):_
[URL="https://forums.civfanatics.com/threads/more-gps-module.665154/page-4#post-16015241"]More GPs Module[/URL]

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by GLop4** [comment]
It seeems that is true for other GPs.
In my last test game (1-15), 'no name' GGs appeared very early in the game.

**Comment by psparky** [comment]
Further info:

I demonstrated the problem using great musicians and will specify those below, but the problem probably applies to all types of great people.

The recently added module MoreGP doesn't work properly. Only one of the added great musicians can be born. The pre-existing GMs work normally.

A table of the names (TXT_KEYS) of great people already born is maintained and is handled by functions in CvGame, isGreatPersonBorn, addGreatPersonBorn and removeGreatPersonBorn. This table is checked when a new great person is born to avoid getting the same name twice. The functions use a hash function for efficiency.

The MoreGP team used text keys in the form TXT_KEY_GREAT_PERSON_M__xxx, where xxx is a number, to name the new musicians. These names all map to the same hash value. The result is that once one of these GM is born and its hash value added to the table, all the others also appear to have been born as isGreatPersonBorn returns true.

It may be that the MoreGP team will need to change the naming scheme. Before that, however, could one of the developers please take a look at the code to verify that it is working as expected. If it is working correctly, are there any small adjustments that could be made so that the new names would work correctly.

Thank you
