### ISSUE TITLE
2/4 HF - Hard Freeze on Next Turn Button

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7510]
_1. Mod version (i.e Date - 12/1):_
2/4 HF

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm getting a hard freeze where I cannot hit the next turn button. In previous versions I generally can get around this by moving a unit or changing up a build order, but this one is hard. Even going back a few turns on autosave and replaying it, it still freezes up.

Save game and logs attached.

_4. Steps to reproduce (optional):_
[Maria I_0119 AD-0100.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6007764/Maria.I_0119.AD-0100.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6007772/Logs.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
sorry but crashes on load for me as usual. the savegame system is unfortunately broken beyond repair.

**Comment by Serpens66** [comment]
What are the known problems that can cause such a freeze? 
(Ijust searched the issues for all "freeze", but most of them were closed with "cannot reproduce", which I understand, because these freezes are very hard to reproduce, since they appear "randomly")

I recently learned that "gDLL->GetScriptSystem()" that is used to send an Event from DLL to Lua, can cause such a freeze. Especially if it is near to an autosave, which is often the case during AI/Barb turns: https://forums.civfanatics.com/threads/tablesaverloader-for-persisting-lua-table-data-through-game-save-load.442249/
I implemented the code from Pazyryk into my DLL and not only the first autosave can freeze the game, also any other autosave can randomly cause the freeze (confirmed by adding logs).

So how to call "gDLL->GetScriptSystem()" savely without freezing?

With this post I hope to help to solve this problem on the one side and on the other side I would get information to fiy this problem for my own DLL.

**Comment by ilteroi** [comment]
well, i don't know the details but if you have a deadlock it might be due to the "gamecore lock".

check the code for 

gDLL->ReleaseGameCoreLock();

calls and see if that is done in your case.

**Comment by Serpens66** [comment]
thank you very much for your response. Is the code of the function gDLL->GetScriptSystem() accessable? Because as I and Pazyryk in my link wrote, this single command is the one causing the freeze, if you call it at the wrong time (I put logs before and after this line, to be sure).

If you dont have the time to read Pazyryks full post, just skip to "How to catch a game save using a dll mod". This is what I did. And my assumption is, that not only this specific case described there is causing freezes, but also other cases, where gDLL->GetScriptSystem() is called, can lead to such a freeze. I already had such freezes very rarely, before I added this "save"-event (although I wasn't aware that they may be related to gDLL->GetScriptSystem(). All freezes happen randomly and are not savely reproducable, seems like a run-condition I guess.)

And I guess it is very likely, that also Community patch suffers/suffered from this.
Eg. this issue shows, that the freeze happend in a round of autosave (assuming it is set to "every 5 rounds"): https://github.com/LoneGazebo/Community-Patch-DLL/issues/3884 
And here a freeze was solved, although I don't see what the problematic code nor the solution was =( https://github.com/LoneGazebo/Community-Patch-DLL/issues/3901#issuecomment-361759748 do you have more info what "overloaded the lua hook" means?
