### ISSUE TITLE
Trade exploit?

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#759]
From Wodhann:

"Sometimes when someone comes up with a trade, like a luxury trade offering gold, you can basically change the amount of gold per turn to whatever you want (as in their entire output) and they will accept.

They will only do this when you click "what do you want for this?". They will not do it if you remove the gold per turn offering and input a new one, you have to change the amount in the one that's already being offered by the AI and then hit accept."

I'm out today and tomorrow, but this needs testing to confirm.

**Comment by DuckZero** [comment]
I confirm that I also have this problem with CP or CBP.

If the AI offers gold or GPT after you click "what do you want for this" you can change their number to whatever you want (like 99999) and after hitting accept you take everything from the AI.

**Comment by LoneGazebo** [comment]
I can't replicate this on the latest version. Are you on the latest version?

**Comment by DuckZero** [comment]
Yes latest 11/17 CBP-NoEUI (no other mods) some hours ago.

I took everything from the AI for 1 horse.

**Comment by ilteroi** [comment]
i use INT_MAX now in all relevant places and take care to check the return value. let's see how it goes.

also found a bug in embassy valuation :)

**Comment by LoneGazebo** [comment]
Bugs! Never! :)

**Comment by ilteroi** [comment]
so i've been looking at the deal log, which nowadays contains the value of each traded item. noticed some strange things, posting them here for your two cents:

> 174, Poland, Arabia, Open Borders Exchange
> 174, Poland, Arabia, , , Open Borders Trade, (value 168 - raw)
> 174, Arabia, Poland, , , Open Borders Trade, (value 88 - raw)

shouldn't go through because of the large disparity?

> 174, Indonesia, Arabia, Open Borders Exchange
> 174, Indonesia, Arabia, , , Open Borders Trade, (value 176 - equalized)
> 174, Arabia, Indonesia, , , Open Borders Trade, (value 198 - equalized)

why did it contain the raw values before and now the equalized values? why are the equalized values not equal?

> 175, Polynesia, Byzantium, , , ***** GPT Trade: 5 *****, (value 260 - raw)
> 175, Polynesia, Arabia, , , ***** GPT Trade: 2 *****, (value 119 - raw)
> 175, Arabia, Indonesia, , , ***** GPT Trade: 12 *****, (value 624 - raw)

haven't looked at the current formula, but i think GPT should be "cheaper" than cash because of the risk of default. so maybe value = GPT * turns * 70%?

**Comment by LoneGazebo** [comment]
It is - currently sits at 80%/

**Comment by LoneGazebo** [comment]
Not sure why those values are being flip-flopped, though I do know that 'equal' values aren't 100% equal because of the margin of error in the DLL for deals between humans/AI.

G

**Comment by ilteroi** [comment]
- the values don't have to agree exactly, that's true. but 168 to 88 is almost 100% off

- the "equalized" values should be exactly equal as they are (buyer price + seller price)/2

- the way it currently works, GPT is apparently not discounted. on the contrary, it's worth a premium. 2 GPT for 50 turns is apparently worth 119 gold to the AI, which is 119% instead of 80%. just took a look at the code and let me phrase it like this, i'm not in the least surprised that it doesn't work

**Comment by DuckZero** [comment]
I don't know if the new version is supposed to fix this, but it hasn't.

Also the large number of 99999 I mentioned was just an example. You can still get whatever amount you want from the AI with normal numbers.

This bug must also be pretty old, maybe CP/CBP has this from when I started playing 6+ months ago. 

It is very easy to reproduce, I don't think a save is even needed.

The steps are:
- Initiate a trade with AI
- Add 1 horse in you side 
- Click "What do you want for this"
- If it is gold or gpt, directly change their number. Don't "touch" other items if he offers them as well. If you remove other items he offered, it does not work.
- Press Accept, and you get all of it.

**Comment by LoneGazebo** [comment]
Ilteroi worked on this, said it was theoretically fixed, but I'll page him. I'm out of pocket til next week.
G

**Comment by DuckZero** [comment]
I don't think this is vanilla. Never been able to trigger it there.

**Comment by LoneGazebo** [comment]
Sorry, by vanilla I mean a vanilla issue that was revealed by AI improvements in the CP.

**Comment by ilteroi** [comment]
cannot reproduce according to the steps outlined above ...

![image](https://cloud.githubusercontent.com/assets/1358966/11320053/0a038a94-908e-11e5-813a-64ec99322960.png)

**Comment by LoneGazebo** [comment]
I can't either, but we should try EUI and no-EUI versions. I've tried both in the past, but not with the most recent version.

**Comment by DuckZero** [comment]
Ok savegame. This was played with CPP-NoEUI (probably 11/19), but it loads and triggers bug with 11/20 fine.

http://s000.tinyupload.com/index.php?file_id=08762628556951280853

After it loads, initiate trade with germany offer 1 horse etc.

**Comment by LoneGazebo** [comment]
Interesting. Must be something to do with how EUI handles trade modifications. We'll see if the Lua reveals anything.

**Comment by ilteroi** [comment]
i'll leave that to you ... i've got no clue about lua

**Comment by Edaka** [comment]
From Gidoza: "Previously, if the AI offered gold for something, I could change his gold value to anything and he would accept. Now, the AI will sometimes say no, and then offer the exact value I put [after pressing 'What do you want for this'?], I hit accept, and now he takes it."

This could still be linked to the no-EUI version somehow since Gidoza admittedly plays with it. Currently waiting for a save.

**Comment by LoneGazebo** [comment]
Tried to reproduce with no-EUI. Cannot.

G
