### ISSUE TITLE
[Feature request] Science Points row in Goodyhuts table

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#7731]
_1. Mod version (i.e Date - 4/14):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Would it be possible to add a Science Points row in the GoodyHuts table which work the same way as "Cuture", e.g. granting the player a certain amount of Science points when entering the Goddy Hut?

Would like to test the effect of this in stead of the normal way of gaining an entire tech (Tech column)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by IanE9** [comment]
Current implementation scales received science points by era which may or may not be the best behavior due to the way that tech costs actually scale. For instance a goody hut that would normally yield 60 science points (near cost for bottom ancient techs) would only yield 180 science points (bottom medieval techs cost 525) for a civilization that has entered the medieval era.

An alternative implementation to consider is to receive a portion of science related to the cost of the most expensive tech currently available for research.

**Comment by skodkim** [comment]
Cool. Looking forward to it
