### ISSUE TITLE
MOD_SERIALIZE_READ/WRITE?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7905]
I notice that a lot of whoward/Putmalk added memory variables have used this format:
```
	MOD_SERIALIZE_WRITE(saveTo, readFrom.m_bTradeUnitRecalled);
```

as opposed to the standard:
```
	saveTo << readFrom.m_iCircuitsCompleted;
	saveTo << readFrom.m_iCircuitsToComplete;
	saveTo << readFrom.m_iTurnRouteComplete;
```

And the same goes for MOD_SERIALIZE_READ

Why not pick one and standardize it? Is there an advantage to doing it this way?

**Comment by IanE9** [comment]
I see not realistic advantage to using a macro here.

The only distinction being made by using one is to make it clear what data is related to mods which would be useful for comparability with vanilla saves, but the engine doesn't even support that behavior by default as is.

Using bit shift operators is less characters per line which is easier on the eyes and the compiler.

**Comment by ilteroi** [comment]
no difference, they are functionally identical. both are fine.

the real issue are those stupid firaxis AutoVariable members.

**Comment by LoneGazebo** [comment]
Would replacing auto variables have any performance benefits? I’ve wondered about that. Seems overengineered.

**Comment by IanE9** [comment]
> 
> 
> Would replacing auto variables have any performance benefits? I’ve wondered about that. Seems overengineered.

It would reduce memory footprint for nearly every object in the game which would probably offer at least a tiny benefit to avoiding cache misses.

FAutoVariable<int, CvCity> consumes 12 bytes instead of 4...

**Comment by IanE9** [comment]
CvUnit is probably where the most gains would be made from removing the usage of auto variables. CvUnit has 313 auto variable members, 313*8 = 2.504kb reduction per unit.

**Comment by HungryForFood** [comment]
How do you see the memory consumption? Visual studio's debug mode?

What is the possible benefit of the FAutoVariable method, if any?

**Comment by IanE9** [comment]
The sizeof() operator will return the size of any defined type in bytes. Visual Studio (at least on newer versions) will let you examine the result of a sizeof expression in the editor by just hovering over it for a moment. If it's not cooperating though you can always go into debug mode and get the result of the expression some other way.

Note that when members are laid out in a class the size of that class is not always going to be the sum of the size of the members sizes due to alignment, but it shouldn't ever be smaller than that sum unless bit-fields are involved.

I haven't worked with FAutoVariable so its exact purpose isn't clear to me, but examining it suggests that most of what it's good for is really heavy duty debugging. Otherwise it looks to me like it just does automatic serialization for saves and such.

Maybe someone with more experience working with FAutoVariable could enlighten us though?

**Comment by ilteroi** [comment]
well, AutoVariables might have some use for debugging if FINAL_RELEASE is not defined. however we can't even build then, so i've never enjoyed that benefit ... in fact the effect is the opposite in practice since it's a bit annoying to inspect an AutoVariable in the debugger.
