### ISSUE TITLE
LUAAPIEXTN vs. static int (lua_State *L);

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7906]
Same as the previous issue: what's the deal with the added functions using this format as opposed to the static int one? Is there an advantage to do it this way? Should we not standardize this?

**Comment by IanE9** [comment]
LUAAPIEXTN unwraps to the same signature which makes it functionally identical, but there are advantages to be had by using a macro here.

The present behavior offered appears to be that it prepends an 'l' to the symbol name and accepts a varargs parameter. The varargs parameter doesn't actually impact the signature in any way are useful as they preserve the information about what the Lua function is actually supposed to receive.

Realistically the macro may be more useful if only because it may make it easy to change a lot of behavior at once without having to change potentially hundreds of lines, however the mixture of the two  ways this is done makes that a moot point right now.

Better would be to use some template wizardry to accomplish the same behavior offered by macros if only because doing so would remain within the language and make debugging easier but as it is the macros are already in place and aren't really doing any harm.

Standardization of using LUAAPIEXTN and its sister macros LUAAPIIMPL and LUAAPIINLINE makes the most sense to me.
