### ISSUE TITLE
Too much gold from ancient ruin with new version

### ISSUE THREAD

**Issue by mcymsb** [LoneGazebo/Community-Patch-DLL#7950]
_1. Mod version (i.e Date - 4/14):_
5 28

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
It's not an error but the latest patch seems to give too much gold from ancient ruins

It used to be 50-140  but now it gives like 160 - 280 which is huge scale difference comparing how much culture or production you get from ancient ruins

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by IanE9** [comment]
Not a bug, but maybe could use tweaking.

Your experience is caused by gold rewards from ruins now being scaled by game speed where as previously they were not scaled at all. Game speed yield scales are set on a per yield basis so the gold scale is likely different from culture & production.

Is 160-280 unreasonable for whatever game speed you're playing on?

**Comment by mcymsb** [comment]
> Not a bug, but maybe could use tweaking.
> 
> Your experience is caused by gold rewards from ruins now being scaled by game speed where as previously they were not scaled at all. Game speed yield scales are set on a per yield basis so the gold scale is likely different from culture & production.
> 
> Is 160-280 unreasonable for whatever game speed you're playing on?

Oh I see now it scales with game speed? But culture and production didn't.  I always been playing epic and the only difference is updating to 528 version.

**Comment by IanE9** [comment]
> 
> 
> > Not a bug, but maybe could use tweaking.
> > Your experience is caused by gold rewards from ruins now being scaled by game speed where as previously they were not scaled at all. Game speed yield scales are set on a per yield basis so the gold scale is likely different from culture & production.
> > Is 160-280 unreasonable for whatever game speed you're playing on?
> 
> Oh I see now it scales with game speed? But culture and production didn't. I always been playing epic and the only difference is updating to 528 version.

That'd be why it seems unusual. Gold is the only new thing scaling, both culture and production had already been scaling.
I'm pretty sure culture, gold, and production yields from ancient ruins should all be 150% on epic.

**Comment by mcymsb** [comment]
> > > Not a bug, but maybe could use tweaking.
> > > Your experience is caused by gold rewards from ruins now being scaled by game speed where as previously they were not scaled at all. Game speed yield scales are set on a per yield basis so the gold scale is likely different from culture & production.
> > > Is 160-280 unreasonable for whatever game speed you're playing on?
> > 
> > 
> > Oh I see now it scales with game speed? But culture and production didn't. I always been playing epic and the only difference is updating to 528 version.
> 
> That'd be why it seems unusual. Gold is the only new thing scaling, both culture and production had already been scaling.
> I'm pretty sure culture, gold, and production yields from ancient ruins should all be 150% on epic.

Hmm 22 culture and 20ish production doesn't seem quite enough tbh if the gold from ruins ranges from 150-250ish in the very beginning.

**Comment by IanE9** [comment]
I just ran a test game on epic as the Shoshone and measured 45 production and 22 culture from ruins. Both are the appropriate values with production's base being 30 and culture's base being 15. That isn't to say that the values couldn't use tweaking though.

The culture value is indeed rather low but it should be noted that culture also has an additional bonus scale from ruins related to the number of policies a player has unlocked. The formula for this is ``bonus multiplier = floor(num policies / 2)`` or a flat ``bonus multiplier = 1`` if the multiplier would otherwise be unfavorable. The flooring of the multiplier may be an unintentional side effect of integer math, but the code for this can be found on line 13736 in CvPlayer.cpp

I'm not sure why this bonus exists but in practice it should mean that a player receives an additional 100% bonus culture from ruins for every 2 policies they've unlocked after the first 2. Perhaps the bonus should be adjusted to provide a 50% culture bonus for every 1 policy after the first 2 so that this bonus comes into play sooner.

**Comment by azum4roll** [comment]
I'm getting 180 gold on turn 2 in Standard speed.

**Comment by IanE9** [comment]
> 
> 
> I'm getting 180 gold on turn 2 in Standard speed. And then another gold ruin with much less gold later on.

The exact way that gold value is calculated is not clear to me, but glancing at the code suggests that it is highly random so that doesn't exactly shock me. See line 13595 of CvPlayer.cpp for the exact code.
