### ISSUE TITLE
Not Showing Happiness Breakdown (EUI error)

### ISSUE THREAD

**Issue by vetox20** [LoneGazebo/Community-Patch-DLL#8007]
_1. Mod version (i.e Date - 4/14):_

06-07 and 06-07-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

When highlighting the happiness indicator, at top bar it either shows faith per turn , golden age points or gold per turn
[EUIError.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6617996/EUIError.zip)
. (depends on what was highlighted last). When clicking the unhappiness meter, it opens up the Economic Overview.

I verified game integrity, made sure cache was clear. did a fresh install of Vox, made sure EUI was in correct folder in DLC. 

_4. Steps to reproduce (optional):_

Highlight the happiness/unhappiness at top bar with EUI enabled.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by CyberPhy** [comment]
I am also getting this problem 
In the LUA I'm getting an error ` Runtime Error: C:\Users\steam\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\TopPanel.lua:1213: Instance does not exist.
`

**Comment by LoneGazebo** [comment]
Yes

**Comment by LoneGazebo** [comment]
I wonder what broke lua instance?

**Comment by IanE9** [comment]
It was when I made the commits using static_cast instead of C style cast and then introducing a bunch of specializations. The behavior before that was actually broken as well because it was accepting integers from lua and casting them to pointers. I guess they were also defaulting to 0 if not passed in which gave it the illusion of working as intended. You wouldn't even have been able to use the optional arguments unless you knew the addresses of the cities you wanted to check because of that.

Apparently this bug also exists in the original Civ 5 DLL as well.

**Comment by IanE9** [comment]
@LoneGazebo I feel I've done a poor job explaining this so I've made an example.
This was done in FireTuner on the original Civ 5 DLL.
```
> player = Players[Game.GetActivePlayer()]
> capital = player:GetCapitalCity()
> player:GetUnhappinessFromCityPopulation()
900
> player:GetUnhappinessFromCityPopulation(capital)
900
> print(capital.__instance)
 InGame: userdata: 79790580
> player:GetUnhappinessFromCityPopulation(0x79790580)
200
```
As you can see when we initially call ``GetUnhappinessFromCityPopulation()`` we get a value of ``900``. Passing ``capital`` as the first parameter should fulfill the ``pAssumeCityAnnexed`` argument which should change the value. However when we do pass ``capital``, we observe no change. This is because the argument it actually wants is the **address** of a city rather than a lua instance of a city. We can get the address of our capital by examining the ``__instance`` field of the instance. Once we do we find that the address is ``0x79790580`` so we pass that in we can see that the value actually does change as we originally anticipated.

**Comment by vetox20** [comment]
Just FYI, tested 6-7-2 on my end and the issue is resolved, if that helps

**Comment by LoneGazebo** [comment]
Yeah, I think it is sorted now. @IanE9 that’s a thorough explanation, and makes sense.
