### ISSUE TITLE
city needs

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8045]
very late game, but is this plausible?

all russian cities are waaaay over the needs threshold ...

![image](https://user-images.githubusercontent.com/1358966/121858676-24200a00-ccf7-11eb-8685-5b264fe86975.png)

![image](https://user-images.githubusercontent.com/1358966/121858731-3601ad00-ccf7-11eb-9663-0cd0cd8f1033.png)

**Comment by SolicShooter** [comment]
Have they build the food corporation? That has typically reduced my unhappiness by a lot.

**Comment by LoneGazebo** [comment]
Repeat public works?

**Comment by ilteroi** [comment]
i believe something is broken with happiness.

![image](https://user-images.githubusercontent.com/1358966/121906000-f94fa900-cd2a-11eb-8c59-fa598d7f6fc1.png

(note that i'm using a modified version of infoaddict that shows the 'raw' uncapped happiness).

and this is the zoomed view - babylon had 11k (!!!!) happiness at one point.

**Comment by LoneGazebo** [comment]
@IanE9 fixed some database issues. On the latest?

**Comment by IanE9** [comment]
I've played a view games since the fixes and had no issues. What version was this on?

**Comment by DemaciaMaggotPie** [comment]
This clearly is an old beta - Your Empire Needs are basically nonexistent, even though they should include many things like empire size and Is Capital.

**Comment by ilteroi** [comment]
new game with all the latest

![image](https://user-images.githubusercontent.com/1358966/121960969-1a35ef80-cd67-11eb-8d70-ba67ddb2597f.png)

happiness still regularly over 1k

**Comment by IanE9** [comment]
Oh dear. That doesn't seem right at all. Can we get a breakdown of happiness sources from one of the happiest cities during one of a peaks?

**Comment by ilteroi** [comment]
![image](https://user-images.githubusercontent.com/1358966/122003147-fac4b400-cdb2-11eb-81fc-cdc22fe53abf.png)

**Comment by DemaciaMaggotPie** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/1358966/122003147-fac4b400-cdb2-11eb-81fc-cdc22fe53abf.png)
> 
> these modifiers below -100 look suspicious?



Lots of public works could technically get the needs very low.
What I'm worried about is the lack of Empire Size in the breakdown of "Needs Factors".

**Comment by IanE9** [comment]
I just checked and ``m_iEmpireNeedsModifier`` is specifically for the empire size need. Public works change this value by -10 and when it dips below the standard threshold, the entry in the tool-tip merely disappears which explains why it wouldn't be present here.

How exactly does info addict collect this data? I've done some testing and observed that functions like ``getUnhappinessFromGoldNeeded()`` do not apply any limiting to the resulting threshold which is not accurate to what the game actually does. Because of this, need modifiers that overcome the threshold will actually produce negative unhappiness values. If these are being negated and summed, a city with a significant number of public works could easily give off the image of producing extreme amounts excess unhappiness where there actually is none.

![ex](https://user-images.githubusercontent.com/7848638/122104592-0e811200-cdd5-11eb-8d61-2f379d9b26cc.PNG)

**Comment by ilteroi** [comment]
my infoaddict uses GetHappinessRatioRawPercent() where the regular one uses GetExcessHappiness(), in turn these numbers are based on sum(GetLocalHappiness()) over all cities and sum(getUnhappinessAggregated()) over all cities.

also minor points: wasn't there a push to put (apple)+(hammer) in the tooltip instead of (apple) / (hammer)?

**Comment by IanE9** [comment]
>
> also minor point: wasn't there a push to put (apple)+(hammer) in the tooltip instead of (apple) / (hammer)?

There was, I remember this. It's still probably a good idea.

Are any transformations actually being applied to the result of ``GetHappinessRatioRawPercent()``? If none are being performed, that would partially explain the incredibly high values because what you're actually getting is a percent value, not an absolute value. In fact it tells you nothing about the exact number of happy or unhappy citizens in the nation other than that there are a whole lot more happy citizens than unhappy citizens. If an empire had 20 happy citizens and 1 unhappy citizen, then ``GetHappinessRatioRawPercent()``would give a value of 1000 for that empire despite it being extraordinarily small for an empire on turn 470.

Less related, is the calculation``GetHappinessRatioRawPercent()`` is performing even correct?
```cpp
int CvPlayer::GetHappinessRatioRawPercent()
{
	int iUnhappyCitizens = getUnhappinessFromCitizenNeeds();
	int iHappyCitizens = getHappinessFromCitizenNeeds();
	return ((iHappyCitizens * 100) / max(1, iUnhappyCitizens) / 2);
}
```
I'm fairly sure this isn't a ratio calculation. The ratio of one thing to another is just ``a`` over ``b``. Why are we dividing by 2?

Ratio percent would just be ``(a / b) * 100`` but in order to preserve correctness for integer math we can write it as ``(a * 100) / b``.

I assume the intent was actually to calculate the percentage of happy citizens because an empire with 1 happy citizen and 1 unhappy citizen would result in ``(1 * 100) / 1 / 2`` which gives a proper 50%. This being correct though is only luck because the total citizens is 2 in this scenario.

If an empire has 98 happy citizens and 2 unhappy citizen, then the percent happiness of the empire is (not so shockingly) 98%, but by this function we get ``(98 * 100) / 2 / 2`` which yields 2450%...?

Percent happiness is just ``(happy citizens / total citizens) * 100``. We can once again write this as ``(happy citizens * 100) / total citizens`` to preserve correctness for integer math.

**Comment by ilteroi** [comment]
i'm aware that it's a percentage value and may have minor rounding errors.

but the question remains, should it really be the case that happiness is so "easy" that you have effectively zero unhappy citizens? is it good design that modifiers can be stacked indefinitely?

unfortunately it's too late for major changes now ...

**Comment by IanE9** [comment]
A city with -120% needs modifiers requires 8 public works to be built assuming it's not benefiting from other various sources. That's a rather large investment just to minimize unhappiness. Judging by the screenshots you've posted, it looks like the AI may actually be attempting to hit 0% needs in all cities.

Maybe the AI is at fault for giving so much priority to this? I can't imagine players are trying to minimize their needs like this and yet they're still managing to beat the already handicapped AI. The AI would probably play better if they weren't perusing 0 unhappiness in all cities anyway because it would give them more opportunities to build things that actually further their progress towards a victory condition.

**Comment by ilteroi** [comment]
yeah excessive public works might be a factor ... if that all works as designed it's also fine by me

**Comment by ilteroi** [comment]
![image](https://user-images.githubusercontent.com/1358966/122539335-c73e8f80-d027-11eb-9b7a-46b916d45f21.png)
