### ISSUE TITLE
[Feature Request] Block turn progression, if spies are not allocated

### ISSUE THREAD

**Issue by SolicShooter** [LoneGazebo/Community-Patch-DLL#8046]
With the Spy rework, spies more often need to be reassigned manually. It would be nice to be prompted that spies are still not assigned if wanting to end a turn. This is similar to the picking build order/moving an unit/selecting a culture policy/voting in world congress prompts. Frequently, I have caught myself not assigning them for a few turns when they have returned from a mission and the wasted potential sucks.

**Comment by RecursiveVision** [comment]
I don't think this idea is workable because it could create situations where you have more spies than cities to place them in, in some rare scenarios, and this would freeze the game.

Perhaps a notification or something would work, though.

**Comment by SolicShooter** [comment]
Is it possible to make it conditional then? I'm assuming that number of spies is already calculated somewhere, since some things depend on spy number. If discovered (ideally) city count is also calculated somewhere, it shouldn't strain performance by a lot I am guessing.

A notification wouldn't do too much for me, since you are already made aware of how your mission has went. Maybe if that directly openend the spy screen, it'd be less of an issue. 

With the prior spy system you only had to reissue spies with every spy death or city transferring ownership, so significantly less. The micro is a lot more substantial now with missions not automatically repeating, except if you put them in a city state.

**Comment by IanE9** [comment]
Having the player's turn blocked _only once_ when one or more spies is made available would probably help a lot without soft locking the player while also allowing the player to keep their spies unassigned if they feel it's to dangerous to send a spy to a foreign city without any domestic cities available. Basically just notify the player that a spy has become available and require that they visit the espionage screen, but once they've done so permit them to ignore all unassigned spies for every following turn until a new spy becomes available again.

The digit on the espionage screen could also be made a different color or to pulse in size in order to better draw the player's attention to it. That alone would probably help a ton with players failing to recognize that they have spies available.
