### ISSUE TITLE
how to increase width of tooltip windows?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8076]
new comfort feature:

![image](https://user-images.githubusercontent.com/1358966/122711650-ce051680-d262-11eb-938c-e6409c24fe20.png)

we now include the number of involved cities for each type of religious pressure.

problem is, it breaks the layout because the text is slightly longer now ... i think on todays' high-res screen it would in general be better to have longer lines on all tooltips. but how can this be achieved?

**Comment by LoneGazebo** [comment]
@JFDaly is probably the candidate most likely to know, but I haven't seen him 'round these parts for a long time...

**Comment by JFDaly** [comment]
You would need to create a custom tooltip box to be called when hovering over the city banner, since the auto-width stuff is done internally somewhere.  

The TopPanel.lua file has an example, where the tooltips for each Yield is a custom tooltip. They use 'ToolTipType="TooltipTypeTopPanel"'' instead of 'ToolTip;' the latter just accepts a text string, the former refers to the tooltip box object which is located at the bottom of that same file ('<ToolTipType Name="TooltipTypeTopPanel" >. This box can be edited to mimic the default tooltip style (probably does already in the TopPanel example) and its width adjusted as needed.

**Comment by ilteroi** [comment]
thanks for the hint but .... uah. lua is just not my thing.
