### ISSUE TITLE
Compiler hangs after first pass

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8086]
@IanE9 Any idea what's responsible?

![Screenshot](https://user-images.githubusercontent.com/66801010/122942851-822a9e00-d344-11eb-9a18-d7c58f46b9ba.png)

**Comment by RecursiveVision** [comment]
Okay, it eventually completed the build, but there's several new warnings that weren't there before:

![8417fd627f824840c2f7b66912fd0b57](https://user-images.githubusercontent.com/66801010/122943007-a5ede400-d344-11eb-90c9-48d7089c4526.png)

**Comment by LoneGazebo** [comment]
I can confirm those three same warnings.

**Comment by IanE9** [comment]
The autovaribles branch has had Whole Program Optimization enabled for awhile which I know for certain is responsible for the hangs. The code generation happens at link time and VS2008 just doesn't do a good job at communicating that any work is happening. This should only happen for release builds and is just the regular behavior. It can be disabled if it's too much of a bother.

I hadn't noticed those warnings before, but I'm pretty sure it just means that the world builder library was compiled with different options than what we're using. The macro ``_HAS_EXCEPTIONS`` is probably responsible. The warning is probably only happening now because Whole Program Optimization offers the compiler a better opportunity to check if all types are correctly sized, though this is a problem even without it on.

**Comment by RecursiveVision** [comment]
@IanE9 If it's improving performance and such for the end user I don't mind a couple mins of delay, but I use the compiler to test my code for build errors too, so could you point me to where I can disable it locally when needed?

**Comment by IanE9** [comment]
Absolutely.
![wpg](https://user-images.githubusercontent.com/7848638/122968157-780a9e80-d348-11eb-8165-63c53dc2221b.png)

**Comment by RecursiveVision** [comment]
@IanE9 Disabling that did indeed clear the warnings and restore the compiler to normal speed. Maybe we should make a note of that on the repository's main page under the help info...

What does Whole Program Optimization do, by the way?

**Comment by LoneGazebo** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization?view=msvc-160
