### ISSUE TITLE
reproducable crash on loading savegame

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8107]
![image](https://user-images.githubusercontent.com/1358966/123868976-b4359480-d930-11eb-96e6-04c2dceeafe2.png)

saving and loading with a6448660519a3604795b2567f6fc025a253e361a

anyone else seeing issues?

**Comment by RecursiveVision** [comment]
@IanE9 redid the serialization.

**Comment by IanE9** [comment]
I'm trying to reproduce now. @ilteroi how far does the game need to progress before this starts happening?

**Comment by ilteroi** [comment]
it was an autosave after 300 turns of autoplay. i'll check again

**Comment by IanE9** [comment]
> I am getting almost the same crash as in the screenshot, only 1 line higher with unreasonable values in loadFrom's fields and no other useful stack frames - it is apparently only reading garbage at that point. The save data hash mismatch warning is there as well, despite me using the same mod set as the creator of the [savegame file](https://drive.google.com/drive/folders/1qgDLi8IeRqc4mMufOSsAixf5REfF4bnb), the commit id is correct at least.
> 
> Some people appear to be able to load the save, others can't. Any ideas on how to further investigate this?

I'm not sure at all what is up with the provided save. When I attempt to load it I get past the game hash check (which fails as described) and then I crash when the game attempts to read the embedded git hash.

More info regarding how this save was generated would be useful, but the present crash would suggest to me that it was made on a game version from before we started tracking the git hash. If this is true it would also account for the game hash check failing because the save is dated.

**Comment by sfPlayer1** [comment]
The logged commit id is exactly the same as the one referenced by the 1.4.6 tag in this repo, As far as I know the save was created using the 2 mods in the linked gdrive share by starting a new game, using restart game a bunch and then saving on turn 1. See [CustomMods.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8179603/CustomMods.log) - DeserializationCallstack.log is empty.
