### ISSUE TITLE
suboptimal pantheon choice

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#813]
![image](https://cloud.githubusercontent.com/assets/1358966/11395874/0d0a9f7e-936e-11e5-9bea-735ff18a4742.png)

india should have gone with sacred path i guess ... open sky makes no sense at all here

**Comment by LoneGazebo** [comment]
There's a random chance that they'll pick sub-optimally, as they look at the top 3 choices (IIRC) and do that, regardless of delta between choices.

**Comment by Heinous-Hat** [comment]
That explains a lot.

 I play often on dense forest maps and noticed Sacred Path going unclaimed despite it being (likely) the optimal choice for many start positions. Even in it's present, nerfed state, it can still grab up to 6 culure/faith, effective instantly. 

What's that about? Player comfort?

**Comment by LoneGazebo** [comment]
What's what? The randomness? It is to keep the AI from picking the same pantheon(s) over and over again. Firaxis used this randomization model throughout the AI to give it some element of, well, randomness.

**Comment by ilteroi** [comment]
randomness ok, but it's a weighted draw. this choice is so bad it can't really be random ... i have the save will try and see whats going on

**Comment by LoneGazebo** [comment]
I have worked on the belief choice a bit - it wasn't accounting for features properly.
G

**Comment by Heinous-Hat** [comment]
Yeah, I meant randomness for it's own sake (in the vanilla design). It works much better with CBP since there aren't an abundance of 'worthless' choices anymore. Even accounting for map peculiarities, there are a lot of effective selections (kudos :+1: ) But in the case of something like Sacred Path going unclaimed on a very woodsy map (with most start positions in the thick of it)... it comes off as "too deliberate".

If you've adjusted the selection to weigh features more heavily, that sounds like what's missing :)
