### ISSUE TITLE
7-1 AI and ships being built in lake cities

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#8175]
While it could be sometime smart to build lighthouses or ships in cities with only a lake access, I think it should be reverted and disallowed due to the AI being unable to evaluate properly when it's worth to do.

![civswe](https://user-images.githubusercontent.com/53142313/128604100-4b4b41c9-29d1-4164-aef4-f7a03ac629d1.png)

Just one of countless examples of wasted hammers/supply, and there's no way for that city to be ever connected to open sea with forts (another 1 tile lake to the west and that's it)

**Comment by DeAnnoCiv** [comment]
I think lighthouses are usually worth it because they at least give supply, which is generally useful. Also in a landlocked empire having one lighthouse city makes any food routes you have much better. Ships though (in particular melee ships!) should definitely not be built without a route to real ocean available.

**Comment by ilteroi** [comment]
it might be a gifted unit. do they have any other coastal cities?

but anyhow they should disband useless units. so something might be wrong after all.

**Comment by azum4roll** [comment]
As Authority keeping one conscripted ship as garrison is fine. But the other should be deleted.
