### ISSUE TITLE
sync archive

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8345]
i just stumbled over this piece of code here:
```
SYNC_ARCHIVE_BEGIN(CvPlot)
SYNC_ARCHIVE_VAR(char, m_eFeatureType)
SYNC_ARCHIVE_END()
```

it seems to be related to multiplayer ... and i can even understand why not all members are included, after all most plot properties are constants. but why for example no improvement type?

and then there's the fact the we only have sync archives for plot, player, unit and city. they have hundreds of entries but the original classes have more. how to decide what is needed?

how can multiplayer work at all?

**Comment by IanE9** [comment]
This confused me as well when I was going working with the sync code. It's particularly confusing because sync vars do not actually enforce synchronization between players, they are only used to verify that the game state is synchronized between turns.

This is a summary of my understanding:
By declaring ``m_eFeatureType`` as a sync var, we only inform engine DLL that we want ``m_eFeatureType`` to be checked at the end of a turn. The value is serialized and sent to all other users. If one user reports that their value does not match another user's value, the entire game state is saved by the host and sent to the clients. This is what causes the game to return to a loading screen during multiplayer sessions and is the mechanism responsible for resolving sync errors. Maintaining a synchronized game state without reloads must as a result be accomplished by ensuring that all players react to networked 
_events_ in the same order and manner.
