### ISSUE TITLE
Hoplite's Discipline promotion only adds 15% once instead of for each adjacent friendly unit.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#8349]
1.1.3

![image](https://user-images.githubusercontent.com/22875626/138619438-a0be26c6-cf82-4d09-a034-a1ca60be199d.png)
![image](https://user-images.githubusercontent.com/22875626/138619449-7a471a0b-9dfb-4e02-9e45-588e5d8fc70c.png)

**Comment by LessRekkless** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/blob/d345671cd429de86b37f24507186af890ed1b4ba/Community%20Balance%20Overhaul/Balance%20Changes/Units/PromotionChanges.xml#L1211-L1223
The Discipline promotion uses `AdjacentMod` instead of `UnitPromotions_CombatModPerAdjacentUnitCombat`
https://github.com/LoneGazebo/Community-Patch-DLL/blob/d345671cd429de86b37f24507186af890ed1b4ba/Community%20Balance%20Overhaul/Balance%20Changes/Units/PromotionChanges.sql#L154-L164
