### ISSUE TITLE
New unit doesn't get pushed out of the city on coastal (island) city

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8448]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_
1.2.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
![](https://i.imgur.com/o1QzfgB.jpeg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
so what is the problem?

**Comment by bsesar** [comment]
@maarten99, I think this is intentional behavior. If I recall correctly, either on the forum, Discord, or on GitHub someone requested to have units spawn in the city even when there is already a garrison you can pick where to move them. This may be useful when the city is under siege. Can you move the units out on your own?

**Comment by maarten99** [comment]
Yes, they are both movable
