### ISSUE TITLE
free gold is back!

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8477]
v 1.2.1, not main branch

![image](https://user-images.githubusercontent.com/1358966/147289917-639368ea-8548-434d-be2e-02e312e6ca00.png)

i thought AI would not offer gold for embassy any more?

**Comment by RecursiveVision** [comment]
Lump Gold, not GPT

**Comment by RecursiveVision** [comment]
Gold Per Turn is less exploitable than Gold, and one of the two needs to be offerable...

**Comment by ilteroi** [comment]
> Gold Per Turn is less exploitable than Gold, and one of the two needs to be offerable...

why?

**Comment by RecursiveVision** [comment]
To permit civs to exchange Embassies before both have researched Writing? That early in the game there often isn't anything else you can offer. We could change it so that both civs must have researched it, but that'd be a balance change. The worth of embassies is so low anyway that I don't think this is an issue.

**Comment by ilteroi** [comment]
ok compromise: AI will just not *offer* embassy for gold anymore, but if you really want to you can still swindle them out of some gold

**Comment by RecursiveVision** [comment]
Milae rewrote the deal equalization logic to always equalize the deal using Gold - modifying this may upset players. Not sure if your change does that.

**Comment by RecursiveVision** [comment]
Looks good!
