### ISSUE TITLE
GetReligionInMostCities  vs GetCurrentReligion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8500]
see title, what is the difference between GetReligionInMostCities() and GetCurrentReligion()?

it seems GetReligionInMostCities is just counting cities and GetCurrentReligion is looking at holy city ownership. but does it make sense to have both?

then there is also GetReligionToSpread(), which combines both aspects ... but many places in the code use one or the other. seems prone to confusions.

additionally there is GetStateReligion() which seems to be something else again, but i don't care as much because it's a modmod.

**Comment by inkyant** [comment]
I think it needs to be more standardized than it currently is. There's a list of things that could be your religion: the majority religion, the holy city you own, the religion you founded, etc. And in case you don't have one we should know in what order precedence takes.

Then maybe a function like CvPlayer::GetEffectiveReligion() that we just use when we need the player's religion, so standards are easy, but also because code like this is tiresome just to get a holy city (and doesn't even cover all cases):
![image](https://user-images.githubusercontent.com/80181074/147868684-0f2c5c25-847f-4367-9639-2704ba0e2a42.png)

**Comment by psparky** [comment]
To me, they represent different concepts. Each affects which beliefs apply, and also impact diplomacy and strategy.

That's not to say that some cleanup isn't appropriate, and perhaps a few utility routines could be added to avoid repeating certain blocks of code.

**Comment by ilteroi** [comment]
ok so it seems "current religion" should be "state religion". and "religion in most cities" is one aspect considered the selection of the state religion, holy city ownership being another ... 

"religion to spread" is difficult because it should differentiate between actively converting other players (which the founder might do) and trying to hold on to your own state religion (which any player might do). what a mess.

**Comment by inkyant** [comment]
And of course don't get confused by JFD's modmod DLL code which has an entirely separate thing called 'State Religion'.

Here's my suggested order. It is decided by Holy city for civs with one, then by majority religion for those without one. If you own multiple holy cities, the one with the most converted cities in your empire is your religion. So that way if you conquer a new Holy City and decide you like it better than your current religion you can convert your cities to the new Holy City's religion if you like.

This may be the way it already works in many cases but it's certainly not consistent.
