### ISSUE TITLE
1.3.4 Silver Placement

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#8508]
VP Only, Standard Random (Continents) map

As somebody else already reported on forum, starting next to a silver monopoly is currently a bad option, because all the grassland/plain silver doesn't spawn anymore.

![civnosilver](https://user-images.githubusercontent.com/53142313/147911833-d8a300de-c353-476f-9ce7-752075301283.png)

Personal opinion, I don't like silver placement changes even if this gets fixed. It should be allowed to spawn on plains and civlopedia changed to reflect that if you want to stay true to realism.

**Comment by azum4roll** [comment]
Wouldn't the same happen for all terrain-specific luxuries then? I'll see what I can do.

**Comment by jayeye2011** [comment]
Terrain-specific luxuries really seem like a bad idea. I can understand living biological resources like fish or bananas being terrain -environment specific, but in the real world non-biological resources can show up wherever. Also, it might very well be that Firaxis  while originally putting in the text description actually later removed the code implementation because of this non-game practical side-effect?

**Comment by azum4roll** [comment]
Try the version in #8523
