### ISSUE TITLE
Religion is not transfered on conquering holy city

### ISSUE THREAD

**Issue by CliveJarman** [LoneGazebo/Community-Patch-DLL#8709]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_
Unique components 0.75, Milae's Alternative difficulty mod v11

_3. Error description:_ 
I captured Beijing as Rome. I did not found a religion. Beijing was the holy city for Taoism. After capture I cannot create inquisitors
and do not get any benefits from Taoism religion even though it has been enhanced and reformed. Beliefs religion screen shows Rome as the founder. My religion shows just my pantheon. When I create a new city ig gets my pantheon so its as if the game does not treat me as the founder of Taoism after capture.
_4. Steps to reproduce (optional):_

-------------
[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8157700/saves.zip)
--------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LessRekkless** [comment]
>Beliefs religion screen shows Rome as the founder. My religion shows just my pantheon.
Currently intentional. To be updated in the future.
>When I create a new city ig gets my pantheon so its as if the game does not treat me as the founder of Taoism after capture.
Intentional. New cities never get your religion.

First test:
![image](https://user-images.githubusercontent.com/34615525/156427577-d8022b11-d2c2-4311-be8e-ffbc5dcdf4d2.png)
Enhancer is functioning, Might be because it's limited to my holy city
Founder functioned after Tengriism became my Majority Religion.

![image](https://user-images.githubusercontent.com/34615525/156427681-8e14aff0-6368-4a2f-b245-0460d47a1d71.png)
Non-holy city doesn't contain Founder or Enhancer beliefs on the tooltip, but both of them are limited to holy city anyway so that may be the reason.

Can't buy inquisitors even after Tengriism becomes Majority Religion.

**Comment by adaneslavo** [comment]
Isn't this thread the same like [this](https://github.com/LoneGazebo/Community-Patch-DLL/issues/8787)?
