### ISSUE TITLE
When purchasing units with gold or faith, only one promotion can be applied. Additional promotions can be applied next turn.

### ISSUE THREAD

**Issue by calloatti** [LoneGazebo/Community-Patch-DLL#8790]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.3, DX 10 & 11):_

2.0.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

When purchasing units with gold or faith, (units that will get more than one promotion), only one promotion can be applied when the unit is purchased.

Additional promotions can be applied on the next turn.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LessRekkless** [comment]
Looks like it's caused by the `CvUnit::canAcquirePromotionAny()`
https://github.com/LoneGazebo/Community-Patch-DLL/blob/1a03acf208685ebef10bac477b45302dea739a2d/CvGameCoreDLL_Expansion2/CvUnit.cpp#L26258-L26264
and the change to `CvUnit::isOutOfAttacks()`
https://github.com/LoneGazebo/Community-Patch-DLL/blob/1a03acf208685ebef10bac477b45302dea739a2d/CvGameCoreDLL_Expansion2/CvUnit.cpp#L24279-L24283
in commit b556d3fc7a47eff3b3b2f0c00c677836ec85e7a2.

**Comment by calloatti** [comment]
Not a big deal anyway, could be kept as is I guess.

**Comment by RecursiveVision** [comment]
@LessRekkless It's an unintended side effect.
