### ISSUE TITLE
DiploAIOptions Feature Request

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#8816]
First of all I would love to see DiploAIOptions moved to an easier place to find it in the file directory :-)

But my real request is an option to edit/remove the requirement for 75 warscore in order to broker peace.

I personally think once 10 turns goes by it should be available no matter what the warscore.

**Comment by RecursiveVision** [comment]
@usadefcon1 The reason it's this way is because the third party might not want to end the war, and you can't negotiate with both in the same deal. A high warscore guarantees that it's in the losing player's interests.

I could add this easily, but it'd be exploitable and may screw you over if you're losing a war.

**Comment by RecursiveVision** [comment]
added

**Comment by usadefcon1** [comment]
Thank you, I'll start conservatively with 50 🙂
