### ISSUE TITLE
Rarity of AI city capture

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8920]
i have to agree with a forum post: it seems AI players capture cities relatively rarely nowadays.

there are some balance issues which are mentioned:
* cities have too many hitpoints, it's hard to arrange enough units for an effective attack
* there are too many units around in general, favoring the defender

open questions from an AI perspective:
* have the defenders gotten better or the attackers worse?
* is it possible that the AI players peace out too early?

some simple ideas to implement:
* bought units are damaged proportional to city damage
* reduce supply, generals/admirals only give +1
* road building in one turn for increased mobility

opinions? further ideas?

**Comment by azum4roll** [comment]
Roads favour the defender, and AI doesn't spam them near their borders unlike humans.

**Comment by ilteroi** [comment]
yeah the road thing is not so simple after all, needs some additional AI logic. would be nice for legions though.

**Comment by nobubblegums** [comment]
Was just about to post this on forums, better write here as well. I don't feel like the abundance of units has an significant role in this, I've been playing with reduced supply cap (and proportionally reduced city hp&defense) for a loong time and city capture is still rare. That said, tweaking the ratio of supply caps gained when going for domination vs. other styles can be good. Tradition&tall is in a fine place, but wide&progress plays get so much supply that they can easily defend against authority. 

About the AI performance, I've been playing since ~ 1.2.x and it hasn't gotten better or worse. One thing I notice quite often is the AI's lack of commitment to offense. They don't push their numerical advantage as much as they should, instead sending units piece-by-piece to get slaughtered at chokepoints. Sadly I didn't capture the exact moment, but this is still illustrative:
[20220601180334_1](https://user-images.githubusercontent.com/94949778/172062152-d3795ea4-0850-467f-a3f0-d2e969d22cef.jpg)

England has been trying to capture Kyzyl from the start, they got pretty close in previous eras when I didn't have much units.. Even then, they kept a huge reserve army around Warwick, while sending only a couple units to Kyzyl. I've never made an offensive maneuver against them, my military was consistently ranked as one of the worst, so such caution just didn't make sense. If they made a mass human wave attack, they could've taken Kyzyl and a lot of my cities for sure.

It's also easy to distract the AI from sieges. Polynesia was often able to encircle my&allied island cities, but I could distract them easily by a few ships.

I didn't have an issue with AI peacing out early. 

I think AI should spam a lot more roads esp. since they don't have a problem with gold. They seem to do that for their forts, so maybe making them build more (&offensively placed) forts would help.

I like the idea of damaged units. I think making the melee units blockade adjacent tiles like the naval ones can also help a bit.

**Comment by ilteroi** [comment]
extending the land blockade range is also a good and simple idea. was always inconsistent.

regarding distraction, that's a hard problem. the current approach is to establish superiority and only then go for the city ...

i'll check the reinforccements.

**Comment by ilteroi** [comment]
i think i may have found the culprit. the war state is often DEFENSIVE but that prevents the creation of city attack operations. 

```
				int iDangerPercent = (iTheirDanger * 100) / max(iOurDanger, 1);
				if (iDangerPercent < 100)
				{
					if (WarScore >= 25)
						eWarState = WAR_STATE_STALEMATE;
					else
						eWarState = WAR_STATE_DEFENSIVE;
				}
```

so after the initial round of fighting, both sides just wait it out ...

**Comment by LoneGazebo** [comment]
>reduction of supply from generals/admirals 

What do you mean?

**Comment by RecursiveVision** [comment]
@LoneGazebo A while back I made the unit supply from expended GG/GA its own value instead of adding it to the capital's supply (so it was unaffected by tech reduction).

ilteroi reduced the supply cap increase from 2 to 1 in his changes.

**Comment by ilteroi** [comment]
@RecursiveVision : still not sure about that code in DoUpdateWarState() ... say an AI player loses a city. as it stands now, their warscore will drop below -25, they will go defensive and will not start an operation to try to get the city back. if you have better ideas, go ahead!

**Comment by RecursiveVision** [comment]
I removed that bit, with the rationale that if they're not in danger they should err on the side of being in offense.

**Comment by RecursiveVision** [comment]
Also added some extra logic so that other parts of the AI don't mistake "stalemate" for "we're doing about evenly" if they're losing. Next version's logic should be good. 👍
