### ISSUE TITLE
CTD during AI turn 12/6 version

### ISSUE THREAD

**Issue by aht820** [LoneGazebo/Community-Patch-DLL#896]
I've been experiencing a CTD during the AI turn on this game. If I reload the save I'm able to play a few more turns but the game will continue to crash. The log files are linked below. 

https://www.dropbox.com/sh/mc92b1e8k26kpno/AABWbNRCzr7LegSWyfpBhrm_a?dl=0

**Comment by LoneGazebo** [comment]
Minidump?

**Comment by Edaka** [comment]
As there have been plenty of crash reports on the last couple of pages, I thought gathering them in one place could be useful. This seems like a good place. Some of them from older versions might not be worth looking at, but that's for you to decide (:

akasha27: "CTD on the last stable version (11/20). It happens between turns, during AI (Spain) turn." 
[CvMiniDump11.20.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/56237/CvMiniDump11.20.txt)
[logs11.20.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/56238/logs11.20.txt)

Forsti: 'Full CPP (11/28) with EUI, no other mods. I tried to negotiate peace with Pacal. He offered me a bunch of gold and a city. Accepting the offer caused the CTD. I first thought it was because I hadn't seen the city, but any accepted offer with his city causes a CTD, so it's not that. A offer that doesn't include a city works just fine.' 
[CvMiniDump11.28.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/56233/CvMiniDump11.28.txt)

Der_Zorn_gottes provided only logs from a 12/6 crash. I've asked him to post a minidump, so I'll update this if/when he does.
[CrashLogs12.6.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/56234/CrashLogs12.6.txt)

Iamblichos crashing on the 12/6 version.
[CvMiniDump-CPP12-6(1).txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/56243/CvMiniDump-CPP12-6.1.txt)
[CvMiniDump-CPP12-6(2).txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/56244/CvMiniDump-CPP12-6.2.txt)

All files' extensions renamed from .rar to .txt. Haven't included King Coltrane's since you've obviously deduced that one already. The other files also had 1-2 views, except for the akasha's and the Forsti's one which had zero, although they both are from older versions.

**Comment by aht820** [comment]
The minidump is included in the folder. I'm using the full version with EUI, cheap workboats, enable magellin, and rotate starting position.

**Comment by LoneGazebo** [comment]
Thanks! I've dealt with a lot of these, but some are new.
G

**Comment by Edaka** [comment]
I'm sorry, Gazebo, turns out Der_Zorn_gottes's minidump is actually also included in his archive. I thought it wouldn't be there because of the name. Just a notice in case you haven't noticed (hehe) like me.

**Comment by LoneGazebo** [comment]
Thanks, yep.

**Comment by LoneGazebo** [comment]
All looked at and addressed where valid. Thanks!
