### ISSUE TITLE
Otoman UA

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#921]
Two issues:
In Industrial age. I get 400 of each yield when a TR completes.
Industrial is age 5, so shouldn`t it be 500? 
Second, it doesn`t scale with gamespeed, on Marathon it should be three times as much.

**Comment by Edaka** [comment]
IIRC, industrial's coefficient is actually 4. That's because the coefficient for both the ancient and the classical era is 1 and it only starts counting from there onwards (medieval - 2, renaissance - 3, etc.). It's weird, but everything should be balanced around that.

It should probably scale with gamespeed, though.
