### ISSUE TITLE
caravansaray on islands

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#925]
AI really likes the caravansaray, it even builds them on one-tile islands. these are the scores for the possible next production item on a typical island city:

185, England, Coventry, Building, Caravansary, 5089, 13
185, England, Coventry, Building, Harbor, 4284, 21
185, England, Coventry, Building, Library, 3934, 9
185, England, Coventry, Building, Market, 3181, 7
185, England, Coventry, Building, Lighthouse, 2801, 9
185, England, Coventry, Unit, Work Boat, 2712, 3
185, England, Coventry, Building, Monument, 2374, 5
185, England, Coventry, Building, Forge, 1988, 9
185, England, Coventry, Unit, Caravel, 1878, 13
185, England, Coventry, Building, Aqueduct, 1816, 13
185, England, Coventry, Building, Granary, 1761, 4
185, England, Coventry, Building, Walls, 1205, 7
185, England, Coventry, Building, Colosseum, 1011, 9
185, England, Coventry, Building, Barracks, 998, 7

don't know exactly how this is calculated, can you tone it down a little bit?

FYI, top flavors seem to be ok:

FLAVOR_CITY_DEFENSE		99
FLAVOR_NAVAL_RECON		116
FLAVOR_NAVAL_TILE_IMPROVEMENT		168
FLAVOR_SCIENCE		184
FLAVOR_GOLD		202
FLAVOR_CULTURE		341

**Comment by ilteroi** [comment]
ps: they also really like to build hotels in cities which don't generate a lot of tourism. 

a hotel on an island makes sense though. so the question is, change the hotel (give it a specialist slot?) or make it less attractive to build if the projected output is not adequate?

**Comment by LoneGazebo** [comment]
It's probably because of things like poverty. They tend to go after econ buildings when poor.

Here's a question - should we expand the 'buildsanity' function you designed a while back to include buildings, and perhaps check for these sorts of fringe cases? i.e. Hotel check for tourism, caravansary for current trade routes, etc?

G

**Comment by LoneGazebo** [comment]
Yeah, I'm going to do this - I'll take care of the buildsanity stuff.

G

**Comment by ilteroi** [comment]
ha. that's funny. i saw that UnitBuildSanity function - but i assumed it's from you? anyway i can't remember writing it, must have been a while ago. seems to be for units only at the moment

**Comment by LoneGazebo** [comment]
Yep - I've now written a buildingsanity one and I added in checks for sanity for geography and some scenarios (like hotels). I didn't zero out the values on all of them (they'll need to be tweaked) as, in some cases, only part of a building is a bad idea (rather than all of it). We'll see if it normalizes some things.

G
