### ISSUE TITLE
Moving on mountains. Shooting through mountains.

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#931]
As a non-Inca civ, I cannot move my units on mountains with roads (even if the unit stands on a roaded tile).
As a corrolary, melee units cannot attack Incan units on (roaded) mountain tiles.

**Comment by ilteroi** [comment]
will check, should work now

**Comment by Edaka** [comment]
It seems that barbarians are still experts at mountaneering. 
http://forums.civfanatics.com/showpost.php?p=14097856&postcount=31

**Comment by ilteroi** [comment]
cannot reproduce. maybe an old version?

**Comment by Edaka** [comment]
Could be, although it was posted in the thread for the 12/18 version.

**Comment by Edaka** [comment]
ilteroi, could you check units seeing/shooting through mountains again, though? Seems it's back:
http://forums.civfanatics.com/showpost.php?p=14099077&postcount=40
http://forums.civfanatics.com/showpost.php?p=14098766&postcount=4065
There's also an interesting graphic bug in that second link, but I don't know if the recent mountainworks have to do anything with that.

**Comment by Edaka** [comment]
PurpleMentat: "Something odd seems to be going on with natural wonders. Specifically, I haven't seen any of the 'mountain' types despite starting multiple maps to look for them. I tried loading up In Game Editor to cheat some in, and on reload they were replaced with standard mountains. "
Necamijat: "I think they are replaced by regular mountains (could be ilterois "can't settle on them" code, since this was after the hotfix version), since I've seen a mountain with a Sri Pada graphic. "
Well, that probably explains the graphic bug.

**Comment by ilteroi** [comment]
the missing natural wonders are fixed.

shooting through mountains, haven't seen it lately

**Comment by Edaka** [comment]
Nice. Regarding shooting through mountains - I've seen a couple of users report it, but it probably needs very specific circumstances to be reproduced. I'll try to get a save from the next person experiencing that (shall that happen), or someone could post it here himself/herself.
