### ISSUE TITLE
Disappearing religious followers

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#936]
Originally posted by Gidoza: "I got a Religion earlier than everyone else in this particular game - I spread the religion to someone else's capital. That player has no religion, and neither does anyone else nearby. I look a few turns later to see that this city that had 5/9 followers has decreased to 3 of 9 followers - and that includes one of my own cities and a trade route giving pressure."

**Comment by ilteroi** [comment]
as far as i can see, the followers are only recomputed for specific reasons (not every turn).

reasons are

    FOLLOWER_CHANGE_POP_CHANGE,
    FOLLOWER_CHANGE_HOLY_CITY,
    FOLLOWER_CHANGE_ADJACENT_PRESSURE,
    FOLLOWER_CHANGE_RELIGION_FOUNDED,
    FOLLOWER_CHANGE_PANTHEON_FOUNDED,
    FOLLOWER_CHANGE_CONQUEST,
    FOLLOWER_CHANGE_MISSIONARY,
    FOLLOWER_CHANGE_PROPHET,
    FOLLOWER_CHANGE_REMOVE_HERESY,

now, if the most common is probably population change. atheists also have religious pressure. when your religions's pressure is lower than the atheism pressure, it can happen that you actually lose followers (because of the way the rounding is handled).

the system is not very straightforward. i do think some changes are in order, but i'm not sure what to do exactly, don't fully understand it yet

**Comment by ilteroi** [comment]
further findings: 
- religious pressure is not re-calculated each turn but updated
- when a citizen is born, 1000 pressure is added to atheism
- each turn, a neigboring religious city exerts a pressure of 60 (base value before modifiers)
- holy city, spies etc added separately
- religion displaces pantheon pressure, but not atheism pressure
- so you need to overcome a threshold of religious pressure per turn to "outgrow" atheism

example: city is growing every 8 turns. you need at least two neighboring cities adding their pressure to keep up with the atheists. otherwise your religion will slowly fade away.

not such a bad model actually, i have seen much worse :)

**Comment by LoneGazebo** [comment]
Aggressive atheism. Heh.

**Comment by LoneGazebo** [comment]
Haven't seen this in a while, so closing for now.
