### ISSUE TITLE
3.0.4 My units can't get any XP :(

### ISSUE THREAD

**Issue by brsoft1981** [LoneGazebo/Community-Patch-DLL#9523]
1.  3.0.4

2. DirectX Version

3. Only Community Patch

4. So, I'm playing with Japan. From some point of the game, my units stopped gaining any XP

______________________________________________________________________________________
5. Attached [Ivo.Civ5Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10166749/Ivo.Civ5Save.zip)

6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)

7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

8. Steps to reproduce the Issue (Optional)

9. Screenshots of the Issue (Optional)_

**Comment by JtG82** [comment]
I have the same problem. Against barbarians or city states the xp is coming, but not against other major civs. Therefore I did a little digging and testing. I noticed that it happens only when playing on "Marathon" game speed, other speeds are fine. I also tried the game on previous version (2.7.3.) and it worked fine on all speeds. 

So my wild guess is that it might have something to do with this new change in "cvunit.cpp" for it affects only normal combat and not barbarians or city states:

"
if (MOD_BALANCE_CORE_SCALING_XP)
	{
		iMaxValue *= GC.getGame().getGameSpeedInfo().getTrainPercent();
		iMaxValue /= 100;
	}
"
(Link to the change: https://github.com/LoneGazebo/Community-Patch-DLL/commit/391d8fcf0b329ed72a6372a0abac3eaf744fa510 )

Since the marathon gamespeed has ID "0" on civ5gamespeeds.xml, is it possible that the code on some point multiplies the xp value with the ID number and thus it ends up giving zero xp on marathon?

**Comment by brsoft1981** [comment]
Yep, I'm playing on 'marathon' speed too, so maybe that's the issue.

**Comment by alex-me642** [comment]
hi.  

> iMaxValue *= GC.getGame().getGameSpeedInfo().getTrainPercent();

the problem here is not getTrainPercent(), but the multiplication itself.   When an unit battles with barbarians or with civ states, iMaxValue above is defined as some const but with real civs it's equal to INT_MAX and the multiplication gives as integer overflow - most probably negative value.

it should be fixed ASAP, currently exp & promotion logic has been broken.

**Comment by alex-me642** [comment]
hi, the logic is okay, and for barbs and civ states it works properly.

The problem is that for **regular** civs the code is absolutely broken (at least for non-default speeds) because when the algo performs:

iMaxValue *= GC.getGame().getGameSpeedInfo().getTrainPercent();

it will get the int overflow, because iMaxValue in this case is defined as INT_MAX, and the multiplication gets **negative** value, and as result unit gets ZERO experience.   For civ-states and barbs iMaxValue  is redefined and so for them there will be no this problem.

**Comment by youngsteve11** [comment]
Another having similar issue. Did clean install, thinking that might resolve the issue, but then saw this thread & the one at civ fanatics, & knew it was more than that.

**Comment by JtG82** [comment]
I found a little workaround for the marathon xp problem. If you change the marathon's training percent from 300 to for example 299 in gamespeeds.xml, units again get xp from combat with other civs.

**Comment by qsqsqsqsqss** [comment]
> I found a little workaround for the marathon xp problem. If you change the marathon's training percent from 300 to for example 299 in gamespeeds.xml, units again get xp from combat with other civs.

Unfortunately not working for me. Have you tried the newest VP from January?

**Comment by qsqsqsqsqss** [comment]
> > I found a little workaround for the marathon xp problem. If you change the marathon's training percent from 300 to for example 299 in gamespeeds.xml, units again get xp from combat with other civs.
> 
> Unfortunately not working for me. Have anyone tred the newest VP from January?

Seems like new update solved the issue. Unfortunately cannot load an old game.
