### ISSUE TITLE
Walking On Water + Ranged VS Pikes

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#968]
1.  Problem with Barbarian Horde spawning:  I've got a game here where some Pikemen are spawning on the water.  They can also walk on the water and attack from the water, but are NOT embarked.  They take damage as though they were on land, but cannot be attacked by land units.

I have a saved game of this, but GitHub is saying that this file type is not supported.  How do I get it to you?

2.  Just an observation that I thought was weird and in my opinion is worth a re-work.  When a Ranged Mounted unit attacks a Pikeman/Spearman, the +50% VS Mounted Units is still applying on the Pike/Spear for the damage calculation.  Now, I understand the +50% bonus when attacking a mounted unit or if a Horseman/Knight attacks a Pikeman, but when a Ranged Mounted unit is making the attack - isn't an arrow an arrow?

**Comment by ilteroi** [comment]
spawning on water was a bug in 12/18 but there's a hotfix out now. check the forum!

**Comment by Iamblichos** [comment]
Question: will the hotfix force them to spawn on land or do you still have the failsafe forced embark if on sea tile?

**Comment by ilteroi** [comment]
spawn on land only. "forced embarkation" is gone

**Comment by Iamblichos** [comment]
![2015-12-21_00001](https://cloud.githubusercontent.com/assets/14372214/11938728/68c46f1a-a7e2-11e5-98b5-4c31d74ae0f0.jpg)

ilteroi, I believe the unit is not technically embarked because I have a check in the mod to add a promotion to the unit if not, but the graphic is still embarked and so the unit won't fire although it gives the radius to fire.

**Comment by Iamblichos** [comment]
![2015-12-21_00002](https://cloud.githubusercontent.com/assets/14372214/11939081/1db35d44-a7e5-11e5-9d64-84e6a19c12e7.jpg)
Here's what it ought to look like, this is the default DLL in the 12-18 CP (notwithstanding the other issues that were in that version).

**Comment by ilteroi** [comment]
ok it seems there is a check in CvUnit::canEverRangeStrikeAt() which prevents ranged attacks from embarked units. now the problem is, it works for hypothetical plots also (i.e. assuming the unit is at x, would it be able to attack y). so it doesn't look at the actual embarkation status of the unit but whether the assumed source plot for the attack requires embarkation. and it doesn't know about your transport mod. not a trivial thing. 

don't know what changed between 12-18 and the hotfix btw, but this is my current theory

**Comment by Iamblichos** [comment]
Perfect. It's fixed.
