### ISSUE TITLE
Freeze upon hovering over city banners

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#975]
At least couple of second worth freezes when hovering over city banners (with EUI) are being reported by Aristos and SeverelyLate on the forum. I think we've been there before, but then you fixed it, Gazebo? I'm not sure I'm remembering things right, but it seems it's back again now.

**Comment by LoneGazebo** [comment]
EUI's banner code is really expensive.

**Comment by Edaka** [comment]
Yeah, slowdowns of that EUI's element in the lategame have always been a thing, as far as I remember, but users on the forum only started reporting that problem since one of the latest versions' release. I wonder if CBP's code could possibly interfere to cause that - as I've said, I used to experience significant freezes myself at some point (a couple of months ago), but then they seemed to vanish.

**Comment by LoneGazebo** [comment]
I think Aristos had a fix. Do you know where, if anywhere, that he posted the fix?

**Comment by Edaka** [comment]
Not that I know of, but I've sent a private message to him.

**Comment by ricanuck** [comment]
Me here... it ended up more like a work-around than a fix, that's why I did not post it. Basically, I changed one line where the religious icon callbacks the OnToolTip function to what it was before (a register callback to OnMouseEnter):
cityBanner.ReligiousIcon:SetToolTipCallback( OnToolTip )
That has the effect of keeping the engine running while the tooltip is being generated, instead of freezing the entire thing because the engine is waiting for the entire tooltip to be generated before displaying it. The delay is still there, but it does not freeze the engine and is barely noticeable. Not a final solution, but it helps.

Now, the final solution would be to rewrite the religious tooltip code block. I could not go deep into it yet, but my observations (both first glance at the code and in-game behavior) point to the following: bc1 made the code generate the tooltip for ALL cities in the world at once; so, the first time you mouse over the religious icon, or the city banner if there is no dominant religion, the code works on ALL cities right there, generating the minifreeze. The proof is that after that initial freeze, you can go to any city during that turn, anywhere in the map, and there is no freeze, the tooltip is instantaneous.

To me, that is plain stupid. bc1 has been doing silly "upgrades" for a while now, with decreasing returns. The correct way is to generate the tooltip for the mouse-hovered city only, as that is the one the player is clearly interested in at any given moment (or even if you hover over by accident, as in the in-between-turns...).

If we can, we should take that block of code back to such behavior. Will keep you posted If I see a quick way to do it.

**Comment by LoneGazebo** [comment]
Sounds good - if you want to take point on that it'd be great. Otherwise, send me your fixed banner lua file and I'll merge it.
