### ISSUE TITLE
Crash to desktop when loading save files

### ISSUE THREAD

**Issue by doom-civ** [LoneGazebo/Community-Patch-DLL#9792]
_1. Mod Version (X.Y.Z). Current Version: 3.3.1_
3.3.1

_2. DirectX Version_
DX 10 & 11. 

_3. List of Other Mods_
InGame Editor (v39)

_4. Describe the Issue_
Crash to desktop when loading save files after launching a new session.  The same save worked okay few turns ago. Please note that this is not a specific instance. It happens with multiple save files, in multiple games across multiple sessions. This is happening since the upgrade to 3.3.1. The previous version (the last one in 2.x series has no previous issues).

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11301862/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
Shows 0 bytes for some reason.

_8. Steps to reproduce the Issue (Optional)_
Loading the save file causes the crash. 
[Pedro II_0004 BC-3840.Civ5Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11301864/Pedro.II_0004.BC-3840.Civ5Save.zip)

**Comment by axatin** [comment]
Unfortunately, I can't reproduce this, because I *am* able to consistently load the save file you attached... Can't find anything unusual in the logs either.

In general, when this problem arises, you can try clearing the cache and temporarily removing any unused mods from the MODS folder, that might help.
