### ISSUE TITLE
Inactive Workers

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#9896]
Version 3.6.2

Poland AI has two workers in the city of Kruszwica that aren't doing anything although there are tiles without roads or improvements near the city (for example the deer tile with the trebuchet). There is no immediate danger of being captured there.
![Screenshot (372)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/95587882/2c03be27-b282-4f6a-86d0-a3068a04e155)

[BuilderTaskingLog.csv](https://github.com/LoneGazebo/Community-Patch-DLL/files/11584805/BuilderTaskingLog.csv)

Save game:
[Workers.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11584812/Workers.zip)

Required Mods:
[MODS.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11584849/MODS.zip)

**Comment by saamohod** [comment]
Were you at war with them until recently? Maybe the workers will be active next turn.

**Comment by saamohod** [comment]
Yes, the issue is there.
Version 3.6.2. Turn 200+, only two monopolies exist in the game with 10+ AIs: mine and another sea resource one, created literally a couple of turns ago.

![20230531153931_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/f8eb7ce2-9a86-49f5-ab1e-4bd9cff24e4f)

![20230531153634_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/01919177-5c71-41fe-93fa-08f1fe0acb2d)
![20230531152546_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/bc40e9cd-354f-49ba-b9eb-c456380e7c25)

**Comment by axatin** [comment]
> Yes, the issue is there.
> Version 3.6.2. Turn 200+, only two monopolies exist in the game with 10+ AIs: mine and another sea resource one, created literally a couple of turns ago.

Yeah, so this is because @saamohod used a hotfix file which still included the bug from version 3.6 (see https://forums.civfanatics.com/threads/unit-and-building-maintenance-discussion.683900/), it has nothing to do with the issue here.

The reported issue happened on version 3.6.2, so workers can move in general. I actually was at war with Poland at that point, and once I ended the war, the workers did move, so it is just the AI being overly careful with its workers. If the AI considers the tile east of the silk safe enough for a half-dead trebuchet, it should also consider it safe for a worker.

**Comment by azum4roll** [comment]
Likely already fixed
